import { chromium } from 'playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
const root=process.env.PREVIEW_V2_BASE_URL||'http://127.0.0.1:4173/prototypes/integrated-product-preview-v2/index.html';
const out=new URL('./artifacts/gate-a-screens/',import.meta.url);mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true});const screens=[];
async function open(viewport,entry='account',reviewer=false){const ctx=await browser.newContext({viewport});const page=await ctx.newPage();await page.goto(`${root}?entry=${entry}${reviewer?'&review=1':''}`,{waitUntil:'networkidle'});return{ctx,page,ui:page.frameLocator('#product-frame')}}
async function shot(page,id,title,group,viewport){const file=`${String(screens.length+1).padStart(2,'0')}-${id}-${viewport.width}x${viewport.height}.png`;await page.screenshot({path:new URL(file,out).pathname,fullPage:true});screens.push({id,title,group,viewport:`${viewport.width}x${viewport.height}`,file})}
async function primary(viewport){const{ctx,page,ui}=await open(viewport);await ui.locator('#entry-screen[data-state="welcome"]').waitFor();await shot(page,'welcome','Welcome','Primary path',viewport);await ui.getByRole('button',{name:'Continue with email'}).click();await ui.locator('#email').fill('sam@example.com');await ui.getByRole('button',{name:'Send code'}).click();await ui.locator('#entry-screen[data-state="code"]').waitFor();await ui.locator('#code').fill('123456');await ui.getByRole('button',{name:'Continue'}).click();await ui.locator('#entry-screen[data-state="profile"]').waitFor();await ui.locator('#name').fill('Sam');await ui.getByRole('button',{name:'Continue'}).click();await ui.locator('#entry-screen[data-state="ready"]').waitFor();await shot(page,'ready-sam','Signed in — Sam','Primary path',viewport);await ui.getByRole('button',{name:'Open ChopDot'}).click();await ui.getByText('No groups yet').waitFor();await shot(page,'home-sam','Home — Sam, no inherited wallet/groups','Primary path',viewport);await ctx.close()}
for(const viewport of[{width:393,height:852},{width:430,height:890}])await primary(viewport);
{
 const viewport={width:430,height:890};const{ctx,page,ui}=await open(viewport,'invite');await ui.locator('#entry-screen[data-state="invite"]').waitFor();await ui.getByText('Geneva Weekend').waitFor();await shot(page,'invite-geneva','Geneva Weekend invite','Invite path',viewport);await ui.getByRole('button',{name:'Continue with email'}).click();await ui.locator('#email').fill('dev@example.com');await ui.getByRole('button',{name:'Send code'}).click();await ui.locator('#code').fill('123456');await ui.getByRole('button',{name:'Continue'}).click();await ui.locator('#entry-screen[data-state="ready"]').waitFor();await shot(page,'invite-returning','Returning person — invite preserved','Invite path',viewport);await ctx.close();
}
{
 const viewport={width:430,height:890};const{ctx,page,ui}=await open(viewport,'guest-invite');await ui.getByText('Geneva Weekend').waitFor();await shot(page,'guest-geneva','Guest — coherent Geneva Weekend invite','Guest path',viewport);await ui.getByRole('button',{name:'Review invite as guest'}).click();await ui.getByText('Nothing is joined yet. Your place is created only after you explicitly choose to join.').waitFor();await shot(page,'guest-consent','Guest — explicit-consent boundary','Guest path',viewport);await ctx.close();
}
{
 const viewport={width:430,height:890};const{ctx,page,ui}=await open(viewport,'account',true);await ui.getByRole('button',{name:'Use a wallet'}).click();await ui.getByRole('button',{name:/Everyday/}).click();await ui.locator('#entry-screen[data-state="approval-waiting"]').waitFor();await ui.getByRole('button',{name:'Demo'}).waitFor();await shot(page,'reviewer-wallet','Reviewer-only wallet outcome controls','Reviewer mode only',viewport);await ctx.close();
}
await browser.close();writeFileSync(new URL('manifest.json',out),JSON.stringify({gate:'A',screens},null,2));console.log(`Captured ${screens.length} primary Gate A screens.`);
