import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';import { fileURLToPath } from 'node:url';import { deriveStage4 } from './stage-4-lib.mjs';
const root=join(dirname(fileURLToPath(import.meta.url)),'..'),read=n=>JSON.parse(readFileSync(join(root,'product-schema',n),'utf8'));
const {packet,report}=deriveStage4(read('semantic-core.json'),read('composition-graph.json'),read('frozen-baseline.json'));const out=join(root,'product-schema/generated');mkdirSync(out,{recursive:true});
writeFileSync(join(out,'completeness-report.json'),JSON.stringify(report,null,2)+'\n');writeFileSync(join(out,'gate-b-construction.json'),JSON.stringify(packet,null,2)+'\n');
const q=x=>`\`${x}\``;
const lines=['# Generated Gate B Construction Packet','',`**Derived view — not product authority or implementation authorization. Pre-Gate-B readiness: ${packet.gate.pre_gate_b_readiness}.**`,'','## Construction order','',...packet.construction_order.map((id,i)=>`${i+1}. J${id} — ${packet.journeys.find(j=>j.id===id).name}`),'','## Gate A qualified reuse','',...packet.gate_a_reuse.reusable_contexts.map(x=>`- ${q(x.id)} — ${x.gate_a_coverage}`),'',`Provenance caveat: ${packet.gate_a_reuse.provenance_caveat}`,'','## Gate B composition','',`Contexts: ${packet.composition.contexts.map(q).join(', ')}`,'',`Operations: ${packet.composition.operations.map(q).join(', ')}`,'',`Rendered here: ${packet.composition.views_rendered.map(q).join(', ')}`,'',`Refreshed downstream: ${packet.composition.views_refreshed_downstream.map(x=>q(x.id)+' → Gate '+x.owner_gate).join(', ')}`,'','## Authority blockers','',...(packet.authority_blockers.length?packet.authority_blockers.map(x=>`- **${x.id}** — ${x.statement}`):['- None']),'','## Product decisions required','',...(packet.product_decisions_required.length?packet.product_decisions_required.map(x=>`- **${x.id}** — ${x.statement}`):['- None']),'','## Continuity contracts','',...packet.continuity_contracts.map(x=>`- **${x.id}** — ${x.rule}`),'','## Composition laws','',...packet.composition_laws.map(x=>`- **${x.id}** — ${x.rule}`),'','## Build constraints','',...packet.build_constraints.map(x=>`- **${x.id}** — ${x.rule}`),'','## Journey authority','',...packet.journeys.flatMap(j=>[`### J${j.id} — ${j.name}`,`- Spec: ${q(j.golden.spec.path)}`,`- Golden entrypoint: ${q(j.golden.prototype_entrypoint.path)}`,...(j.golden.artifact_resolution?.resolved_artifacts||[]).map(a=>`- Resolved artifact: ${q(a.path)} (${a.kind}, Git blob ${q(a.git_blob)})`),...(j.golden.artifact_resolution?.missing_artifacts||[]).map(a=>`- **MISSING frozen artifact:** ${q(a)}`),...(j.golden.authority_files||[]).map(a=>`- Authority: ${q(a.path)} (${a.kind})`),'']),'## Schema blockers','',...(packet.schema_blockers.length?packet.schema_blockers.map(x=>`- ${x}`):['- None detected.']),''];
writeFileSync(join(out,'GATE_B_CONSTRUCTION.md'),lines.join('\n')+'\n');
console.log(JSON.stringify({schema_status:report.schema_status,pre_gate_b_readiness:report.pre_gate_b_readiness,authority_blockers:packet.authority_blockers.map(x=>x.id),product_decisions:packet.product_decisions_required.map(x=>x.id),result:'PASS'},null,2));
