export function deriveStage4(core,graph,frozen){
 const byObj=new Map(core.objects.map(x=>[x.id,x])),byOp=new Map(core.operations.map(x=>[x.id,x])),byLaw=new Map(core.laws.map(x=>[x.id,x])),byView=new Map(core.derived_models.map(x=>[x.id,x])),byCtx=new Map(graph.contexts.map(x=>[x.id,x])),byJ=new Map(graph.journey_projections.map(x=>[x.id,x])),byUnit=new Map(graph.composition_units.map(x=>[x.id,x]));
 const gateB=graph.gates.find(x=>x.id==='B'),u=byUnit.get(gateB.composition),gateA=graph.gates.find(x=>x.id==='A'),ambient=(graph.ambient_contexts||[]).map(x=>x.id),routes=frozen.journeys.flatMap(j=>(j.next||[]).map(to=>{const s=byJ.get(j.id),t=byJ.get(to),avail=new Set([...(s.emits_contexts||[]),...ambient]);return{from:j.id,to,matched_contexts:t.entry_contexts_any.filter(x=>avail.has(x))};})),bset=new Set(u.journeys);
 const lawIds=new Set(u.law_refs||[]);for(const cid of u.contexts||[])for(const lid of byCtx.get(cid)?.laws||[])lawIds.add(lid);for(const oid of u.operations||[])for(const lid of byOp.get(oid)?.law_refs||[])lawIds.add(lid);
 const objs=new Set();for(const cid of u.contexts||[])for(const id of byCtx.get(cid)?.objects||[])objs.add(id);for(const oid of u.operations||[]){const o=byOp.get(oid);objs.add(o.owner);for(const id of [...(o.changes||[]),...(o.invalidates||[]),...(o.guards||[])])objs.add(id);}for(const vid of u.views_rendered||[])for(const id of byView.get(vid)?.derived_from||[])objs.add(id);
 const reqs=(graph.construction_requirements||[]).filter(r=>(u.construction_requirement_refs||[]).includes(r.id));
 const integrations=(frozen.accepted_integration.gate_a.inherited_integration_constraints||[]).filter(c=>(u.integration_constraint_refs||[]).includes(c.id));
 const aCtx=new Map((gateA.context_coverage||[]).map(x=>[x.id,x])),aOps=new Map((gateA.operation_coverage||[]).map(x=>[x.id,x]));
 const journeys=u.journeys.map(id=>{const f=frozen.journeys.find(x=>x.id===id),p=byJ.get(id);return{id,name:f.name,version:f.version,golden:{spec:f.spec,prototype_entrypoint:f.prototype,artifact_resolution:f.artifact_resolution||null,qa:f.qa,authority_files:f.authority_files},requirements:reqs.filter(r=>r.journey===id),wiring:{entry_contexts_any:p.entry_contexts_any,ambient_contexts_required:p.ambient_contexts_required,effect_contexts_required:p.effect_contexts_required,owns_operations:p.owns_operations,renders_views:p.renders_views,emits_contexts:p.emits_contexts}};});
 const authorityBlockers=(frozen.authority_blockers||[]).filter(x=>!x.journey||bset.has(x.journey)),decisions=(core.known_gaps||[]).filter(x=>x.classification==='requires_product_decision'&&(x.journeys||[]).some(j=>bset.has(j)));
 const packet={schema_version:3,generated_view:'gate-b-construction',authority:'DERIVED_ONLY',gate:{id:'B',name:gateB.name,status:gateB.status,goal:gateB.goal,implementation_authorized:false,pre_gate_b_readiness:authorityBlockers.length||decisions.length?'BLOCKED':'READY_FOR_HUMAN_AUTHORIZATION'},construction_order:u.journeys,journeys,composition:{id:u.id,contexts:u.contexts,operations:u.operations,views_rendered:u.views_rendered,views_refreshed_downstream:u.views_refreshed_downstream,continuity_refs:u.continuity_refs,law_refs:[...lawIds],build_constraint_refs:u.build_constraint_refs,construction_requirement_refs:u.construction_requirement_refs,integration_constraint_refs:u.integration_constraint_refs},construction_requirements:reqs,inherited_integration_constraints:integrations,semantic_objects:[...objs].sort().map(id=>byObj.get(id)).filter(Boolean),operation_contracts:u.operations.map(id=>byOp.get(id)),laws:[...lawIds].map(id=>byLaw.get(id)).filter(Boolean),composition_laws:(graph.shared_composition_laws||[]).filter(x=>lawIds.has(x.id)),continuity_contracts:(graph.continuity_contracts||[]).filter(x=>u.continuity_refs.includes(x.id)),build_constraints:(graph.build_constraints||[]).filter(x=>u.build_constraint_refs.includes(x.id)),contexts:u.contexts.map(id=>byCtx.get(id)),handoffs:{internal:routes.filter(x=>bset.has(x.from)&&bset.has(x.to)),inbound:routes.filter(x=>!bset.has(x.from)&&bset.has(x.to)),downstream:routes.filter(x=>bset.has(x.from)&&!bset.has(x.to))},gate_a_reuse:{accepted_source:gateA.accepted_source,reusable_contexts:(u.contexts||[]).filter(id=>aCtx.has(id)).map(id=>aCtx.get(id)),new_gate_b_contexts:(u.contexts||[]).filter(id=>!aCtx.has(id)),operation_delta:u.operations.map(id=>aOps.has(id)?{id,status:'expand_bounded_gate_a_capability',gate_a_coverage:aOps.get(id).coverage}:{id,status:'new_to_integrated_gate_b'}),provenance_caveat:gateA.provenance_caveat,rule:gateA.rule},authority_blockers:authorityBlockers,product_decisions_required:decisions,schema_blockers:[]};
 const uses=new Map(core.objects.map(o=>[o.id,0]));for(const c of graph.contexts)for(const id of c.objects||[])uses.set(id,(uses.get(id)||0)+1);for(const o of core.operations)for(const id of [o.owner,...(o.changes||[]),...(o.invalidates||[]),...(o.guards||[])])uses.set(id,(uses.get(id)||0)+1);for(const v of core.derived_models)for(const id of v.derived_from||[])uses.set(id,(uses.get(id)||0)+1);for(const l of core.laws)for(const id of l.applies_to||[])uses.set(id,(uses.get(id)||0)+1);
 const orphan=[...uses].filter(([,n])=>n===0).map(([id])=>id),rendered=new Set(graph.journey_projections.flatMap(j=>j.renders_views)),unrendered=core.derived_models.map(x=>x.id).filter(id=>!rendered.has(id)),owned=new Map(core.operations.map(o=>[o.id,[]]));for(const j of graph.journey_projections)for(const id of j.owns_operations||[])owned.get(id)?.push(j.id);const contractOnly=new Set(graph.contract_only_operations||[]),coordinated=new Set((graph.coordinated_operations||[]).map(x=>x.id)),unowned=[...owned].filter(([id,js])=>js.length===0&&!contractOnly.has(id)&&!coordinated.has(id)).map(([id])=>id),dup=[...owned].filter(([,js])=>js.length>1).map(([id,js])=>({id,owners:js}));
 const report={schema_version:3,generated_view:'schema-hardening-completeness',schema_status:orphan.length||unrendered.length||unowned.length||dup.length?'FAIL':'PASS',pre_gate_b_readiness:packet.gate.pre_gate_b_readiness,audits:{objects:{total:core.objects.length,orphans:orphan},views:{total:core.derived_models.length,unrendered},operations:{total:core.operations.length,unowned,duplicate_owners:dup,contract_only:[...contractOnly],coordinated:[...coordinated]},routes:{total:routes.length,covered:routes.length},composition:{units:graph.composition_units.length,gate_b:u.id},construction_requirements:{total:reqs.length},integration_constraints:{total:integrations.length}},authority_blockers:authorityBlockers,product_decisions_required:decisions};return{packet,report};
}
