export function deriveStage4(core, graph, frozen) {
  const byObj=new Map(core.objects.map(x=>[x.id,x])), byOp=new Map(core.operations.map(x=>[x.id,x])), byLaw=new Map(core.laws.map(x=>[x.id,x])), byView=new Map(core.derived_models.map(x=>[x.id,x])), byCtx=new Map(graph.contexts.map(x=>[x.id,x])), byJ=new Map(graph.journey_projections.map(x=>[x.id,x])), byUnit=new Map(graph.composition_units.map(x=>[x.id,x]));
  const gateB=graph.gates.find(x=>x.id==='B'), unit=byUnit.get(gateB.composition), gateA=graph.gates.find(x=>x.id==='A');
  const routes=frozen.journeys.flatMap(j=>(j.next||[]).map(to=>{const s=byJ.get(j.id),t=byJ.get(to),avail=new Set([...(s.emits_contexts||[]),...(graph.ambient_contexts||[]).map(x=>x.id)]),matched=t.entry_contexts_any.filter(x=>avail.has(x));return{from:j.id,to,matched_contexts:matched};}));
  const bset=new Set(unit.journeys);
  const handoffs={internal:routes.filter(x=>bset.has(x.from)&&bset.has(x.to)),inbound:routes.filter(x=>!bset.has(x.from)&&bset.has(x.to)),downstream:routes.filter(x=>bset.has(x.from)&&!bset.has(x.to))};
  const lawIds=new Set(unit.law_refs||[]);
  for(const cid of unit.contexts||[])for(const lid of byCtx.get(cid)?.laws||[])lawIds.add(lid);
  for(const oid of unit.operations||[])for(const lid of byOp.get(oid)?.law_refs||[])lawIds.add(lid);
  const semanticObjects=new Set();
  for(const cid of unit.contexts||[])for(const id of byCtx.get(cid)?.objects||[])semanticObjects.add(id);
  for(const oid of unit.operations||[]){const o=byOp.get(oid);semanticObjects.add(o.owner);for(const id of [...(o.changes||[]),...(o.invalidates||[]),...(o.emits||[]),...(o.guards||[])])semanticObjects.add(id);}
  for(const vid of unit.views_rendered||[])for(const id of byView.get(vid)?.derived_from||[])semanticObjects.add(id);
  const gateAByContext=new Map((gateA.context_coverage||[]).map(x=>[x.id,x]));
  const contextReuse=(unit.contexts||[]).filter(id=>gateAByContext.has(id)).map(id=>gateAByContext.get(id));
  const newContexts=(unit.contexts||[]).filter(id=>!gateAByContext.has(id));
  const opCoverage=new Map((gateA.operation_coverage||[]).map(x=>[x.id,x]));
  const operationDelta=(unit.operations||[]).map(id=>opCoverage.has(id)?{id,status:'expand_bounded_gate_a_capability',gate_a_coverage:opCoverage.get(id).coverage}:{id,status:'new_to_integrated_gate_b'});
  const journeyPackets=unit.journeys.map(id=>{const f=frozen.journeys.find(x=>x.id===id),p=byJ.get(id);return{id,name:f.name,version:f.version,golden:{spec:f.spec,prototype_entrypoint:f.prototype,artifact_resolution:f.artifact_resolution||null,qa:f.qa,contracts:f.contracts,authority_files:f.authority_files},registry:{entry:f.entry,exit:f.exit,next:f.next},wiring:{entry_contexts_any:p.entry_contexts_any,ambient_contexts_required:p.ambient_contexts_required,effect_contexts_required:p.effect_contexts_required,owns_operations:p.owns_operations,participates_operations:p.participates_operations,renders_views:p.renders_views,emits_contexts:p.emits_contexts}};});
  const authorityBlockers=(frozen.authority_blockers||[]).filter(x=>!x.journey||bset.has(x.journey));
  const productDecisions=(core.known_gaps||[]).filter(x=>x.classification==='requires_product_decision'&&(x.journeys||[]).some(j=>bset.has(j)));
  const packet={schema_version:2,generated_view:'gate-b-construction',authority:'DERIVED_ONLY',gate:{id:'B',name:gateB.name,status:gateB.status,goal:gateB.goal,implementation_authorized:false,pre_gate_b_readiness:authorityBlockers.length||productDecisions.length?'BLOCKED':'READY_FOR_HUMAN_AUTHORIZATION'},generated_from:{product_authority_commit:frozen.authority.product.commit,stage_1_schema:'frozen-baseline.json',stage_2_schema:'semantic-core.json',stage_3_schema:'composition-graph.json'},construction_order:unit.journeys,journeys:journeyPackets,composition:{id:unit.id,contexts:unit.contexts,operations:unit.operations,views_rendered:unit.views_rendered,views_refreshed_downstream:unit.views_refreshed_downstream,continuity_refs:unit.continuity_refs,law_refs:[...lawIds],build_constraint_refs:unit.build_constraint_refs},semantic_objects:[...semanticObjects].sort().map(id=>byObj.get(id)).filter(Boolean),operation_contracts:unit.operations.map(id=>byOp.get(id)),laws:[...lawIds].map(id=>byLaw.get(id)).filter(Boolean),composition_laws:(graph.shared_composition_laws||[]).filter(x=>lawIds.has(x.id)),continuity_contracts:(graph.continuity_contracts||[]).filter(x=>(unit.continuity_refs||[]).includes(x.id)),build_constraints:(graph.build_constraints||[]).filter(x=>(unit.build_constraint_refs||[]).includes(x.id)),contexts:unit.contexts.map(id=>byCtx.get(id)),handoffs,gate_a_reuse:{accepted_source:gateA.accepted_source,reusable_contexts:contextReuse,new_gate_b_contexts:newContexts,operation_delta:operationDelta,frozen_scope_exclusions:gateA.scope_exclusions,provenance_caveat:gateA.provenance_caveat,rule:gateA.rule},authority_blockers:authorityBlockers,product_decisions_required:productDecisions,schema_blockers:[]};
  const objectUses=new Map(core.objects.map(o=>[o.id,0]));for(const c of graph.contexts)for(const id of c.objects||[])objectUses.set(id,(objectUses.get(id)||0)+1);for(const op of core.operations)for(const id of [op.owner,...(op.changes||[]),...(op.invalidates||[]),...(op.emits||[]),...(op.guards||[])])objectUses.set(id,(objectUses.get(id)||0)+1);for(const v of core.derived_models)for(const id of v.derived_from||[])objectUses.set(id,(objectUses.get(id)||0)+1);for(const l of core.laws)for(const id of l.applies_to||[])objectUses.set(id,(objectUses.get(id)||0)+1);
  const orphan=[...objectUses].filter(([,n])=>n===0).map(([id])=>id);
  const rendered=new Set(graph.journey_projections.flatMap(j=>j.renders_views));const unrendered=core.derived_models.map(x=>x.id).filter(id=>!rendered.has(id));
  const owned=new Map(core.operations.map(o=>[o.id,[]]));for(const j of graph.journey_projections)for(const id of j.owns_operations||[])owned.get(id)?.push(j.id);
  const contractOnly=new Set(graph.contract_only_operations||[]), coordinated=new Set((graph.coordinated_operations||[]).map(x=>x.id));const unowned=[...owned].filter(([id,js])=>js.length===0&&!contractOnly.has(id)&&!coordinated.has(id)).map(([id])=>id),duplicate=[...owned].filter(([,js])=>js.length>1).map(([id,js])=>({id,owners:js}));
  const report={schema_version:2,generated_view:'schema-hardening-completeness',schema_status:orphan.length||unrendered.length||unowned.length||duplicate.length?'FAIL':'PASS',pre_gate_b_readiness:packet.gate.pre_gate_b_readiness,audits:{objects:{total:core.objects.length,orphans:orphan},views:{total:core.derived_models.length,unrendered},operations:{total:core.operations.length,unowned,duplicate_owners:duplicate,contract_only:[...contractOnly],coordinated:[...coordinated]},routes:{total:routes.length,covered:routes.length},composition:{units:graph.composition_units.length,gate_b:unit.id}},authority_blockers:authorityBlockers,product_decisions_required:productDecisions};
  return {packet,report};
}
