#!/usr/bin/env node
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { chromium } from 'playwright';

const here=path.dirname(fileURLToPath(import.meta.url));
const journeyRoot=path.resolve(here,'..');
const repoRoot=path.resolve(journeyRoot,'../../../..');
const candidatePath=path.join(journeyRoot,'v1-candidate.html');
const packetPath=path.join(here,'current-work-packet.md');
const evidenceRoot=path.resolve(repoRoot,'artifacts/j27-v1-review');
const shotRoot=path.join(evidenceRoot,'screenshots');
await mkdir(shotRoot,{recursive:true});
const html=await readFile(candidatePath,'utf8'),packet=await readFile(packetPath,'utf8');
const hash=text=>createHash('sha256').update(text).digest('hex');
const git=(...args)=>execFileSync('git',args,{cwd:repoRoot,encoding:'utf8'}).trim();
const head=git('rev-parse','HEAD'),tree=git('rev-parse','HEAD^{tree}'),branch=process.env.GITHUB_REF_NAME||git('rev-parse','--abbrev-ref','HEAD');
const candidateSha256=hash(html),packetSha256=hash(packet);
const viewports=[{width:393,height:852,name:'393x852'},{width:430,height:890,name:'430x890'}];
const errors=[],pageErrors=[],consoleErrors=[],external=[],screenshots=[],layouts=[],interactions=[],reachability=[],modelChecks=[],sequentialChecks=[];
const check=(label,pass,actual='')=>{modelChecks.push({label,pass,actual});if(!pass)errors.push(`${label}${actual?`: ${actual}`:''}`)};
const interaction=(label,pass,actual='')=>{interactions.push({label,pass,actual});if(!pass)errors.push(`${label}${actual?`: ${actual}`:''}`);return pass};
const sequence=(label,pass,actual='')=>{sequentialChecks.push({label,pass,actual});return interaction(`sequential: ${label}`,pass,actual)};
for(const bad of ['<script src=','type="password"','private key fixture','seed phrase fixture'])if(html.includes(bad))errors.push(`prohibited static marker: ${bad}`);
for(const req of ['Journey 27','v1.1','window.J27_DEFS','Prototype fixture only','account-entry','deletion-type-confirm','notification-system-boundary','app-header','tabbar','add-tab','window.J27_TEST_RESET','window.J27_TEST_TRUTH','sessionStatus','accountStatus'])if(!html.includes(req))errors.push(`missing static marker: ${req}`);
check('packet identifies Journey 27',packet.includes('Journey: **27 — Account & Preferences V1**'));
check('packet binds activation head',packet.includes('19a282b8c3346ca62e77c2db3780163a75f58046'));
check('packet requires caller reachability',packet.toLowerCase().includes('caller reachability'));

const browser=await chromium.launch({headless:true});
const file=pathToFileURL(candidatePath).href;
const stateUrl=id=>{const u=new URL(file);u.hash=id;return u.href};
const renderedState=p=>p.evaluate(()=>document.getElementById('content')?.dataset?.testState||'');
const waitRendered=(p,id)=>p.waitForFunction(target=>location.hash===`#${target}`&&document.getElementById('content')?.dataset?.testState===target,id);
const truth=p=>p.evaluate(()=>window.J27_TEST_TRUTH());
const text=p=>p.locator('#content').innerText();
const freshGoto=async(p,id)=>{await p.goto(stateUrl('account-entry'),{waitUntil:'load'});await p.evaluate(target=>{window.J27_TEST_RESET();location.hash=target},id);await waitRendered(p,id)};
async function clickTo(p,to){const from=await renderedState(p),loc=p.locator(`#content [data-to="${to}"]`).first();if(await loc.count()!==1)return interaction(`click ${from}->${to}`,false,'control missing');await loc.click();await waitRendered(p,to);const actual=await renderedState(p);return interaction(`click ${from}->${to}`,actual===to,actual)}
async function clickPath(p,targets){for(const to of targets)if(!await clickTo(p,to))return false;return true}

const probe=await browser.newPage({viewport:{width:393,height:852}});await freshGoto(probe,'account-entry');
const defs=await probe.evaluate(()=>window.J27_DEFS),roots=await probe.evaluate(()=>window.J27_ROOTS),boundaryIds=await probe.evaluate(()=>window.J27_BOUNDARIES);await probe.close();
const ids=Object.keys(defs),boundarySet=new Set(boundaryIds),stateIds=ids.filter(id=>!boundarySet.has(id));
check('registered material state count',stateIds.length===62,String(stateIds.length));check('named boundary count',boundaryIds.length===5,String(boundaryIds.length));check('root set exact',JSON.stringify(roots)===JSON.stringify(['account-entry']),JSON.stringify(roots));check('all codes unique',new Set(ids.map(id=>defs[id].code)).size===ids.length);
for(const id of stateIds)check(`${id} has J27 state code`,/^J27-S\d+$/.test(defs[id].code),defs[id].code);for(const id of boundaryIds)check(`${id} has J27 boundary code`,/^J27-B\d+$/.test(defs[id].code),defs[id].code);
for(const id of ['profile-saving','notifications-saving','appearance-saving','signing-out','deletion-requesting'])check(`${id} pending`,defs[id]?.status==='progress',defs[id]?.status);
for(const id of ['profile-unknown','notifications-unknown','appearance-unknown','signout-unknown','deletion-unknown'])check(`${id} unknown warning`,defs[id]?.status==='warn',defs[id]?.status);
for(const id of ['profile-saved','notifications-saved','appearance-saved','signed-out','deleted'])check(`${id} verified success`,defs[id]?.status==='success',defs[id]?.status);
for(const id of ['profile-cancelled','notifications-cancelled','appearance-cancelled','signout-cancelled','deletion-cancelled'])check(`${id} neutral cancel`,defs[id]?.status==='neutral',defs[id]?.status);
const edges={};for(const id of ids){edges[id]=[];for(const a of defs[id].actions||[])if(a?.to)edges[id].push({from:id,to:a.to,label:a.label})}edges['deletion-type-confirm'].push({from:'deletion-type-confirm',to:'deletion-final-review',special:'exact'},{from:'deletion-type-confirm',to:'deletion-mismatch',special:'mismatch'});for(const id of ids)for(const e of edges[id])check(`valid transition ${id}->${e.to}`,Boolean(defs[e.to]),e.to);
function shortestPath(target){const q=roots.map(start=>({id:start,start,steps:[]})),seen=new Set();while(q.length){const cur=q.shift();if(seen.has(cur.id))continue;seen.add(cur.id);if(cur.id===target)return cur;for(const e of edges[cur.id]||[])q.push({id:e.to,start:cur.start,steps:[...cur.steps,e]})}return null}
const pathProof={};for(const id of ids){pathProof[id]=shortestPath(id);check(`truthful caller path exists for ${id}`,Boolean(pathProof[id]),'no path')}
async function clickTransition(p,e){const current=await renderedState(p);if(current!==e.from){errors.push(`caller ${e.from}->${e.to}: current ${current}`);return false}if(e.special){const currentTruth=await truth(p);await p.locator('[data-test-delete-input]').fill(e.special==='exact'?currentTruth.displayName:'WRONG');await p.locator('#delete-submit').click()}else{const loc=p.locator(`#content [data-to="${e.to}"]`).first();if(await loc.count()!==1){errors.push(`caller ${e.from}->${e.to}: control missing`);return false}await loc.click()}await waitRendered(p,e.to);const actual=await renderedState(p),pass=actual===e.to;interactions.push({label:`caller ${e.from}->${e.to}`,expected:e.to,actual,pass});if(!pass)errors.push(`caller ${e.from}->${e.to}: ended ${actual}`);return pass}
async function reachState(p,id){const proof=pathProof[id];await freshGoto(p,proof.start);for(const e of proof.steps)if(!await clickTransition(p,e))return false;return(await renderedState(p))===id}
const callerPage=await browser.newPage({viewport:{width:393,height:852}});for(const id of ids){const proof=pathProof[id],ok=await reachState(callerPage,id);reachability.push({state:id,start:proof.start,steps:proof.steps.map(e=>`${e.from}->${e.to}${e.special?`(${e.special})`:''}`),pass:ok})}await callerPage.close();check('caller reachability complete',reachability.filter(r=>r.pass).length===ids.length,`${reachability.filter(r=>r.pass).length}/${ids.length}`);

for(const vp of viewports){const p=await browser.newPage({viewport:{width:vp.width,height:vp.height}});p.on('pageerror',e=>pageErrors.push({viewport:vp.name,error:String(e)}));p.on('console',m=>{if(m.type()==='error')consoleErrors.push({viewport:vp.name,text:m.text()})});p.on('request',r=>{const u=r.url();if(!u.startsWith('file:')&&!u.startsWith('data:')&&!u.startsWith('about:'))external.push({viewport:vp.name,url:u})});for(const id of ids){await reachState(p,id);const code=await p.locator('#content').getAttribute('data-state-code');if(code!==defs[id].code)errors.push(`${vp.name}/${id}: code ${code} expected ${defs[id].code}`);const metrics=await p.evaluate(()=>{const c=document.getElementById('content');return{doc:document.documentElement.scrollWidth,iw:innerWidth,cw:c.clientWidth,sw:c.scrollWidth,ch:c.clientHeight,sh:c.scrollHeight,actions:[...c.querySelectorAll('.btn,button')].map(el=>{const r=el.getBoundingClientRect();return{t:el.textContent.trim(),h:r.height,w:r.width}})}});if(metrics.doc>metrics.iw+1||metrics.sw>metrics.cw+1)errors.push(`${vp.name}/${id}: horizontal overflow`);for(const a of metrics.actions)if(a.h<43)errors.push(`${vp.name}/${id}: action too short ${a.t}:${a.h}`);layouts.push({viewport:vp.name,state:id,...metrics});let shot=path.join(shotRoot,`${id}-${vp.name}.png`);await p.screenshot({path:shot,fullPage:false});screenshots.push({viewport:vp.name,state:id,position:'top',path:path.relative(evidenceRoot,shot)});if(metrics.sh>metrics.ch+4){await p.locator('#content').evaluate(el=>{el.scrollTop=el.scrollHeight});shot=path.join(shotRoot,`${id}-bottom-${vp.name}.png`);await p.screenshot({path:shot,fullPage:false});screenshots.push({viewport:vp.name,state:id,position:'bottom',path:path.relative(evidenceRoot,shot)})}}
await reachState(p,'notifications-saved');for(const t of ['Push preference','On','Effective push','Permission needed'])if(!(await text(p)).includes(t))errors.push(`${vp.name}/notifications-saved missing ${t}`);
await reachState(p,'signed-out');for(const t of ['Account','Not deleted','Groups / money / history','Unchanged'])if(!(await text(p)).includes(t))errors.push(`${vp.name}/signed-out missing ${t}`);
await reachState(p,'deleted');for(const t of ['Shared group/expense history','Preserved','Not claimed erased'])if(!(await text(p)).includes(t))errors.push(`${vp.name}/deleted missing ${t}`);
await reachState(p,'deletion-type-confirm');await p.locator('[data-test-delete-input]').fill('WRONG');await p.locator('#delete-submit').click();await waitRendered(p,'deletion-mismatch');await reachState(p,'deletion-type-confirm');const exact=(await truth(p)).displayName;await p.locator('[data-test-delete-input]').fill(exact);await p.locator('#delete-submit').click();await waitRendered(p,'deletion-final-review');await p.close()}

const seq=await browser.newPage({viewport:{width:393,height:852}});seq.on('pageerror',e=>pageErrors.push({viewport:'sequential',error:String(e)}));seq.on('console',m=>{if(m.type()==='error')consoleErrors.push({viewport:'sequential',text:m.text()})});seq.on('request',r=>{const u=r.url();if(!u.startsWith('file:')&&!u.startsWith('data:')&&!u.startsWith('about:'))external.push({viewport:'sequential',url:u})});
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','profile-overview','profile-edit','profile-review','profile-saving','profile-saved']);sequence('profile verified truth is Dev Peña',(await truth(seq)).displayName==='Dev Peña',JSON.stringify(await truth(seq)));await clickTo(seq,'profile-overview');sequence('profile overview keeps Dev Peña',(await text(seq)).includes('Dev Peña'),await text(seq));await clickTo(seq,'account-overview');sequence('account overview keeps Dev Peña',(await text(seq)).includes('Dev Peña'),await text(seq));await seq.reload({waitUntil:'load'});await waitRendered(seq,'account-overview');sequence('profile truth survives reload',(await truth(seq)).displayName==='Dev Peña'&&(await text(seq)).includes('Dev Peña'),JSON.stringify(await truth(seq)));
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','notifications-overview','notifications-edit','notifications-review','notifications-saving','notifications-saved','notifications-permission-needed','notification-system-boundary','notifications-overview']);let body=await text(seq),t=await truth(seq);sequence('permission granted return refreshes truth',t.osPermission==='granted'&&t.reminders===false&&t.pushPreference===true&&body.includes('Granted')&&body.includes('Effective push')&&body.includes('On'),`${JSON.stringify(t)}\n${body}`);await seq.reload({waitUntil:'load'});await waitRendered(seq,'notifications-overview');body=await text(seq);sequence('granted notification truth survives reload',(await truth(seq)).osPermission==='granted'&&body.includes('Granted')&&body.includes('Effective push'),body);
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','notifications-overview','notifications-edit','notifications-review','notifications-saving','notifications-saved','notifications-permission-needed','notification-system-boundary','notifications-permission-denied']);t=await truth(seq);body=await text(seq);sequence('permission denied return refreshes truth',t.osPermission==='denied'&&t.pushPreference===true&&body.includes('Denied')&&body.includes('Effective push')&&body.includes('Off'),`${JSON.stringify(t)}\n${body}`);await clickTo(seq,'notifications-overview');await seq.reload({waitUntil:'load'});await waitRendered(seq,'notifications-overview');body=await text(seq);sequence('denied notification truth survives overview and reload',(await truth(seq)).osPermission==='denied'&&body.includes('Denied')&&body.includes('Push preference')&&body.includes('On'),body);
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','appearance-overview','appearance-preview','appearance-saving','appearance-saved','appearance-overview']);sequence('appearance overview keeps Dark',(await truth(seq)).appearance==='Dark'&&(await text(seq)).includes('Dark'),JSON.stringify(await truth(seq)));await clickTo(seq,'account-overview');await seq.reload({waitUntil:'load'});await waitRendered(seq,'account-overview');sequence('appearance truth survives account navigation and reload',(await truth(seq)).appearance==='Dark'&&(await text(seq)).includes('Dark'),await text(seq));
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','deletion-entry','deletion-review','deletion-type-confirm']);body=await text(seq);sequence('baseline deletion confirmation names current display name',body.includes('Type Devinson to continue')&&body.includes('Exact text required')&&body.includes('Devinson'),body);await seq.locator('[data-test-delete-input]').fill('Devinson');await seq.locator('#delete-submit').click();await waitRendered(seq,'deletion-final-review');sequence('baseline current display name passes confirmation',await renderedState(seq)==='deletion-final-review',await renderedState(seq));
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','profile-overview','profile-edit','profile-review','profile-saving','profile-saved','profile-overview','account-overview','deletion-entry','deletion-review','deletion-type-confirm']);body=await text(seq);sequence('renamed deletion confirmation names Dev Peña',body.includes('Type Dev Peña to continue')&&body.includes('Exact text required')&&body.includes('Dev Peña'),body);await seq.locator('[data-test-delete-input]').fill('Devinson');await seq.locator('#delete-submit').click();await waitRendered(seq,'deletion-mismatch');sequence('stale old display name is rejected after rename',await renderedState(seq)==='deletion-mismatch',await renderedState(seq));await clickTo(seq,'deletion-type-confirm');await seq.locator('[data-test-delete-input]').fill('Dev Peña');await seq.locator('#delete-submit').click();await waitRendered(seq,'deletion-final-review');sequence('exact renamed display name passes confirmation',await renderedState(seq)==='deletion-final-review',await renderedState(seq));
async function terminalAssert(label,kind){await seq.waitForTimeout(60);const state=await renderedState(seq),snapshot=await truth(seq),copy=await text(seq);const truthPass=kind==='deleted'?snapshot.accountStatus==='deleted'&&snapshot.sessionStatus==='signed-out':snapshot.accountStatus==='active'&&snapshot.sessionStatus==='signed-out';return sequence(label,truthPass&&['signed-out','deleted','you-home-boundary'].includes(state)&&!copy.includes('Open account settings')&&!copy.includes('This device active'),`${state} ${JSON.stringify(snapshot)}\n${copy}`)}
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','security-overview','signout-review','signing-out','signed-out']);await terminalAssert('sign-out establishes terminal session truth','signed-out');await seq.goBack().catch(()=>null);await terminalAssert('signed-out truth survives Back','signed-out');await seq.goForward().catch(()=>null);await terminalAssert('signed-out truth survives Forward','signed-out');await seq.reload({waitUntil:'load'});await terminalAssert('signed-out truth survives reload','signed-out');sequence('signed-out owner boundary has no account-entry resurrection control',await seq.locator('#content [data-to="account-entry"]').count()===0,String(await seq.locator('#content [data-to="account-entry"]').count()));
await freshGoto(seq,'account-entry');await clickPath(seq,['account-loading','account-overview','deletion-entry','deletion-review','deletion-type-confirm']);await seq.locator('[data-test-delete-input]').fill('Devinson');await seq.locator('#delete-submit').click();await waitRendered(seq,'deletion-final-review');await clickPath(seq,['deletion-requesting','deleted']);await terminalAssert('deletion establishes terminal account truth','deleted');await seq.goBack().catch(()=>null);await terminalAssert('deleted truth survives Back','deleted');await seq.goForward().catch(()=>null);await terminalAssert('deleted truth survives Forward','deleted');await seq.reload({waitUntil:'load'});await terminalAssert('deleted truth survives reload','deleted');sequence('deleted owner boundary has no account-entry resurrection control',await seq.locator('#content [data-to="account-entry"]').count()===0,String(await seq.locator('#content [data-to="account-entry"]').count()));await seq.close();

await browser.close();if(pageErrors.length)errors.push(`page errors: ${pageErrors.length}`);if(consoleErrors.length)errors.push(`console errors: ${consoleErrors.length}`);if(external.length)errors.push(`external runtime requests: ${external.length}`);
const summary={journey:27,branch,head,tree,candidateSha256,packetSha256,stateCount:stateIds.length,boundaryCount:boundaryIds.length,viewports,screenshotCount:screenshots.length,layoutCount:layouts.length,interactionChecks:interactions.length,sequentialPersistenceChecks:`${sequentialChecks.filter(c=>c.pass).length}/${sequentialChecks.length}`,callerReachability:`${reachability.filter(r=>r.pass).length}/${ids.length}`,modelContractChecks:`${modelChecks.filter(c=>c.pass).length}/${modelChecks.length}`,pageErrors:pageErrors.length,consoleErrors:consoleErrors.length,externalRequests:external.length,mechanicalFailures:errors.length};
await writeFile(path.join(evidenceRoot,'summary.json'),JSON.stringify(summary,null,2));await writeFile(path.join(evidenceRoot,'browser-qa.json'),JSON.stringify({summary,layouts,interactions,sequentialChecks,pageErrors,consoleErrors,external,screenshots},null,2));await writeFile(path.join(evidenceRoot,'caller-reachability.json'),JSON.stringify({summary:summary.callerReachability,paths:reachability},null,2));await writeFile(path.join(evidenceRoot,'model-contract.json'),JSON.stringify({summary:summary.modelContractChecks,checks:modelChecks},null,2));await writeFile(path.join(evidenceRoot,'SEQUENTIAL_PERSISTENCE_QA.json'),JSON.stringify({summary:summary.sequentialPersistenceChecks,checks:sequentialChecks},null,2));await writeFile(path.join(evidenceRoot,'VISUAL_QA.md'),`# Journey 27 V1 visual QA\n\n- Exact head: \`${head}\`\n- Candidate SHA-256: \`${candidateSha256}\`\n- Registered states: ${stateIds.length}\n- Boundaries: ${boundaryIds.length}\n- Screenshots generated: ${screenshots.length}\n- Canonical viewports: 393×852 and 430×890\n- Sequential persistence checks: ${summary.sequentialPersistenceChecks}\n- Horizontal overflow failures: ${errors.filter(e=>e.includes('horizontal overflow')).length}\n- Page errors: ${pageErrors.length}\n- Console errors: ${consoleErrors.length}\n- External runtime requests: ${external.length}\n\nRender evidence is produced through truthful caller paths so persisted fixture truth matches each captured state. Direct independent visual review follows the active risk-based review doctrine.\n`);console.log(JSON.stringify(summary,null,2));if(errors.length){console.error('\nFAILURES\n'+errors.map(e=>`- ${e}`).join('\n'));process.exit(1)}
