import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const run=(file,args=[])=>execFileSync(process.execPath,[path.join(root,'tools',file),...args],{cwd:root,stdio:'inherit'});
run('apply-j13-golden-freeze.mjs',['--preflight']);
run('apply-j09-golden-freeze.mjs',['--preflight']);
execFileSync('npm',['run','gate:historical'],{cwd:root,stdio:'inherit'});
run('build-j13-candidate.mjs');
run('apply-j09-golden-freeze.mjs');run('build-journey-map.mjs');run('validate-workbench.mjs');run('apply-j09-golden-freeze.mjs',['--check']);
run('validate-j13-request.mjs');
if(fs.existsSync(path.join(root,'tools/build-j14-candidate.mjs')))run('build-j14-candidate.mjs');
run('apply-j13-golden-freeze.mjs');run('build-journey-map.mjs');run('validate-workbench.mjs');run('apply-j13-golden-freeze.mjs',['--check']);
if(fs.existsSync(path.join(root,'tools/validate-j14-receive.mjs')))run('validate-j14-receive.mjs');
