import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const M=require('./model.cjs');
const journeyDir=path.resolve(import.meta.dirname,'..');
const workbench=path.resolve(journeyDir,'../..');
const reviewDir=path.join(journeyDir,'review-v1');
fs.mkdirSync(reviewDir,{recursive:true});
const read=p=>fs.readFileSync(p,'utf8');
const inherited=read(path.join(workbench,'journeys/19-insights/source/inherited.css'));
const shell=read(path.join(workbench,'journeys/19-insights/source/shell.css'));
const methods=M.clone(M.DEMO_METHODS);
const bank=methods.find(m=>m.kind==='bank'),twint=methods.find(m=>m.kind==='twint'),paypal=methods.find(m=>m.kind==='paypal'),dot=methods.find(m=>m.kind==='crypto');

const iconPaths={
 back:'<path d="M15 18l-6-6 6-6"/>',chev:'<path d="M9 18l6-6-6-6"/>',plus:'<path d="M12 5v14M5 12h14"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/>',users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/>',activity:'<path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v6h6"/><path d="M12 7v5l4 2"/>',user:'<path d="M19 21a7 7 0 0 0-14 0"/><circle cx="12" cy="7" r="4"/>',bank:'<path d="M3 10h18M5 10v8M9 10v8M15 10v8M19 10v8M3 18h18M12 3l9 5H3z"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/>',crypto:'<path d="M4 7h16v10H4z"/><path d="M8 11h8M12 7V4M12 20v-3"/>',check:'<path d="M20 6L9 17l-5-5"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>',star:'<path d="M12 3l2.8 5.7 6.2.9-4.5 4.4 1.1 6.2L12 17.3 6.4 20.2 7.5 14 3 9.6l6.2-.9z"/>',edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4z"/>',trash:'<path d="M3 6h18M8 6V4h8v2M6 6l1 15h10l1-15M10 10v7M14 10v7"/>',refresh:'<path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/>',alert:'<circle cx="12" cy="12" r="9"/><path d="M12 8v5M12 16h.01"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',link:'<path d="M10 13a5 5 0 0 0 7.5.5l2-2a5 5 0 0 0-7-7l-1.1 1.1"/><path d="M14 11a5 5 0 0 0-7.5-.5l-2 2a5 5 0 0 0 7 7l1.1-1.1"/>',wifi:'<path d="M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0M12 19h.01"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 8h.01"/>',copy:'<rect x="9" y="9" width="10" height="10" rx="2"/><path d="M15 9V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h4"/>'
};
const svg=(name,cls='')=>`<svg ${cls?`class="${cls}" `:''}viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||''}</svg>`;
const header=(title,sub='Payment methods',back='#you-preview')=>`<header class="detail-header"><a class="icon-btn" href="${back}" aria-label="Back">${svg('back')}</a><div class="header-title"><b>${title}</b><span>${sub}</span></div><a class="demo-btn" href="#demo">Demo</a></header>`;
const tabs=`<footer class="app-footer"><nav class="tabbar" aria-label="Main navigation"><a class="tab" href="#pots-preview">${svg('grid','nav-icon')}<span>Pots</span></a><a class="tab" href="#people-preview">${svg('users','nav-icon')}<span>People</span></a><a class="add-tab" aria-label="Add" href="#add-preview">${svg('plus')}</a><a class="tab" href="#activity-preview">${svg('activity','nav-icon')}<span>Activity</span></a><a class="tab active" href="#you-preview">${svg('user','nav-icon')}<span>You</span></a></nav></footer>`;
const focusFooter=(primary,href,secondary='',secondaryHref='#overview')=>`<footer class="j20-footer"><a class="j20-primary" href="${href}">${primary}</a>${secondary?`<a class="j20-secondary" href="${secondaryHref}">${secondary}</a>`:''}</footer>`;
const note=(text,type='gray',icon='info')=>`<div class="j20-note ${type}">${svg(icon)}<div>${text}</div></div>`;
const stateCard=(title,copy,icon='info',type='')=>`<div class="card j20-state ${type}"><div class="j20-state-icon">${svg(icon)}</div><h1>${title}</h1><p>${copy}</p></div>`;
const status=(text,type='neutral')=>`<span class="j20-pill ${type}">${text}</span>`;
const methodIcon=k=>k==='bank'?'bank':k==='twint'?'phone':k==='paypal'?'mail':'crypto';
const methodMeta=m=>m.kind==='crypto'?`${m.fields.asset} · ${m.fields.network[0].toUpperCase()+m.fields.network.slice(1)}`:'CHF';
const methodRow=(m,{suggested=false,available=m.available,href=`#detail-${m.kind==='crypto'?'crypto':m.kind}`}={})=>`<a class="j20-method" href="${href}"><div class="j20-method-icon">${svg(methodIcon(m.kind))}</div><div class="j20-method-copy"><div class="j20-method-title"><b>${m.label}</b>${suggested?status('Suggested','good'):''}</div><span>${methodMeta(m)} · ${M.maskedDestination(m)}</span><small>${available?'Available to receive':'Not shared for receiving'}</small></div>${svg('chev','j20-chev')}</a>`;
const fact=(label,value,cls='')=>`<div class="j20-fact"><span>${label}</span><b class="${cls}">${value}</b></div>`;
const field=(label,value,help='')=>`<label class="j20-field"><span>${label}</span><div class="j20-input">${value}</div>${help?`<small>${help}</small>`:''}</label>`;
const screen=(id,title,body,{sub='Payment methods',back='#overview',footer='',withTabs=false,defaultScreen=false}={})=>`<section id="${id}" class="screen${defaultScreen?' default':''}">${header(title,sub,back)}<main class="j20-content">${body}</main>${withTabs?tabs:footer}</section>`;
const methodDetail=(id,m,extra='')=>screen(id,m.label,`<div class="card j20-detail"><div class="j20-detail-head"><div class="j20-method-icon big">${svg(methodIcon(m.kind))}</div><div><span class="j20-kicker">${methodMeta(m)}</span><h1>${m.label}</h1><p>${M.maskedDestination(m)}</p></div></div><div class="j20-facts">${fact('Available to receive',m.available?'Yes':'No')}${fact('Destination version',`v${m.version}`)}${fact('Preference',m.id===bank.id?'Suggested for CHF':m.id===dot.id?'Suggested for DOT · Polkadot':'Not preferred')}</div></div>${extra}${note(m.kind==='crypto'?'This is a public receiving destination only. It is not a connected wallet and cannot sign or authorize anything.':'Saved details help ChopDot route you to a compatible payment handoff. They never authorize a payment.','gray','shield')}`,{footer:focusFooter('Edit method',`#edit-${m.kind==='bank'?'bank':m.kind==='crypto'?'crypto':'bank'}`,'Back to methods','#overview')});

const overview=`<section id="overview" class="screen default">${header('Payment methods','Your receiving details','#you-preview')}<main class="j20-content"><div class="j20-intro"><div><span class="j20-kicker">Your receiving details</span><h1>How people can pay you</h1><p>Keep the destinations you use. ChopDot only shows a compatible suggestion when it helps.</p></div><a class="j20-add" href="#add-chooser">${svg('plus')} Add method</a></div><div class="j20-section"><h2>Saved methods</h2><span>Masked here</span></div><div class="card j20-list">${methodRow(bank,{suggested:true})}${methodRow(twint)}${methodRow(paypal)}${methodRow(dot,{suggested:true})}</div>${note('Saved methods do not move money. Settlement still asks you to review the exact amount, person and method before anything can happen.','gray','shield')}<a class="j20-preference-card" href="#preference"><div>${svg('star')}<span><b>Payment suggestions</b><small>Bank for CHF · DOT destination for Polkadot</small></span></div>${svg('chev')}</a></main>${tabs}</section>`;

const css=`
/* JOURNEY 20 — PAYMENT METHODS V1. Scoped additions. TYPO-01 unchanged. */
.j20-content{min-height:0;overflow-y:auto;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;padding:16px;display:flex;flex-direction:column;gap:12px}.j20-content>*{flex:0 0 auto}
.j20-intro{display:flex;flex-direction:column;gap:11px}.j20-intro h1{font-size:27px;line-height:1.06;letter-spacing:-.045em;margin:3px 0 0}.j20-intro p{font-size:11px;line-height:1.45;color:var(--secondary);margin:6px 0 0;max-width:330px}.j20-kicker{font-size:9px;color:#127d57;font-weight:730;text-transform:uppercase;letter-spacing:.06em}.j20-add{height:44px;border-radius:14px;background:#111113;color:white;display:flex;align-items:center;justify-content:center;gap:7px;font-size:11px;font-weight:720}.j20-add svg{width:18px;height:18px}
.j20-section{display:flex;align-items:end;justify-content:space-between;padding:3px 2px 0}.j20-section h2{font-size:13px;margin:0}.j20-section span{font-size:9px;color:var(--secondary)}.j20-list{overflow:hidden}.j20-method{display:grid;grid-template-columns:42px minmax(0,1fr) 18px;gap:10px;align-items:center;padding:12px 13px;border-top:1px solid var(--border)}.j20-method:first-child{border-top:0}.j20-method-icon{width:42px;height:42px;border-radius:13px;background:var(--surface2);display:grid;place-items:center}.j20-method-icon.big{width:48px;height:48px;border-radius:15px}.j20-method-icon svg{width:20px;height:20px}.j20-method-copy{min-width:0}.j20-method-title{display:flex;align-items:center;gap:6px;min-width:0}.j20-method-title b{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.j20-method-copy>span{display:block;font-size:9px;color:var(--secondary);margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.j20-method-copy small{display:block;font-size:8px;color:var(--muted);margin-top:3px}.j20-chev{width:16px;height:16px;color:var(--muted)}
.j20-pill{display:inline-flex;min-height:18px;align-items:center;padding:0 6px;border-radius:99px;font-size:7px;background:#eeeef0;color:#66666d;white-space:nowrap}.j20-pill.good{background:#e7f7f0;color:#137353}.j20-pill.warn{background:#fff4da;color:#875d12}.j20-pill.pink{background:#fdeaf3;color:#a32968}.j20-note{display:grid;grid-template-columns:18px minmax(0,1fr);gap:8px;padding:11px 12px;border-radius:13px;border:1px solid var(--border);font-size:9px;line-height:1.45}.j20-note svg{width:16px;height:16px}.j20-note.gray{background:#f0f0f2;color:#5c5c63}.j20-note.good{background:#e7f7f0;border-color:#c6eadc;color:#137353}.j20-note.warn{background:#fff4da;border-color:#f1dfad;color:#875d12}.j20-note.pink{background:#fdeaf3;border-color:#f3c4dc;color:#a32968}
.j20-preference-card{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:12px 13px;display:flex;align-items:center;justify-content:space-between}.j20-preference-card>div{display:grid;grid-template-columns:30px minmax(0,1fr);align-items:center;gap:9px}.j20-preference-card>div>svg{width:20px;height:20px}.j20-preference-card b{display:block;font-size:10px}.j20-preference-card small{display:block;font-size:8px;color:var(--secondary);margin-top:2px}.j20-preference-card>svg{width:16px;height:16px;color:var(--muted)}
.j20-footer{background:rgba(255,255,255,.98);border-top:1px solid var(--border);padding:10px 16px calc(10px + env(safe-area-inset-bottom));display:flex;flex-direction:column;gap:7px}.j20-primary{min-height:45px;border-radius:14px;background:#111113;color:#fff;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:720}.j20-primary.pink{background:var(--accent)}.j20-secondary{min-height:34px;display:flex;align-items:center;justify-content:center;color:var(--secondary);font-size:9px}
.j20-detail{overflow:hidden}.j20-detail-head{display:grid;grid-template-columns:48px minmax(0,1fr);gap:12px;align-items:center;padding:16px}.j20-detail-head h1{font-size:18px;margin:3px 0 0}.j20-detail-head p{font-size:10px;color:var(--secondary);margin:4px 0 0}.j20-facts{border-top:1px solid var(--border)}.j20-fact{display:grid;grid-template-columns:1fr auto;gap:10px;padding:11px 14px;border-top:1px solid var(--border);font-size:9px}.j20-fact:first-child{border-top:0}.j20-fact span{color:var(--secondary)}.j20-fact b{font-size:9px;text-align:right;max-width:210px}.j20-fact b.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:8px}
.j20-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.j20-action-card{min-height:76px;padding:13px;background:white;border:1px solid var(--border);border-radius:16px}.j20-action-card svg{width:20px;height:20px}.j20-action-card b{display:block;font-size:10px;margin-top:7px}.j20-action-card span{display:block;font-size:8px;color:var(--secondary);margin-top:3px;line-height:1.35}
.j20-choice{overflow:hidden}.j20-choice-row{display:grid;grid-template-columns:42px minmax(0,1fr) 18px;gap:11px;align-items:center;padding:13px;border-top:1px solid var(--border)}.j20-choice-row:first-child{border-top:0}.j20-choice-row .j20-method-icon{width:42px;height:42px}.j20-choice-row b{display:block;font-size:11px}.j20-choice-row span{display:block;font-size:9px;color:var(--secondary);margin-top:2px}.j20-choice-row>svg{width:16px;height:16px;color:var(--muted)}
.j20-form-title h1{font-size:24px;line-height:1.08;letter-spacing:-.04em;margin:0}.j20-form-title p{font-size:10px;line-height:1.45;color:var(--secondary);margin:6px 0 0}.j20-field{display:block}.j20-field>span{display:block;font-size:9px;color:var(--secondary);margin:0 0 5px 2px}.j20-input{min-height:48px;padding:0 13px;border:1px solid var(--border);background:white;border-radius:14px;display:flex;align-items:center;font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.j20-field small{display:block;font-size:8px;color:var(--muted);margin:5px 2px 0;line-height:1.35}.j20-field.error .j20-input{border-color:#e7a3c6;background:#fff9fc}.j20-field.error small{color:#a32968}
.j20-review{overflow:hidden}.j20-review-head{padding:16px}.j20-review-head h1{font-size:22px;letter-spacing:-.035em;margin:0}.j20-review-head p{font-size:10px;line-height:1.45;color:var(--secondary);margin:6px 0 0}.j20-review .j20-fact{padding:12px 14px}.j20-warning{padding:13px;border-top:1px solid var(--border);font-size:9px;line-height:1.45;background:#fffaf0;color:#755716}
.j20-state{padding:26px 18px;text-align:center}.j20-state-icon{width:52px;height:52px;border-radius:16px;background:var(--surface2);display:grid;place-items:center;margin:0 auto 12px}.j20-state-icon svg{width:23px;height:23px}.j20-state h1{font-size:23px;letter-spacing:-.04em;margin:0}.j20-state p{font-size:10px;line-height:1.5;color:var(--secondary);max-width:280px;margin:7px auto 0}.j20-state.good .j20-state-icon{background:#e7f7f0;color:#137353}.j20-state.warn .j20-state-icon{background:#fff4da;color:#875d12}.j20-state.pink .j20-state-icon{background:#fdeaf3;color:#a32968}
.j20-status{padding:15px}.j20-status-head{display:flex;align-items:center;gap:10px}.j20-status-head .j20-state-icon{width:42px;height:42px;margin:0;border-radius:50%}.j20-status-head b{font-size:12px}.j20-status-head span{display:block;font-size:9px;color:var(--secondary);margin-top:2px}.j20-timeline{margin-top:14px;padding-left:7px}.j20-step{position:relative;padding:0 0 13px 20px;font-size:9px;color:var(--secondary)}.j20-step:before{content:"";position:absolute;left:0;top:2px;width:8px;height:8px;border-radius:50%;background:#d7d7dc}.j20-step.done:before{background:#19a86f}.j20-step.warn:before{background:#d19a2b}.j20-step:not(:last-child):after{content:"";position:absolute;left:3px;top:10px;width:2px;bottom:1px;background:#e2e2e5}.j20-step b{display:block;color:var(--ink);font-size:10px;margin-bottom:2px}
.j20-toggle-list{overflow:hidden}.j20-toggle-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;padding:13px 14px;border-top:1px solid var(--border)}.j20-toggle-row:first-child{border-top:0}.j20-toggle-row b{display:block;font-size:10px}.j20-toggle-row span{display:block;font-size:8px;color:var(--secondary);margin-top:3px;line-height:1.35}.j20-switch{width:36px;height:22px;border-radius:99px;background:#d9d9dd;padding:3px}.j20-switch i{display:block;width:16px;height:16px;border-radius:50%;background:white;box-shadow:0 1px 3px rgba(0,0,0,.15)}.j20-switch.on{background:#17a66b}.j20-switch.on i{margin-left:14px}
.j20-demo{padding:10px 12px;background:#151516;color:#fff;border-radius:14px}.j20-demo summary{font-size:10px;font-weight:700;cursor:pointer}.j20-demo-links{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:8px}.j20-demo-links a{padding:8px;border-radius:9px;background:#262629;font-size:8px;color:#d7d7dc}.tabbar .add-tab svg{width:23px;height:23px}.tabbar .tab svg{width:20px;height:20px}
`;

let sections=[];
sections.push(overview);
sections.push(screen('empty','Payment methods',`${stateCard('No payment methods yet','Add the receiving destination you actually use. You can keep it unavailable until you need to share it.','plus')}${note('Nothing is exposed to a pot just because you add it here.','gray','shield')}`,{withTabs:true}));
sections.push(methodDetail('detail-bank',bank,`<div class="j20-actions"><a class="j20-action-card" href="#preference">${svg('star')}<b>CHF suggestion</b><span>Currently suggested when a CHF handoff needs a compatible method.</span></a><a class="j20-action-card" href="#availability">${svg('eye')}<b>Receiving availability</b><span>Available only through an authorized payment or share context.</span></a></div>`));
sections.push(methodDetail('detail-twint',twint));
sections.push(methodDetail('detail-paypal',paypal));
sections.push(methodDetail('detail-crypto',dot));
sections.push(screen('add-chooser','Add payment method',`<div class="j20-form-title"><h1>What do you use?</h1><p>Add a destination, not a payment account connection.</p></div><div class="card j20-choice"><a class="j20-choice-row" href="#add-bank"><div class="j20-method-icon">${svg('bank')}</div><div><b>Bank transfer</b><span>CHF · IBAN</span></div>${svg('chev')}</a><a class="j20-choice-row" href="#add-twint"><div class="j20-method-icon">${svg('phone')}</div><div><b>TWINT</b><span>CHF · phone or supported handle</span></div>${svg('chev')}</a><a class="j20-choice-row" href="#add-paypal"><div class="j20-method-icon">${svg('mail')}</div><div><b>PayPal</b><span>Email or username</span></div>${svg('chev')}</a><a class="j20-choice-row" href="#add-crypto"><div class="j20-method-icon">${svg('crypto')}</div><div><b>Crypto receiving destination</b><span>Public address + exact network</span></div>${svg('chev')}</a></div>${note('Cash can still be chosen during settlement, but there is nothing to save here for cash.','gray','info')}`,{footer:focusFooter('Back to methods','#overview')}));
sections.push(screen('add-bank','Bank transfer',`<div class="j20-form-title"><h1>Add your CHF account</h1><p>These are synthetic review values. The prototype never saves or sends them.</p></div>${field('Label','Backup CHF account')}${field('Account holder','Dev Demo')}${field('IBAN','CH12 0076 2011 6238 5295 8','Format can be checked here; provider ownership is not verified in this prototype.')}${field('Reference note','ChopDot demo')}${note('Full values stay owner-only here. Other people see only masked context until a payment/share flow authorizes disclosure.','gray','shield')}`,{back:'#add-chooser',footer:focusFooter('Review method','#review-new-bank','Cancel','#overview')}));
sections.push(screen('add-twint','TWINT',`<div class="j20-form-title"><h1>Add TWINT</h1><p>Use a phone number or supported handle.</p></div>${field('Label','TWINT')}${field('Swiss phone','+41 79 000 00 00')}${field('Handle','demo-handle','Optional when phone is present.')}${note('A saved TWINT destination is a receiving detail. It does not initiate or confirm a TWINT payment.','gray','shield')}`,{back:'#add-chooser',footer:focusFooter('Review method','#review-new-bank','Cancel','#overview')}));
sections.push(screen('add-paypal','PayPal',`<div class="j20-form-title"><h1>Add PayPal</h1><p>Use the destination you want to receive with.</p></div>${field('Label','PayPal')}${field('Email','demo.user@example.invalid')}${field('Username','demo-user','One supported destination is enough.')}${note('Provider login and password never belong in ChopDot.','gray','lock')}`,{back:'#add-chooser',footer:focusFooter('Review method','#review-new-bank','Cancel','#overview')}));
sections.push(screen('add-crypto','Crypto destination',`<div class="j20-form-title"><h1>Add a receiving destination</h1><p>Choose the exact asset and network. This is not wallet connection.</p></div>${field('Label','DOT receiving destination')}${field('Asset','DOT')}${field('Network','Polkadot')}${field('Public address','5DemoDotDestination111111111111111111111111111111','Format can be checked; chain ownership is not proven here.')}${note('Never paste a seed phrase, private key, recovery phrase or signing secret. ChopDot only needs a public receiving destination.','pink','lock')}`,{back:'#add-chooser',footer:focusFooter('Review method','#review-new-bank','Cancel','#overview')}));
sections.push(screen('review-new-bank','Review new method',`<div class="card j20-review"><div class="j20-review-head"><span class="j20-kicker">Before saving</span><h1>Backup CHF account</h1><p>Confirm the exact destination and how it can be suggested.</p></div><div class="j20-facts">${fact('Type','Bank transfer')}${fact('Account holder','Dev Demo')}${fact('IBAN','CH12 0076 2011 6238 5295 8','mono')}${fact('Available to receive','Yes')}${fact('Suggested for CHF','No')}</div></div>${note('Saving adds a destination only. It does not change a balance, request, settlement or payment status.','gray','shield')}`,{back:'#add-bank',footer:focusFooter('Save method','#save-pending','Edit details','#add-bank')}));
sections.push(screen('edit-bank','Edit method',`<div class="j20-form-title"><h1>Update Main CHF account</h1><p>This method is currently destination version v3.</p></div>${field('Label','Main CHF account')}${field('Account holder','Dev Demo')}${field('IBAN','CH93 0076 2011 6238 5295 7')}${field('Reference note','Updated demo reference')}${note('Saving an edit creates destination version v4. Any active share or review bound to v3 becomes stale and must be reviewed again.','warn','link')}`,{footer:focusFooter('Review changes','#review-edit-bank','Cancel','#detail-bank')}));
sections.push(screen('edit-crypto','Edit crypto destination',`<div class="j20-form-title"><h1>Update DOT destination</h1><p>Current destination version v4 · Polkadot.</p></div>${field('Label','DOT receiving destination')}${field('Asset','DOT')}${field('Network','Polkadot')}${field('Public address','5DemoDotDestination111111111111111111111111111111')}${note('Changing network or address creates a new destination version. Existing shares do not silently follow the edit.','warn','link')}`,{back:'#detail-crypto',footer:focusFooter('Review changes','#review-edit-bank','Cancel','#detail-crypto')}));
sections.push(screen('review-edit-bank','Review changes',`<div class="card j20-review"><div class="j20-review-head"><span class="j20-kicker">Destination update</span><h1>Main CHF account</h1><p>The saved destination will move from v3 to v4.</p></div><div class="j20-facts">${fact('IBAN','CH93 0076 2011 6238 5295 7','mono')}${fact('Reference note','Updated demo reference')}${fact('New destination version','v4')}</div><div class="j20-warning">1 active receiving share uses v3. It will become stale after this update instead of silently pointing to v4.</div></div>`,{back:'#edit-bank',footer:focusFooter('Save update','#save-pending','Keep v3','#detail-bank')}));
sections.push(screen('save-pending','Saving method',`<div class="card j20-status"><div class="j20-status-head"><div class="j20-state-icon">${svg('refresh')}</div><div><b>Saving your destination</b><span>Command j20-save-demo-01</span></div></div><div class="j20-timeline"><div class="j20-step done"><b>Review completed</b>Exact fields and availability confirmed.</div><div class="j20-step warn"><b>Save result pending</b>Do not submit the same command again while its result is unknown.</div><div class="j20-step"><b>Readable record</b>Appears after the accepted version can be read.</div></div></div>${note('A pending save still cannot authorize or confirm a payment.','gray','shield')}`,{footer:focusFooter('Demo accepted result','#save-accepted','Demo result unknown','#save-unknown')}));
sections.push(screen('save-accepted','Method saved',`${stateCard('Payment method saved','The accepted destination is readable as its own version. No payment or balance changed.','check','good')}<div class="card j20-facts">${fact('Method','Backup CHF account')}${fact('Destination version','v1')}${fact('Available to receive','Yes')}</div>`,{footer:focusFooter('Back to methods','#overview')}));
sections.push(screen('save-unknown','Check the original save',`${stateCard('We do not know the save result yet','ChopDot keeps the original command identity and checks that result before allowing another save.','refresh','warn')}${note('Retry is blocked until the original result is recovered. This prevents duplicate destination records.','warn','shield')}`,{footer:focusFooter('Check original result','#save-recovered','Back to methods','#overview')}));
sections.push(screen('save-recovered','Original result checked',`${stateCard('The original save did not complete','It is now verified as not accepted, so a safe retry can use a new attempt without duplicating an accepted record.','check','good')}`,{footer:focusFooter('Retry save','#save-pending','Cancel','#overview')}));
sections.push(screen('save-failed','Could not save',`${stateCard('Payment method was not saved','The failure is verified. Your existing methods are unchanged and you can safely retry.','alert','pink')}`,{footer:focusFooter('Try again','#review-new-bank','Back to methods','#overview')}));
sections.push(screen('invalid-bank','Check the IBAN',`<div class="j20-form-title"><h1>One detail needs fixing</h1><p>ChopDot can check structure without pretending the bank account is provider-verified.</p></div>${field('IBAN','CH12 34','Use a complete Swiss IBAN. This is a format check only.').replace('j20-field','j20-field error')}${note('Ownership and account status are not proven by a local format check.','gray','info')}`,{back:'#add-bank',footer:focusFooter('Fix IBAN','#add-bank')}));
sections.push(screen('duplicate','Already saved',`${stateCard('You already have this destination','The normalized destination matches Main CHF account. Edit the existing method instead of creating a duplicate.','copy','warn')}`,{footer:focusFooter('Open existing method','#detail-bank','Back','#add-bank')}));
sections.push(screen('preference','Payment suggestions',`<div class="j20-form-title"><h1>Suggestions by context</h1><p>Preferred means suggested among compatible methods. It never means authorized.</p></div><div class="card j20-toggle-list"><div class="j20-toggle-row"><div><b>CHF</b><span>Main CHF account</span></div>${status('Suggested','good')}</div><div class="j20-toggle-row"><div><b>DOT · Polkadot</b><span>DOT receiving destination</span></div>${status('Suggested','good')}</div></div><a class="card j20-choice-row" href="#incompatible-asset"><div class="j20-method-icon">${svg('phone')}</div><div><b>Try TWINT for DOT</b><span>Demo incompatible preference</span></div>${svg('chev')}</a>${note('Settlement revalidates the actual method against the exact asset and network every time.','gray','shield')}`,{footer:focusFooter('Done','#overview')}));
sections.push(screen('availability','Receiving availability',`<div class="j20-form-title"><h1>Where can this method appear?</h1><p>Availability controls authorized payment/share handoffs, not public directory visibility.</p></div><div class="card j20-toggle-list"><div class="j20-toggle-row"><div><b>Available when someone needs to pay you</b><span>Exact details remain hidden until the payment/share context allows them.</span></div><span class="j20-switch on"><i></i></span></div><div class="j20-toggle-row"><div><b>Public in Pots</b><span>Not supported. Saving a method never publishes raw receiving details to a pot.</span></div><span class="j20-switch"><i></i></span></div></div>${note('Another person may see a masked suggestion in People, but raw IBAN/phone/email/address disclosure belongs to settlement or Receive / Share.','gray','eye')}`,{footer:focusFooter('Save availability','#save-accepted','Cancel','#detail-bank')}));
sections.push(screen('remove-confirm','Remove payment method',`<div class="card j20-review"><div class="j20-review-head"><span class="j20-kicker">Future use only</span><h1>Remove Main CHF account?</h1><p>This stops future suggestion and disclosure of this destination.</p></div><div class="j20-warning">An active receiving share bound to destination v3 will become stale. Already exported copies outside ChopDot cannot be recalled.</div></div>${note('Removing this method does not cancel a request, reverse a payment, erase settlement history or change any balance.','gray','shield')}`,{back:'#detail-bank',footer:focusFooter('Remove method','#remove-pending','Keep method','#detail-bank')}));
sections.push(screen('remove-pending','Removing method',`<div class="card j20-status"><div class="j20-status-head"><div class="j20-state-icon">${svg('refresh')}</div><div><b>Checking removal result</b><span>Command j20-remove-demo-01</span></div></div><div class="j20-timeline"><div class="j20-step done"><b>Removal reviewed</b>Future use and stale-share impact confirmed.</div><div class="j20-step warn"><b>Result pending</b>Duplicate removal is blocked.</div></div></div>`,{footer:focusFooter('Demo accepted','#remove-accepted','Demo result unknown','#remove-unknown')}));
sections.push(screen('remove-accepted','Method removed',`${stateCard('Main CHF account removed','It is no longer available for future payment/share handoffs. Existing settlement history still records which destination version was used.','check','good')}`,{footer:focusFooter('Back to methods','#overview')}));
sections.push(screen('remove-unknown','Check the original removal',`${stateCard('Removal result is unknown','ChopDot checks the original command before allowing another destructive attempt.','refresh','warn')}`,{footer:focusFooter('Check original result','#remove-recovered','Back','#detail-bank')}));
sections.push(screen('remove-recovered','Original removal checked',`${stateCard('The method was not removed','The original command is verified as not accepted. A retry is now safe.','check','good')}`,{footer:focusFooter('Retry removal','#remove-pending','Keep method','#detail-bank')}));
sections.push(screen('remove-failed','Could not remove',`${stateCard('Main CHF account is still saved','The removal failed and was verified as not accepted. Nothing else changed.','alert','pink')}`,{footer:focusFooter('Try again','#remove-confirm','Back','#detail-bank')}));
sections.push(screen('share-stale-edit','Receiving detail changed',`${stateCard('This share needs a fresh review','The share was created from Main CHF account v3. The owner edited the destination to v4, so the old share cannot silently follow the new details.','link','warn')}${note('Open Receive / Share to create a new disclosure from the current destination version.','gray','shield')}`,{footer:focusFooter('Open Receive / Share','#handoff-receive','Back to methods','#overview')}));
sections.push(screen('share-stale-remove','Receiving detail removed',`${stateCard('This saved share is no longer current','The destination used by this ChopDot share was removed. Future access is blocked rather than redirecting to another method.','link','pink')}${note('A value that someone already copied or screenshotted outside ChopDot cannot be recalled.','gray','info')}`,{footer:focusFooter('Back to methods','#overview')}));
sections.push(screen('incompatible-asset','Not compatible',`${stateCard('TWINT cannot receive this DOT settlement','This context is DOT on Polkadot. A CHF-oriented method cannot become compatible just because it is preferred.','alert','warn')}${note('ChopDot does not convert DOT to CHF to make a payment method fit.','gray','shield')}`,{footer:focusFooter('Choose DOT destination','#detail-crypto','Back to suggestions','#preference')}));
sections.push(screen('network-mismatch','Network does not match',`${stateCard('Choose the Polkadot destination','The asset is DOT, but this demo destination is for a different network. Matching the ticker alone is not enough.','alert','warn')}${note('Exact asset + network are revalidated before a crypto handoff.','gray','shield')}`,{footer:focusFooter('Use DOT · Polkadot','#detail-crypto','Open Wallet & Crypto','#handoff-wallet')}));
sections.push(screen('offline','Payment methods','${PLACEHOLDER}',{withTabs:true}));
sections[sections.length-1]=screen('offline','Payment methods',`${note("You're offline. Showing the last saved masked method list. New edits from another device may be missing.",'warn','wifi')}<div class="card j20-list">${methodRow(bank,{suggested:true})}${methodRow(twint)}${methodRow(dot,{suggested:true})}</div>${note('Full write actions stay blocked until ChopDot can verify the latest destination version.','gray','shield')}`,{withTabs:true});
sections.push(screen('offline-write','Offline',`${stateCard('Reconnect before changing payment details','Add, edit, remove, preference and availability writes are blocked while ChopDot cannot verify the latest version.','wifi','warn')}`,{footer:focusFooter('Back to saved methods','#offline')}));
sections.push(screen('session-changed','Payment methods',`${stateCard('Sign in again to view full details','Owner-only destination values were removed from this screen when the session changed. Masked navigation can return after access is verified.','lock','warn')}`,{footer:focusFooter('Back','#overview')}));
sections.push(screen('loading','Payment methods',`<div class="card loading-card"><div class="skel big"></div><div class="skel"></div><div class="skel med"></div></div><div class="card loading-card"><div class="skel med"></div><div class="skel"></div><div class="skel short"></div></div>`,{withTabs:true}));
sections.push(screen('error','Payment methods',`${stateCard('Payment methods did not load','No preferred or available method is inferred while the current records are unavailable.','refresh','pink')}`,{footer:focusFooter('Try again','#overview')}));
sections.push(screen('handoff-settlement','Settlement preview',`${note('Journey 11 owns the exact person, amount, source items, compatible-method revalidation and human authorization. Journey 20 supplies only a saved destination suggestion.','gray','shield')}`,{footer:focusFooter('Return to payment methods','#overview')}));
sections.push(screen('handoff-receive','Receive / Share preview',`${note('Journey 14 owns deliberate disclosure, copy and private-share behavior. It binds the share to the exact payment-method destination version selected here.','gray','link')}`,{footer:focusFooter('Return to payment methods','#overview')}));
sections.push(screen('handoff-wallet','Wallet & Crypto preview',`${note('Journey 21 owns wallet connection, switching, signing, execution and finality. A Journey 20 crypto destination is only a public receiving address + exact network.','gray','crypto')}`,{footer:focusFooter('Return to payment methods','#overview')}));
const navPreview=(id,title,copy)=>screen(id,title,`${note(copy,'gray','shield')}`,{footer:focusFooter('Return to payment methods','#overview')});
sections.push(navPreview('pots-preview','Pots preview','Pots remains an approved adjacent surface. Journey 20 does not redesign it.'));
sections.push(navPreview('people-preview','People preview','People remains an approved adjacent surface. Another person’s payment preference stays masked and read-only there.'));
sections.push(navPreview('add-preview','Add preview','The global Add action remains separate from Add payment method. Journey 20 does not redesign the app-wide action.'));
sections.push(navPreview('activity-preview','Activity preview','Activity remains Journey 18. Payment-method edits may create meaningful activity later, but this prototype does not redesign the feed.'));
sections.push(navPreview('you-preview','You preview','You remains the entry surface for your own payment methods. Journey 20 does not redesign the full profile/account experience.'));
const demoIds=['overview','empty','detail-bank','detail-twint','detail-paypal','detail-crypto','add-chooser','add-bank','add-twint','add-paypal','add-crypto','review-new-bank','edit-bank','review-edit-bank','save-pending','save-accepted','save-unknown','save-recovered','save-failed','invalid-bank','duplicate','preference','availability','remove-confirm','remove-pending','remove-accepted','remove-unknown','remove-recovered','remove-failed','share-stale-edit','share-stale-remove','incompatible-asset','network-mismatch','offline','offline-write','session-changed','loading','error'];
sections.push(screen('demo','Demo states',`<details class="j20-demo" open><summary>Review Journey 20 states</summary><div class="j20-demo-links">${demoIds.map(id=>`<a href="#${id}">${id.replaceAll('-',' ')}</a>`).join('')}</div></details>${note('Demo navigation changes only this standalone prototype. No payment detail, share, provider account, wallet or money is created.','gray','shield')}`,{footer:focusFooter('Back to payment methods','#overview')}));

const valid=[...sections.join('').matchAll(/<section id="([^"]+)"/g)].map(m=>m[1]);
const unique=[...new Set(valid)];if(unique.length!==valid.length)throw new Error('Duplicate Journey 20 screen IDs');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>ChopDot — Payment Methods V1</title><style>${inherited}</style><style>${shell}</style><style>${css}</style></head><body><div class="lab"><main class="stage"><div class="device">${sections.join('')}</div></main><aside class="labpanel"><h2>Journey 20 — Payment Methods V1</h2><p>Prototype only. Saved destinations, masking, compatibility, versioning, availability and recovery.</p><div class="labsec"><div class="lablabel">Review</div><a class="current" href="#overview">Overview</a><a class="current" href="#add-chooser">Add method</a><a class="current" href="#review-edit-bank">Edit version impact</a><a class="current" href="#preference">Suggestions</a><a class="current" href="#share-stale-edit">Stale share</a><a class="current" href="#network-mismatch">Network mismatch</a></div><div class="labsec"><p class="note">19 approved Goldens unchanged. Journey 20 is review candidate only. TYPO-01 remains deferred.</p></div></aside></div><script>const valid=new Set(${JSON.stringify(unique)});function normalize(){const id=location.hash.slice(1);if(id&&!valid.has(id))location.replace('#overview');}addEventListener('hashchange',normalize);normalize();</script></body></html>`;
const out=path.join(reviewDir,'v1-candidate.html');fs.writeFileSync(out,html);
const hash=crypto.createHash('sha256').update(html).digest('hex');
console.log(JSON.stringify({ok:true,version:'v1',screens:unique.length,path:path.relative(journeyDir,out),sha256:hash},null,2));
