/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CloseoutRegistry {
  export type CloseoutStruct = {
    snapshotHash: BytesLike;
    asset: string;
    metadataHash: string;
    creator: AddressLike;
    createdAt: BigNumberish;
    completed: boolean;
    settledLegCount: BigNumberish;
    totalLegCount: BigNumberish;
  };

  export type CloseoutStructOutput = [
    snapshotHash: string,
    asset: string,
    metadataHash: string,
    creator: string,
    createdAt: bigint,
    completed: boolean,
    settledLegCount: bigint,
    totalLegCount: bigint
  ] & {
    snapshotHash: string;
    asset: string;
    metadataHash: string;
    creator: string;
    createdAt: bigint;
    completed: boolean;
    settledLegCount: bigint;
    totalLegCount: bigint;
  };

  export type SettlementLegStruct = {
    payer: AddressLike;
    payee: AddressLike;
    amount: BigNumberish;
    settlementTxHash: BytesLike;
    proofTxHash: BytesLike;
    status: BigNumberish;
  };

  export type SettlementLegStructOutput = [
    payer: string,
    payee: string,
    amount: bigint,
    settlementTxHash: string,
    proofTxHash: string,
    status: bigint
  ] & {
    payer: string;
    payee: string;
    amount: bigint;
    settlementTxHash: string;
    proofTxHash: string;
    status: bigint;
  };
}

export interface CloseoutRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createCloseout"
      | "getCloseout"
      | "getLeg"
      | "markLegAcknowledged"
      | "nextCloseoutId"
      | "recordSettlementProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CloseoutCompleted"
      | "CloseoutCreated"
      | "SettlementProofRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createCloseout",
    values: [
      BytesLike,
      string,
      string,
      AddressLike[],
      AddressLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCloseout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLeg",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markLegAcknowledged",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCloseoutId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordSettlementProof",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCloseout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCloseout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLeg", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markLegAcknowledged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextCloseoutId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSettlementProof",
    data: BytesLike
  ): Result;
}

export namespace CloseoutCompletedEvent {
  export type InputTuple = [closeoutId: BigNumberish];
  export type OutputTuple = [closeoutId: bigint];
  export interface OutputObject {
    closeoutId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CloseoutCreatedEvent {
  export type InputTuple = [
    closeoutId: BigNumberish,
    snapshotHash: BytesLike,
    creator: AddressLike,
    asset: string,
    metadataHash: string
  ];
  export type OutputTuple = [
    closeoutId: bigint,
    snapshotHash: string,
    creator: string,
    asset: string,
    metadataHash: string
  ];
  export interface OutputObject {
    closeoutId: bigint;
    snapshotHash: string;
    creator: string;
    asset: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementProofRecordedEvent {
  export type InputTuple = [
    closeoutId: BigNumberish,
    legIndex: BigNumberish,
    settlementTxHash: BytesLike,
    proofTxHash: BytesLike,
    status: BigNumberish
  ];
  export type OutputTuple = [
    closeoutId: bigint,
    legIndex: bigint,
    settlementTxHash: string,
    proofTxHash: string,
    status: bigint
  ];
  export interface OutputObject {
    closeoutId: bigint;
    legIndex: bigint;
    settlementTxHash: string;
    proofTxHash: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CloseoutRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CloseoutRegistry;
  waitForDeployment(): Promise<this>;

  interface: CloseoutRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createCloseout: TypedContractMethod<
    [
      snapshotHash: BytesLike,
      asset: string,
      metadataHash: string,
      payers: AddressLike[],
      payees: AddressLike[],
      amounts: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;

  getCloseout: TypedContractMethod<
    [closeoutId: BigNumberish],
    [CloseoutRegistry.CloseoutStructOutput],
    "view"
  >;

  getLeg: TypedContractMethod<
    [closeoutId: BigNumberish, legIndex: BigNumberish],
    [CloseoutRegistry.SettlementLegStructOutput],
    "view"
  >;

  markLegAcknowledged: TypedContractMethod<
    [closeoutId: BigNumberish, legIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextCloseoutId: TypedContractMethod<[], [bigint], "view">;

  recordSettlementProof: TypedContractMethod<
    [
      closeoutId: BigNumberish,
      legIndex: BigNumberish,
      settlementTxHash: BytesLike,
      proofTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createCloseout"
  ): TypedContractMethod<
    [
      snapshotHash: BytesLike,
      asset: string,
      metadataHash: string,
      payers: AddressLike[],
      payees: AddressLike[],
      amounts: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCloseout"
  ): TypedContractMethod<
    [closeoutId: BigNumberish],
    [CloseoutRegistry.CloseoutStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLeg"
  ): TypedContractMethod<
    [closeoutId: BigNumberish, legIndex: BigNumberish],
    [CloseoutRegistry.SettlementLegStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "markLegAcknowledged"
  ): TypedContractMethod<
    [closeoutId: BigNumberish, legIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextCloseoutId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordSettlementProof"
  ): TypedContractMethod<
    [
      closeoutId: BigNumberish,
      legIndex: BigNumberish,
      settlementTxHash: BytesLike,
      proofTxHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CloseoutCompleted"
  ): TypedContractEvent<
    CloseoutCompletedEvent.InputTuple,
    CloseoutCompletedEvent.OutputTuple,
    CloseoutCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CloseoutCreated"
  ): TypedContractEvent<
    CloseoutCreatedEvent.InputTuple,
    CloseoutCreatedEvent.OutputTuple,
    CloseoutCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementProofRecorded"
  ): TypedContractEvent<
    SettlementProofRecordedEvent.InputTuple,
    SettlementProofRecordedEvent.OutputTuple,
    SettlementProofRecordedEvent.OutputObject
  >;

  filters: {
    "CloseoutCompleted(uint256)": TypedContractEvent<
      CloseoutCompletedEvent.InputTuple,
      CloseoutCompletedEvent.OutputTuple,
      CloseoutCompletedEvent.OutputObject
    >;
    CloseoutCompleted: TypedContractEvent<
      CloseoutCompletedEvent.InputTuple,
      CloseoutCompletedEvent.OutputTuple,
      CloseoutCompletedEvent.OutputObject
    >;

    "CloseoutCreated(uint256,bytes32,address,string,string)": TypedContractEvent<
      CloseoutCreatedEvent.InputTuple,
      CloseoutCreatedEvent.OutputTuple,
      CloseoutCreatedEvent.OutputObject
    >;
    CloseoutCreated: TypedContractEvent<
      CloseoutCreatedEvent.InputTuple,
      CloseoutCreatedEvent.OutputTuple,
      CloseoutCreatedEvent.OutputObject
    >;

    "SettlementProofRecorded(uint256,uint32,bytes32,bytes32,uint8)": TypedContractEvent<
      SettlementProofRecordedEvent.InputTuple,
      SettlementProofRecordedEvent.OutputTuple,
      SettlementProofRecordedEvent.OutputObject
    >;
    SettlementProofRecorded: TypedContractEvent<
      SettlementProofRecordedEvent.InputTuple,
      SettlementProofRecordedEvent.OutputTuple,
      SettlementProofRecordedEvent.OutputObject
    >;
  };
}
