import {requirePrototypeWriter,assertPrototypeWriter} from '../prototype-writer.js';
import {repository,member,membershipActive,groupMembers,inviteContext,online,assertOwner,fail} from './model.js';
import {currentActor,grantFixture,revokeFixture,signFixture,verifyFixture,consumeFixture} from './authority.js';
import {position} from '../gate-b/model.js';
import {formatPreviewMoney} from '../money-v1.js';
await requirePrototypeWriter();
const repo=repository(localStorage,assertPrototypeWriter,verifyFixture),app=document.querySelector('#app');
const docs=Object.fromEntries(await Promise.all(['j03','j04','j04-c1'].map(async j=>[j,new DOMParser().parseFromString(await fetch(`./goldens/${j}.html`).then(r=>{if(!r.ok)throw Error('Approved source unavailable');return r.text();}),'text/html')])));
const fixtureMode=new URLSearchParams(location.search).has('fixtures');let s,route,screen;
const el=(tag,cls='',t)=>{const n=document.createElement(tag);n.className=cls;if(t!==undefined)n.textContent=t;return n;};
const $=q=>screen.querySelector(q),$$=q=>[...screen.querySelectorAll(q)];
const guarded=fn=>(...args)=>{try{return fn(...args);}catch(e){notice(e.message,true);}};
const action=(q,fn)=>$$(q).forEach(n=>n.onclick=guarded(e=>{e.preventDefault();fn();}));
const text=(q,t)=>$$(q).forEach(n=>n.textContent=t);
function notice(t,bad=false){const n=el('p','cj-note'+(bad?' cj-error':''),t);n.role=bad?'alert':'status';($('.content,.card')||screen).prepend(n);return n;}
function button(t,fn,cls='btn secondary'){const n=el('button',cls,t);n.type='button';n.onclick=guarded(fn);return n;}
function nav(page,extra={}){const r={page,...(route?.invite?{invite:route.invite}:{}),...extra};const hash=new URLSearchParams(r).toString();if(hash===location.hash.slice(1))render();else location.hash=hash;}
function commit(c,authority){const command=signFixture(repo.read(),{...c,operationId:c.operationId||crypto.randomUUID()});const next=repo.commit(command,authority);consumeFixture(command);return next;}
function actor(id){sessionStorage.setItem('chopdot.membership.actor',id);sessionStorage.setItem('chopdot.gate-b.actor',id);}
function mount(j,id){document.documentElement.dataset.source=j;document.querySelector('#golden-style').textContent=[...docs[j].querySelectorAll('style')].map(n=>n.textContent).join('\n');const source=docs[j].getElementById(id);if(!source)throw Error('Missing approved state '+j+'/'+id);if(j==='j04-c1'){screen=docs[j].querySelector('main').cloneNode(true);screen.querySelectorAll('section,.footer').forEach(n=>n.remove());const section=source.cloneNode(true);section.classList.remove('hidden');screen.append(section);}else screen=source.cloneNode(true);screen.querySelectorAll('script').forEach(n=>n.remove());screen.dataset.journey=j;screen.dataset.golden=id;screen.tabIndex=-1;app.replaceChildren(screen);$$("a").forEach(a=>a.onclick=e=>{e.preventDefault();const page=a.getAttribute('href')?.slice(1);if(page)nav(page);});}
function openGroup(page='group'){const p=member(s,currentActor());if(p&&!membershipActive(s,p.id,p.groupId))fail('ACCESS','Your membership ended. Historical attribution is preserved, but group access is unavailable.');if(p&&p.groupId!==s.group?.id)s=repo.selectJoinedGroup(p.id);location.href=`../gate-b/index.html${fixtureMode?'?fixtures=1':''}#page=${page}`;}
function owner(){actor('self');nav('invite',{invite:''});}
function entry(mode){sessionStorage.setItem('chopdot.membership.entry-return',JSON.stringify({invite:route.invite||'',page:mode,participantId:currentActor()}));if(parent!==window)parent.postMessage({type:'chopdot-create-join-entry'},location.origin);else location.href='../index.html?entry=signin';}
function entryVerified(){const h=parent!==window?parent:window;return h.ChopDotEntryPrecondition?.verified===true&&h.ChopDotEntryPrecondition.participantId===currentActor()&&h.ChopDotEntryPrecondition.invite===(route.invite||'');}
function makeDraft(){return s.membership.creation||{id:crypto.randomUUID(),operationId:crypto.randomUUID(),name:'',currency:'CHF'};}
function create(){if(!online(s)&&route.page!=='offline'){nav('offline');return;}const d=makeDraft();const input=$('.name-input');if(input)d.name=input.value;repo.saveCreation(d);try{commit({type:'create',...d,actor:'self'});nav('success',{invite:''});}catch(e){nav('error',{invite:''});sessionStorage.setItem('chopdot.creation.error',e.message);}}
function creation(page){if(currentActor()!=='self')fail('PERMISSION','Return to the inviter fixture before creating a group.');const mapped=['entry','currency','advanced-currency','offline','error','savings'].includes(page)?page:'entry';mount('j03',mapped);const d=makeDraft();
 if(mapped==='entry'){const input=$('.name-input');input.value=d.name;input.maxLength=80;input.oninput=()=>{d.name=input.value;try{repo.saveCreation(d);}catch(e){notice('Could not retain this draft. '+e.message,true);}};text('.pill',d.currency);action('[href="#success"]',create);}
 if(mapped==='currency'){const check=$('.check').cloneNode(true);$$('.choice .check').forEach(n=>n.remove());$$('.choice').forEach(a=>{const code=a.querySelector('.choice-title')?.textContent;if(['CHF','EUR','USD'].includes(code)){a.classList.toggle('selected',code===d.currency);if(code===d.currency)a.append(check);a.onclick=guarded(e=>{e.preventDefault();d.currency=code;repo.saveCreation(d);nav('entry');});}});text('.footer a','Keep '+d.currency);}
 if(mapped==='offline'){text('.lead',`${d.name||'New group'} · ${d.currency}`);text('.banner','Offline. Save on this device; sharing waits for reconnection.');action('[href="#success"]',create);}
 if(mapped==='error'){text('.lead',`${d.name||'New group'} · ${d.currency}`);action('[href="#success"]',create);if(sessionStorage.getItem('chopdot.creation.error'))notice(sessionStorage.getItem('chopdot.creation.error'),true);}
 if(mapped==='advanced-currency')notice('These approved choices remain outside this bounded prototype. No conversion or payment rail is selected.');
 if(mapped==='savings'){const next=button('Continue to savings',()=>{location.href='../expansion/index.html'+(fixtureMode?'?fixtures=1':'')+'#family=16&page=list&group=';},'btn dark');$('.footer').prepend(next);}
}
function success(){if(currentActor()!=='self')fail('PERMISSION','Open your joined group through membership.');if(!s.group) return creation('entry');mount('j03',s.group.currency==='EUR'?'success-eur':s.group.currency==='USD'?'success-usd':'success');text('.success-title',s.group.name+' is ready.');text('.group-name',s.group.name);text('.group-meta',s.group.currency+' · '+(groupMembers(s).length===1?'only you':groupMembers(s).length+' people'));const facts=$$('.state-item b');if(facts[0])facts[0].textContent=groupMembers(s).length;if(facts[1])facts[1].textContent=s.expenses.filter(e=>e.groupId===s.group.id&&!e.deleted).length;const units=BigInt(position(s,'self')[s.group.currency+':2']||'0');text('.group-balance',(units<0n?'−':'')+formatPreviewMoney({v:1,currency:s.group.currency,exponent:2,minorUnits:(units<0n?-units:units).toString()}));if(s.expenses.some(e=>e.groupId===s.group.id&&!e.deleted))$('.empty-block')?.remove();action('[href="#invite-handoff"]',()=>nav('invite'));action('[href="#expense-handoff"]',()=>openGroup('editor'));$('.footer').append(button('Open group',()=>openGroup(),'btn text'));}
function invitation(page){assertOwner(s,currentActor());mount('j04',page);text('.header-title',s.group.name);if(['share','invite-sent'].includes(page))text('.lead',s.group.name);const invitations=s.membership.invitations.filter(i=>i.groupId===s.group.id);const latest=invitations.at(-1);const selected=page==='share'?invitations.filter(i=>i.kind==='group-link'&&i.status==='pending').at(-1):(s.membership.invitations.find(i=>i.id===route.invite)||latest);
 if(page==='add-person'){const input=$('input');input.value='';input.maxLength=60;input.setAttribute('aria-label','Invitee name');action('[href="#person-added"]',()=>{const id=crypto.randomUUID();commit({type:'invite',id,name:input.value,actor:currentActor()});nav('person-added',{invite:id});});}
 if(page==='share'){text('.invite-name',selected?inviteUrl(selected):'Create a local invitation first.');const linkField=$('input');if(linkField){linkField.value=selected?inviteUrl(selected):'';linkField.readOnly=true;}action('[href="#invite-sent"]',()=>{let i=selected;if(!i){const id=crypto.randomUUID();commit({type:'invite',id,name:'Invited person',kind:'group-link',actor:currentActor()});i=repo.read().membership.invitations.find(i=>i.id===id);}nav('invite-sent',{invite:i.id});});notice('Local prototype link: it opens this browser’s invitation record. No message is sent and no remote membership is created.');}
 const list=$('.member-list');if(list){const template=list.querySelector('.member').cloneNode(true);list.replaceChildren();for(const p of groupMembers(s)){const row=template.cloneNode(true);row.querySelector('.person-name').textContent=p.name;row.querySelector('.person-meta').textContent=p.id===(s.group.ownerId||'self')?'Owner':'Member';row.querySelector('.status').textContent='Joined';row.querySelector('.person-avatar').textContent=p.name.slice(0,2).toUpperCase();list.append(row);}for(const i of invitations.filter(i=>i.status!=='joined')){const row=template.cloneNode(true);row.querySelector('.person-name').textContent=i.name;row.querySelector('.person-meta').textContent=i.status==='pending'?'Invite sent':'Expired';row.querySelector('.status').textContent=i.status==='pending'?'Pending':'Expired';row.querySelector('.status').className='status pending';row.querySelector('.person-avatar').textContent=i.name.slice(0,2).toUpperCase();list.append(row);}}
 if(page==='person-added'&&selected){text('.success-title',`Invite for ${selected.name}.`);text('.lead,.success-sub',`${selected.name} can join when ready.`);}
 action('[href="#group-handoff"]',()=>openGroup());
 if(selected){$('.footer').append(button('View invite as recipient (prototype)',()=>{actor('visitor');sessionStorage.setItem('chopdot.membership.invite',selected.id);nav('join',{invite:selected.id});},'btn text'));}
 if(page==='invite-sent'&&selected)notice(inviteUrl(selected));
}
function inviteUrl(i){const u=new URL('../index.html',location.href);u.searchParams.set('createJoin',new URLSearchParams({page:'join',invite:i.id}).toString());if(fixtureMode)u.searchParams.set('fixtures','1');return u.href;}
function recipient(page){const id=route.invite||sessionStorage.getItem('chopdot.membership.invite');const info=inviteContext(s,id);const i=s.membership.invitations.find(i=>i.id===id);if(currentActor()==='self'||(i.status==='pending'&&!i.redemptions?.includes(currentActor())&&member(s,currentActor()))){actor('visitor');}sessionStorage.setItem('chopdot.membership.invite',id);
 if(i.status==='expired')page='expired';else if(!online(s)&&i.status==='pending')page='offline';else if(i.status==='joined'||i.redemptions?.includes(currentActor()))page=i.redemptions?.includes(currentActor())||currentActor()===i.participantId?'already':'expired';
 mount('j04',page);text('.invite-name,.success-sub',info.name);if(!['not-now','offline','closed'].includes(page))text('.lead',info.name);text('.avatar',i.name.slice(0,2).toUpperCase());text('.title',page==='join'?`${info.inviter} invited you.`:page==='offline'?info.name:$('.title')?.textContent||'');text('.invite-by','Invited by '+info.inviter);$$('.stat').forEach(n=>{n.querySelector('b').textContent=n.querySelector('span').textContent==='People'?info.people:info.currency;});$('.people-stack')?.replaceChildren();action('[href="#joined"]',()=>nav('consent',{invite:id}));action('[href="#group-handoff"]',()=>{if(!i.redemptions?.includes(currentActor())&&currentActor()!==i.participantId)fail('PARTICIPANT','Recover your existing participant.');openGroup();});if(i.status==='pending'&&page==='join')$('.footer').append(button('Sign in instead',()=>nav('account',{invite:id}),'btn text'));
}
function join(identity='guest'){
 const id=route.invite||sessionStorage.getItem('chopdot.membership.invite'),i=s.membership.invitations.find(i=>i.id===id);if(!i)fail('INVITE','Reopen the invite.');
 const participantId=i.groupId+':p_'+crypto.randomUUID();const next=commit({type:'join',inviteId:id,consent:true,participantId,identity,actor:'visitor',evidence:identity==='account_backed'?{accountProof:true,activation:true,durableBinding:true,readback:true}:undefined},identity==='account_backed'?'entry-verified':'user');actor(participantId);grantFixture(next,participantId);nav('member',{invite:id});
}
function c1(page){const p=member(s,currentActor());if(p&&!membershipActive(s,p.id,p.groupId))fail('ACCESS','Your membership ended. Historical attribution is preserved. Saved labels cannot restore group access.');if(p&&s.group?.id!==p.groupId)s=repo.selectJoinedGroup(p.id);if(page==='member'&&p?.identity==='linked')page='linked';const map={member:'joined','link':'link','pending':'link-pending',unknown:'link-unknown','no-effect':'link-no-effect',mismatch:'unresolved',cancelled:'link-cancelled',failed:'link-failed',linked:'linked',recovery:'recovery',consent:'consent',account:'account'};if(!['consent','account','recovery'].includes(page)&&!p)fail('PARTICIPANT','Reopen your invitation or recover your existing participant.');
 if(['consent','account'].includes(page)){const info=inviteContext(s,route.invite);if(info.status!=='pending'||!online(s))return recipient('join');}
 if(p&&['link','pending','unknown','no-effect','mismatch','cancelled','failed','linked'].includes(page)){const actual=p.identity==='linked'?'linked':({prepared:'link',pending:'pending',unknown:'unknown','no-effect':'no-effect',mismatch:'mismatch',cancelled:'cancelled','known-pre-effect-failed':'failed',linked:'linked'}[p.link?.status]||'member');if(actual!==page)page=actual;}
 mount('j04-c1',map[page]||'recovery');if(p){const walker=document.createTreeWalker(screen,NodeFilter.SHOW_TEXT);while(walker.nextNode())walker.currentNode.textContent=walker.currentNode.textContent.replaceAll('grp_alps:p_7f3a',p.id).replaceAll('LINK-ALPS-01',p.link?.id||'Not started');text('#participant-id',p.id);}
 action('#confirm-guest',()=>join());action('#consent-back',()=>nav('join'));action('#consent-account',()=>nav('account'));action('#account-back',()=>nav('consent'));action('#account-join',()=>{if(!entryVerified()){entry('account');return;}join('account_backed');});
 if(page==='account')notice('Entry and binding use explicit local fixtures. Joining with an account requires the verified Entry handoff and a complete binding/readback fixture; no real authentication occurs.');
 action('#group-home,#linked-home',()=>openGroup());action('#upgrade,#no-effect-retry,#failed-retry,#retry-link',()=>{if(['pending','unknown','prepared'].includes(p.link?.status)){nav({pending:'pending',unknown:'unknown',prepared:'link'}[p.link.status]);return;}commit({type:'link',actor:p.id,linkId:crypto.randomUUID()});nav('link');});action('#simulate-recovery',()=>{revokeFixture(p.id);nav('recovery');});
 const result=r=>{if(r==='matched'&&!entryVerified()){entry('link');return;}commit({type:'link-result',actor:p.id,linkId:p.link.id,result:r,evidence:r==='linked'?{accountProof:true,activation:true,durableBinding:true,readback:true}:undefined},'prototype-fixture');nav({matched:'pending',unknown:'unknown',linked:'linked','no-effect':'no-effect',mismatch:'mismatch',cancelled:'cancelled','known-pre-effect-failed':'failed'}[r]);};
 action('#link-match',()=>result('matched'));action('#link-mismatch',()=>result('mismatch'));action('#link-cancel',()=>result('cancelled'));action('#link-timeout',()=>result('unknown'));action('#link-known-fail',()=>result('known-pre-effect-failed'));action('#reconcile-link-no-effect',()=>result('no-effect'));action('#link-readback-success,#reconcile-link-success',()=>result('linked'));action('#no-effect-guest,#keep-guest,#cancelled-back,#failed-back,#link-back',()=>nav('member'));
 action('#recovery-done',()=>{if(!p)fail('PARTICIPANT','Recover the participant associated with your invitation.');const next=repo.commit({type:'rotate',actor:p.id,operationId:crypto.randomUUID()},'prototype-fixture');grantFixture(next,p.id);nav('member');});
 if(page==='recovery'){if(p)text('.notice',`Participant ${p.id} is preserved. Saved labels grant no write authority. This button explicitly simulates a current participant-controlled proof and rotates its version; it does not select a real authenticator.`);else{text('h1','Reopen your invitation.');text('.notice','You have not joined. No ledger or private account data is available.');const actions=$('.actions');actions.replaceChildren(button('View invitation',()=>nav('join',{invite:sessionStorage.getItem('chopdot.membership.invite')||''})));}}
 if(p){const actions=$('.actions');if(actions&&!['recovery','consent','account'].includes(page))actions.append(button('Recover current proof (prototype)',()=>{revokeFixture(p.id);nav('recovery');},'link'));}
}
function toolbar(){const bar=document.querySelector('#fixtures');if(!fixtureMode)return;bar.hidden=false;bar.replaceChildren(el('b','','Local prototype fixtures · no server or real credentials'));for(const [label,key]of [['Offline','offline'],['Create fails','failCreate']]){const l=el('label'),b=el('input');b.type='checkbox';b.checked=!!s.membership.environment[key];b.onchange=()=>{repo.fixture({[key]:b.checked});render();};l.append(b,document.createTextNode(label));bar.append(l);}if(currentActor()==='self'&&route.invite){const i=s.membership.invitations.find(i=>i.id===route.invite&&i.status==='pending');if(i)bar.append(button('Expire pending invite',()=>{commit({type:'expire',actor:'self',inviteId:i.id},'prototype-fixture');render();},''));}bar.append(button('Inviter session',()=>{actor('self');nav(s.group?'invite':'entry',{invite:''});},''),button('New group',()=>{actor('self');nav('entry',{invite:''});},''));const h=bar.getBoundingClientRect().height;document.body.classList.add('fixture-mode');document.documentElement.style.setProperty('--fixture-height',h+'px');}
function render(){try{s=repo.read();route=Object.fromEntries(new URLSearchParams(location.hash.slice(1)));route.page||='entry';if(parent!==window)parent.postMessage({type:'chopdot-create-join-route',hash:location.hash},location.origin);const page=route.page;if(['entry','currency','advanced-currency','offline','error','savings'].includes(page))creation(page);else if(page==='success')success();else if(['invite','share','add-person','person-added','invite-sent','invite-done'].includes(page))invitation(page);else if(['join','not-now','closed','expired','already'].includes(page))recipient(page);else c1(page);toolbar();}catch(e){app.replaceChildren();screen=el('main');app.append(screen);screen.append(el('h1','','Continue through the approved entry'),el('p','cj-note cj-error',e.message),button('Sign in through Entry',()=>entry('invite')),button('Back',()=>history.back()));toolbar();}}
window.addEventListener('hashchange',render);render();window.ChopDotCreateJoin={ready:true};
