// Explicit local precondition fixture, held in memory. This is NOT an authenticator.
// Reload/restore never derives executable authority from saved participant labels.
import {member,membershipActive,fail} from './model.js';
const grants=new Map(),used=new Set(),minted=new Map();
const host=()=>typeof window!=='undefined'&&window.parent!==window?window.parent:globalThis;
function runtime(){const h=host();return h.ChopDotParticipantFixture||(h.ChopDotParticipantFixture={grants,used,minted});}
const digest=c=>JSON.stringify(Object.fromEntries(Object.entries(c).filter(([k])=>k!=='participantProof')));
const version=s=>JSON.stringify([s.membership?.sequence||0,s.gateB?.sequence||0,s.gateC?.sequence||0,s.expansion?.sequence||0]);
export function grantFixture(s,id){const p=member(s,id);if(!p||!membershipActive(s,id,p.groupId))fail('PARTICIPANT','Recover the existing participant.');runtime().grants.set(id,{groupId:p.groupId,capabilityVersion:p.capabilityVersion,policyVersion:p.policyVersion});}
export function revokeFixture(id){runtime().grants.delete(id);}
export function currentActor(){if(typeof sessionStorage==='undefined')return 'self';return sessionStorage.getItem('chopdot.membership.actor')||'self';}
export function signFixture(s,c){if(typeof sessionStorage!=='undefined'&&currentActor()!=='self'&&currentActor()!==c.actor)fail('GUEST_PROOF','This command belongs to a different participant session.');const p=member(s,c.actor);if(p&&!membershipActive(s,c.actor,p.groupId))fail('ACCESS','This group membership is no longer active.');if(!p)return c;if(typeof sessionStorage!=='undefined'&&currentActor()!==p.id)fail('GUEST_PROOF','The organizer cannot act as this participant.');const a=runtime().grants.get(p.id);if(!a)fail('GUEST_PROOF','Current proof is unavailable. Recover your existing participant explicitly.');const q={group_id:p.groupId,participant_id:p.id,capability_id:p.id+':local-fixture',capability_version:a.capabilityVersion,policy_version:a.policyVersion,command_id:c.operationId,state_version:version(s),scope_digest:p.groupId,payload_digest:digest(c),nonce:crypto.randomUUID(),proof_ref:'explicit-local-precondition-fixture'};runtime().minted.set(q.nonce,JSON.stringify(q));return {...c,participantProof:q};}
export function verifyFixture(s,c,p=member(s,c.actor)){
 const a=runtime().grants.get(c.actor),q=c.participantProof;if(!p||!a||!q||!membershipActive(s,p.id,p.groupId))return false;
 return runtime().minted.get(q.nonce)===JSON.stringify(q)&&q.group_id===p.groupId&&q.participant_id===p.id&&q.capability_version===p.capabilityVersion&&a.capabilityVersion===p.capabilityVersion&&q.policy_version===p.policyVersion&&a.policyVersion===p.policyVersion&&q.command_id===c.operationId&&q.state_version===version(s)&&q.scope_digest===p.groupId&&q.payload_digest===digest(c)&&q.capability_id===p.id+':local-fixture'&&q.proof_ref==='explicit-local-precondition-fixture'&&typeof q.nonce==='string'&&!runtime().used.has(q.nonce);
}
export function consumeFixture(c){if(c.participantProof){runtime().used.add(c.participantProof.nonce);runtime().minted.delete(c.participantProof.nonce);}}
export function assertParticipantCommand(s,c){if(typeof sessionStorage!=='undefined'&&currentActor()!=='self'&&currentActor()!==c.actor)fail('GUEST_PROOF','This command belongs to a different participant session.');const p=member(s,c.actor);if(!membershipActive(s,c.actor,p?.groupId||s.group?.id))fail('ACCESS','This group membership is no longer active.');if(!p)return;if(p.groupId!==s.group?.id||!verifyFixture(s,c,p))fail('GUEST_PROOF','Current group-scoped participant proof is required. Recover the existing participant.');if(p.identity!=='linked'&&!['create','edit'].includes(c.type))fail('ACCOUNT','This action requires an account bound to this participant. Guest expense and split input remain available.');}
export function canRead(s,area='group'){const actor=currentActor();if(actor==='visitor')return false;if(actor==='self')return area==='account'||membershipActive(s,actor);const p=member(s,actor);return !!p&&membershipActive(s,actor,p.groupId)&&p.groupId===s.group?.id&&area!=='account';}
export function routeParticipant(s,area='group'){if(canRead(s,area))return true;const url='../create-join/index.html#page=recovery';if(typeof location!=='undefined')location.replace(url);return false;}
