import '../gate-b/browser-launch.mjs';import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';import {serve} from '../gate-b/test-server.mjs';
import {upgrade,transition,newDraft} from '../gate-b/model.js';import {upgrade as account} from '../gate-d/model.js';
const out=process.env.EVIDENCE_DIR||'/tmp/chopdot-create-join-browser';mkdirSync(out,{recursive:true});const host=await serve(process.env.PREVIEW_ROOT),browser=await chromium.launch({headless:true});
const report={status:'RUNNING',browser:browser.version(),checks:[],consoleErrors:[],screenshots:[],scope:'J03/J04 actual UI, local participant proof and external binding fixtures; no real auth, remote invitations or settlement execution'};let page,context;
const core=JSON.parse(readFileSync(new URL('../gate-b/contract/semantic-core.json',import.meta.url)));
let seed=upgrade({group:{id:'old',name:'Accepted existing group',currency:'CHF'},people:[{id:'alex',name:'Alex'}],expenses:[],accountCreated:true});const d={...newDraft(seed),amountText:'12.00',description:'Accepted original dinner'};seed=account(transition(seed,{type:'create',id:d.id,operationId:d.operationId,actor:'self',draft:d},core));
const f=()=>page.frameLocator('#product-frame'),state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest'))),check=(id,fn)=>{fn();report.checks.push({id,status:'PASS'});};
const wait=id=>f().locator(`[data-golden="${id}"]`).waitFor();const b=name=>f().getByRole('button',{name,exact:true}).click();const link=name=>f().getByRole('link',{name,exact:true}).first().click();const shot=async name=>{const path=`${out}/${name}.png`;await page.screenshot({path});report.screenshots.push(path);};
const cj=async (hash='page=entry')=>{await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/index.html?fixtures=1&createJoin=${encodeURIComponent(hash)}`);await page.waitForFunction(()=>window.ChopDotPreviewV2);await f().locator('#app>*').waitFor();};
async function entry(){await f().getByLabel('Email',{exact:true}).fill('dev@example.com');await b('Send code');await f().getByLabel('6-digit code').fill('123456');await b('Continue');await b('Open ChopDot');}
try{
 for(const width of [393,430]){
 context=await browser.newContext({viewport:{width,height:width===393?852:890}});page=await context.newPage();page.on('pageerror',e=>report.consoleErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});await context.addInitScript(s=>{if(!localStorage.getItem('chopdot.preview-v2.guest'))localStorage.setItem('chopdot.preview-v2.guest',JSON.stringify(s));},seed);
 await cj();await wait('entry');await f().getByLabel('Group name').fill('Community trip');await f().locator('[href="#currency"]').click();await wait('currency');await f().locator('.choice').filter({hasText:'EUR'}).click();await wait('entry');await page.reload();await wait('entry');const retainedName=await f().getByLabel('Group name').inputValue();check(`CJ-B01-${width}-draft-reload`,()=>assert.equal(retainedName,'Community trip'));await f().getByRole('checkbox',{name:'Create fails',exact:true}).check();await link('Create group');await wait('error');let s=await state();check(`CJ-B02-${width}-failure-preserves-accepted`,()=>{assert.equal(s.group.id,'old');assert.deepEqual(s.expenses,seed.expenses);});await f().getByRole('checkbox',{name:'Create fails',exact:true}).uncheck();await link('Try again');await wait('success-eur');s=await state();const groupId=s.group.id;check(`CJ-B03-${width}-unique-group-history`,()=>{assert.notEqual(groupId,'old');assert.equal(s.groups.length,2);assert.deepEqual(s.expenses,seed.expenses);assert.equal(s.people.length,1);});await shot(`created-${width}`);
 await link('Invite people');await wait('invite');await f().locator('[href="#add-person"]').click();await wait('add-person');await f().getByLabel('Invitee name').fill('Sam');await f().locator('[href="#person-added"]').click();await wait('person-added');s=await state();const invite=s.membership.invitations.at(-1);check(`CJ-B04-${width}-pending-not-member`,()=>{assert.equal(s.people.length,1);assert.equal(invite.status,'pending');});await shot(`pending-${width}`);
 await b('View invite as recipient (prototype)');await wait('join');await link('Not now');await wait('not-now');await link('View invite');await wait('join');s=await state();check(`CJ-B05-${width}-not-now-no-membership`,()=>assert.equal(s.people.length,1));assert.ok(!(await f().locator('#app').innerText()).includes('Accepted original dinner'));await shot(`prejoin-${width}`);
 await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-b/index.html#page=group`);await page.waitForURL(/create-join\/index/);await page.getByText('Reopen your invitation.',{exact:true}).waitFor();check(`CJ-B06-${width}-direct-private-route-denied`,()=>assert.match(page.url(),/page=recovery/));
 await cj('page=join&invite='+invite.id);await wait('join');await link('Join group');await wait('consent');s=await state();check(`CJ-B07-${width}-consent-before-identity`,()=>assert.equal(s.people.length,1));await b('Join group as guest');await wait('joined');s=await state();const participant=s.people.at(-1).id;check(`CJ-B08-${width}-durable-scoped-identity`,()=>{assert.ok(participant.startsWith(groupId+':p_'));assert.equal(s.people.at(-1).identity,'guest');assert.deepEqual(s.expenses,seed.expenses);});await shot(`guest-joined-${width}`);
 await b('Go to group');await wait('active');await link('Add expense');await wait('entry');await f().getByLabel('Amount',{exact:true}).fill('10.01');await f().getByLabel('Description',{exact:true}).fill('Guest shared lunch');await f().locator('.app-footer .primary').click();await wait('success');s=await state();const e=s.expenses.at(-1);check(`CJ-B09-${width}-guest-expense-canonical`,()=>{assert.equal(e.ownerId,participant);assert.equal(e.groupId,groupId);assert.equal(e.money.minorUnits,'1001');assert.deepEqual(new Set(e.participantIds),new Set(['self',participant]));assert.equal(e.allocation.allocations.reduce((a,x)=>a+BigInt(x.amount.minorUnits),0n),1001n);});await link('Back to group');await wait('active');await shot(`group-refresh-${width}`);
 await f().locator('[href="#members-handoff"]').click();await link('Your membership');await wait('joined');await page.reload();await wait('joined');await b('Link an account');await f().getByRole('alert').filter({hasText:'Current proof'}).waitFor();const proofAlert=await f().getByRole('alert').innerText();check(`CJ-B10-${width}-reload-does-not-restore-write-authority`,()=>assert.match(proofAlert,/Current proof/));await b('Recover current proof (prototype)');await wait('recovery');await b('Continue after authority check');await wait('joined');s=await state();check(`CJ-B11-${width}-recovery-same-identity`,()=>{assert.equal(s.people.at(-1).id,participant);assert.equal(s.people.at(-1).capabilityVersion,2);assert.equal(s.people.length,2);assert.deepEqual(s.expenses.at(-1),e);});
 await b('Link an account');await wait('link');await b('Use matching account proof');await entry();await wait('link');await b('Use matching account proof');await wait('link-pending');s=await state();const linkId=s.people.at(-1).link.id;check(`CJ-B12-${width}-entry-not-binding-completion`,()=>{assert.equal(s.people.at(-1).identity,'guest');assert.equal(s.people.at(-1).link.status,'pending');});await b('Simulate timeout / unknown result');await wait('link-unknown');await shot(`link-unknown-${width}`);await page.reload();await wait('link-unknown');await b('Readback: binding committed');await f().getByRole('alert').waitFor();await b('Recover current proof (prototype)');await wait('recovery');await b('Continue after authority check');await wait('joined');await b('Link an account');await wait('link-unknown');await b('Readback: no effect');await wait('link-no-effect');s=await state();check(`CJ-B13-${width}-same-link-readback-no-effect`,()=>{assert.equal(s.people.at(-1).link.id,linkId);assert.equal(s.people.at(-1).link.status,'no-effect');assert.equal(s.people.at(-1).identity,'guest');});
 await b('Start a new link operation');await wait('link');await b('Use matching account proof');await entry();await wait('link');await b('Use matching account proof');await wait('link-pending');await b('Simulate verified durable binding');await wait('linked');s=await state();check(`CJ-B14-${width}-binding-preserves-ledger`,()=>{assert.equal(s.people.at(-1).identity,'linked');assert.equal(s.people.at(-1).id,participant);assert.deepEqual(s.expenses.at(-1),e);assert.equal(s.people.length,2);});await shot(`linked-${width}`);
 const overflow=await f().locator('html').evaluate(n=>n.scrollWidth>innerWidth);check(`CJ-B15-${width}-no-horizontal-overflow`,()=>assert.equal(overflow,false));await context.close();
 }
 check('CJ-B16-browser-health',()=>assert.deepEqual(report.consoleErrors,[]));report.status='PASS';
}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;if(page)await shot('failure').catch(()=>{});console.error(e);}finally{writeFileSync(`${out}/results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,error:report.error}));await browser.close();await host.close();}
