import '../gate-b/browser-launch.mjs';import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {serve} from '../gate-b/test-server.mjs';import {transition,upgrade} from './model.js';import {upgrade as accountUpgrade} from '../gate-d/model.js';
const out=process.env.EVIDENCE_DIR||'/tmp/chopdot-create-join-recovery';mkdirSync(out,{recursive:true});const host=await serve(process.env.PREVIEW_ROOT),browser=await chromium.launch({headless:true});const report={status:'RUNNING',checks:[],consoleErrors:[],screenshots:[],scope:'Fresh isolated browser contexts; known external/precondition records seeded explicitly, all subsequent operations use visible controls.'};let page,context;
const c=(type,x={})=>({type,actor:'self',operationId:crypto.randomUUID(),...x});const base=()=>upgrade(accountUpgrade({group:{id:'g',name:'Family trip',currency:'CHF',membershipManaged:true},groups:[{id:'g',name:'Family trip',currency:'CHF',membershipManaged:true}],people:[],expenses:[],accountCreated:true}));const invite=()=>transition(base(),c('invite',{id:'i',name:'Sam'}));const joined=()=>transition(invite(),c('join',{actor:'visitor',inviteId:'i',consent:true,participantId:'g:p_sam',identity:'guest'}));
const f=()=>page.frameLocator('#product-frame'),wait=id=>f().locator(`[data-golden="${id}"]`).waitFor(),b=name=>f().getByRole('button',{name,exact:true}).click(),link=name=>f().getByRole('link',{name,exact:true}).first().click(),state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest'))),check=(id,fn)=>{fn();report.checks.push({id,status:'PASS'});};
async function scene(seed,actor='self',hash='page=entry'){context=await browser.newContext({viewport:{width:393,height:852}});page=await context.newPage();page.on('pageerror',e=>report.consoleErrors.push(e.message));await context.addInitScript(({s,a})=>{if(!localStorage.getItem('chopdot.preview-v2.guest')){localStorage.setItem('chopdot.preview-v2.guest',JSON.stringify(s));sessionStorage.setItem('chopdot.membership.actor',a);}}, {s:seed,a:actor});await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/index.html?fixtures=1&createJoin=${encodeURIComponent(hash)}`);await f().locator('#app>*').waitFor();}
async function entry(){await f().getByLabel('Email',{exact:true}).fill('dev@example.com');await b('Send code');await f().getByLabel('6-digit code').fill('123456');await b('Continue');await b('Open ChopDot');}
async function shot(n){const path=`${out}/${n}.png`;await page.screenshot({path});report.screenshots.push(path);}
try{
 await scene(base());await f().getByLabel('Group name').fill('Offline draft');await f().getByRole('checkbox',{name:'Offline',exact:true}).check();await link('Create group');await wait('offline');await link('Save on this device');await wait('success');let s=await state();check('CJ-R01-offline-local-create-explicit',()=>{assert.equal(s.group.localOnly,true);assert.equal(s.group.shared,false);assert.equal(s.groups.length,2);});await shot('offline-created');await context.close();
 await scene(invite(),'visitor','page=join&invite=i');await f().getByRole('checkbox',{name:'Offline',exact:true}).check();await wait('offline');assert.ok((await f().locator('#app').innerText()).includes('Join when you’re back online.'));s=await state();check('CJ-R02-offline-invite-no-participant',()=>assert.equal(s.people.length,0));await shot('offline-invite');await context.close();
 await scene(invite(),'self','page=invite&invite=i');await b('Expire pending invite');await b('View invite as recipient (prototype)');await wait('expired');s=await state();check('CJ-R03-expired-precondition-no-membership',()=>{assert.equal(s.membership.invitations[0].status,'expired');assert.equal(s.people.length,0);});await shot('expired');await context.close();
 for(const pageName of ['linked','pending','unknown']){await scene(joined(),'g:p_sam','page='+pageName+'&invite=i');await wait('joined');s=await state();check('CJ-R04-'+pageName+'-route-cannot-invent-result',()=>assert.equal(s.people[0].identity,'guest'));await context.close();}
 for(const result of ['mismatch','cancelled']){await scene(joined(),'g:p_sam','page=recovery&invite=i');await b('Continue after authority check');await wait('joined');await b('Link an account');await wait('link');await b(result==='mismatch'?'Simulate mismatch':'Cancel before effect');await wait(result==='mismatch'?'unresolved':'link-cancelled');s=await state();check('CJ-R05-'+result+'-preserves-participant',()=>{assert.equal(s.people[0].id,'g:p_sam');assert.equal(s.people[0].identity,'guest');assert.equal(s.people.length,1);assert.equal(s.people[0].link.status,result);});await shot(result);await context.close();}
 const pending=joined();pending.people[0].link={id:'fixed-link',participantId:'g:p_sam',status:'pending'};await scene(pending,'g:p_sam','page=recovery&invite=i');await b('Continue after authority check');await b('Link an account');await wait('link-pending');await b('Simulate proven pre-effect failure');await wait('link-failed');s=await state();check('CJ-R06-pre-effect-distinct-from-readback',()=>assert.equal(s.people[0].link.status,'known-pre-effect-failed'));assert.ok(!(await f().locator('#app').innerText()).includes('Authoritative readback proved'));await shot('known-pre-effect-failure');await context.close();
 const changed=joined();changed.groups.push({id:'other',name:'Another group',currency:'USD'});changed.group=changed.groups.at(-1);await scene(changed,'g:p_sam','page=recovery&invite=i');await b('Continue after authority check');await wait('joined');await b('Go to group');await wait('active');s=await state();check('CJ-R07-reopen-reselects-existing-group',()=>{assert.equal(s.group.id,'g');assert.equal(s.people[0].id,'g:p_sam');assert.equal(s.people.length,1);});await context.close();
 await scene(changed,'g:p_sam','page=join&invite=i');await wait('already');await link('Open group');await wait('active');s=await state();check('CJ-R07b-already-joined-reselects-without-new-proof',()=>{assert.equal(s.group.id,'g');assert.equal(s.people[0].capabilityVersion,1);assert.equal(s.people.length,1);assert.equal(s.membership.sequence,changed.membership.sequence);});await context.close();
 await scene(invite(),'visitor','page=account&invite=i');await b('Join with account');await entry();await wait('account');s=await state();check('CJ-R08-entry-alone-does-not-join',()=>assert.equal(s.people.length,0));await b('Join with account');await wait('linked');s=await state();check('CJ-R08-account-entry-does-not-join-before-consent-binding',()=>{assert.equal(s.people.length,1);assert.equal(s.people[0].identity,'linked');assert.equal(s.membership.invitations[0].status,'joined');});await shot('account-join');await context.close();
 await scene(joined(),'g:p_sam','page=join&invite=i');await wait('already');await link('Open group');await wait('active');s=await state();check('CJ-R09-already-joined-reopens-same-member',()=>assert.equal((s.people||[]).length,1));await context.close();
 const multi=joined();multi.groups.push({id:'next',name:'Next group',currency:'EUR',membershipManaged:true});multi.membership.invitations.push({id:'next-invite',groupId:'next',name:'Sam',inviterName:'Owner',status:'pending',redemptions:[]});await scene(multi,'g:p_sam','page=join&invite=next-invite');await link('Join group');await b('Join group as guest');await wait('joined');s=await state();check('CJ-R10-next-group-distinct-no-name-merge',()=>{assert.equal(s.people.length,2);assert.equal(s.people[0].id,'g:p_sam');assert.ok(s.people[1].id.startsWith('next:p_'));assert.equal(s.group.id,'next');});await context.close();
 check('CJ-R11-browser-health',()=>assert.deepEqual(report.consoleErrors,[]));report.status='PASS';
}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;console.error(e);await shot('failure').catch(()=>{});}finally{writeFileSync(`${out}/results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,error:report.error}));await browser.close();await host.close();}
