import '../gate-b/browser-launch.mjs';
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { serve } from '../gate-b/test-server.mjs';
const root=process.env.PREVIEW_ROOT||resolve(new URL('../../..',import.meta.url).pathname);
const out=process.env.EVIDENCE_DIR||'/tmp/chopdot-gate-c-browser';mkdirSync(out,{recursive:true});
const host=await serve(root),browser=await chromium.launch({headless:true});
const report={status:'RUNNING',browser:browser.version(),reason:'Browser plugin not available; existing Playwright runtime used',flow:'Position → group/person scope → full/partial payment → simulated receipt → updated balances and record',checks:[],consoleErrors:[],screenshots:[]};
const check=(id,fn)=>{fn();report.checks.push({id,status:'PASS'});};
let page;
const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest')));
const pmt=async()=> (await data()).gateC.payments.at(-1);
const expectState=async value=>{await page.waitForFunction(v=>document.querySelector('#app>.screen')?.dataset.paymentState===v,value);};
const click=async(label)=>{await page.getByRole('link',{name:label,exact:true}).click();};
async function scene(name,width=393){const context=await browser.newContext({viewport:{width,height:852}});page=await context.newPage();page.on('pageerror',e=>report.consoleErrors.push({scene:name,error:e.message}));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({scene:name,error:m.text()});});await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=position`);await page.getByRole('button',{name:'Add Golden example',exact:true}).click();await page.locator('.person-row').filter({hasText:'Jeanine'}).waitFor();check(name+'-page-identity',()=>assert.match(page.url(),/gate-c\/index.html/));return context;}
async function person(){await page.locator('.person-row').filter({hasText:'Jeanine'}).click();await click('Settle CHF 54.30');}
async function prepareStart(){await click('Continue');await expectState('prepared');await click('Open TWINT');await expectState('started');await click('Return to ChopDot');}
async function receive(amount){await click('Yes, I sent it');await expectState('sent');await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-jeanine');await page.getByRole('link',{name:'Yes, it arrived',exact:true}).waitFor();if(amount){await click('Something’s wrong');await page.getByRole('textbox',{name:'Amount received'}).fill(amount);await click('Confirm received amount');}else await click('Yes, it arrived');await expectState('received');}
async function shot(name){const path=`${out}/${name}.png`;await page.screenshot({path,fullPage:false});report.screenshots.push(path);}
try {
 let context=await scene('group-full');
 await click('Groups');await page.locator('.group-list .gc-row').filter({hasText:'Apartment'}).click();await page.locator('.gc-row').filter({hasText:'Jeanine'}).click();await click('Settle CHF 74.30');await prepareStart();
 await click('Yes, I sent it');await expectState('sent');const before=await data();await click('View confirmation status');await click('Refresh status');check('payer-refresh-is-pure',()=>{});assert.deepEqual(await data(),before);
 const id=(await pmt()).id;await page.reload();await expectState('sent');check('reload-retains-payment',()=>assert.equal(before.gateC.payments.at(-1).id,id));
 await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-jeanine');await click('Not yet');await expectState('not_received');assert.equal((await pmt()).confirmed,'0');report.checks.push({id:'recipient-not-yet',status:'PASS'});
 await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=payment&id=${id}`);await click('Yes, it arrived');await expectState('received');await page.getByRole('button',{name:'Accept exact closure'}).click();await expectState('closed');
 check('group-full-scope',()=>assert.deepEqual(before.gateC.payments.at(-1).groupIds,['gc-apartment']));
 await click('Back to balances');await click('Groups');let groupRow=page.locator('.group-list .gc-row').filter({hasText:'Apartment'});
 assert.match(await groupRow.innerText(),/0 open balances[\s\S]*You’re square/);assert.doesNotMatch(await groupRow.innerText(),/(Owe|Owed) CHF 0\.00/);report.checks.push({id:'cleared-group-row-is-square',status:'PASS'});
 await page.getByRole('combobox',{name:'Test person'}).selectOption('self');await click('Groups');groupRow=page.locator('.group-list .gc-row').filter({hasText:'Apartment'});
 assert.match(await groupRow.innerText(),/1 open balances[\s\S]*Owed CHF 20\.00/);assert.doesNotMatch(await groupRow.innerText(),/(Owe|Owed) CHF 0\.00/);report.checks.push({id:'mixed-group-row-omits-cleared-counterparty',status:'PASS'});
 await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-jeanine');await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=payment&id=${id}`);await expectState('closed');
 await click('View payment record');await page.locator('.record-row,.gc-row').filter({hasText:'7430'}).count();assert.match(await page.locator('#app').innerText(),/CHF 74.30/);report.checks.push({id:'saved-record-canonical-amount',status:'PASS'});await shot('group-full-record');
 await click('Done');await click('Payment details');await page.locator('.gc-row').filter({hasText:'Apartment supplies'}).click();await page.waitForURL(/gate-b\/index/);await page.getByRole('combobox',{name:'Test person'}).selectOption('self');await page.locator('#app>.screen[data-golden="active"]').waitFor();assert.match(await page.locator('.position-value').innerText(),/20.00/);report.checks.push({id:'group-home-shared-state',status:'PASS'});await context.close();

 context=await scene('person-full',430);await person();await prepareStart();await receive();const received=await data();assert.equal((await pmt()).applications.length,0);report.checks.push({id:'received-not-closed',status:'PASS'});await page.getByRole('button',{name:'Accept exact closure'}).click();await expectState('closed');const closed=await pmt();check('person-full-two-source-applications',()=>{assert.equal(closed.sources.length,2);assert.equal(closed.applications.reduce((n,a)=>n+BigInt(a.minor),0n),5430n);});await shot('person-full-complete');await context.close();

 context=await scene('partial-offset');await person();await page.locator('[href="#amount"]').click();await page.getByRole('textbox',{name:'Payment amount',exact:true}).fill('20.00');await click('Use CHF 20.00');assert.match(await page.locator('#app').innerText(),/CHF 34.30/);await prepareStart();await receive('10.00');await page.getByRole('button',{name:'Accept exact closure'}).click();await expectState('partial');const partial=await pmt();check('lower-receipt-confirmed-only',()=>{assert.equal(partial.confirmed,'1000');assert.equal(partial.applications.reduce((n,a)=>n+BigInt(a.minor),0n),1000n);});await shot('partial-complete');
 await page.getByRole('combobox',{name:'Test person'}).selectOption('self');await click('View remaining balance');await click('Settle CHF 44.30');await click('Continue');await expectState('prepared');check('new-remainder-payment-linked',()=>{});assert.deepEqual((await pmt()).remainderOf,[partial.id]);await context.close();

 context=await scene('partial-keep-offset');await person();await page.locator('[href="#amount"]').click();await page.getByRole('textbox',{name:'Payment amount',exact:true}).fill('20.00');await page.getByRole('checkbox',{name:'Apply included offsets'}).uncheck();await click('Use CHF 20.00');await prepareStart();await receive();await page.getByRole('button',{name:'Accept exact closure'}).click();await expectState('partial');const kept=await pmt();check('keep-credit-choice-preserved',()=>assert.equal(kept.applications.find(a=>a.sourceId.includes('ski-jeanine')).minor,'0'));await page.getByRole('button',{name:'Verify reversal'}).click();await expectState('reversed');assert.equal((await pmt()).retryEligible,false);report.checks.push({id:'verified-reversal-recorded',status:'PASS'});await context.close();

 context=await scene('recovery',1440);await person();await prepareStart();const original=await pmt();await page.getByRole('button',{name:'Simulate unknown result'}).click();await expectState('unknown');assert.equal(await page.getByRole('link',{name:'Review and retry',exact:true}).count(),0);report.checks.push({id:'unknown-has-no-retry-action',status:'PASS'});await click('Recover status');await expectState('recovering');await page.getByRole('button',{name:'Verify no execution'}).click();await expectState('failed');await click('Review and retry');await expectState('prepared');check('recovery-reuses-identity',()=>{});const retried=await pmt();assert.equal(retried.id,original.id);assert.equal(retried.attempt,2);assert.equal(retried.retryEligible,false);await shot('recovered-review');await context.close();

 context=await scene('wallet');await person();await page.locator('[href="#methods"]').click();await page.locator('.method-row').filter({has:page.locator('b',{hasText:/^Wallet$/})}).click();await click('Review wallet payment');await expectState('prepared');await click('Approve in wallet');await expectState('approval_waiting');await click('Return to ChopDot');assert.equal((await pmt()).confirmed,'0');report.checks.push({id:'wallet-request-not-authorization',status:'PASS'});await page.getByRole('button',{name:'Accept wallet submission'}).click();await expectState('submitted');await page.getByRole('button',{name:'Accept exact wallet receipt'}).click();await expectState('received');await page.getByRole('button',{name:'Accept exact closure'}).click();await expectState('closed');check('wallet-exact-result',()=>{});assert.equal((await pmt()).confirmation,'simulated-wallet-result');await click('View payment record');const saved=await data();await page.getByRole('checkbox',{name:'Record unavailable'}).check();await click('Refresh record');assert.equal((await pmt()).state,'closed');report.checks.push({id:'record-retrieval-does-not-undo-effect',status:'PASS'});await context.close();
 assert.deepEqual(report.consoleErrors,[]);report.checks.push({id:'console-health',status:'PASS'});report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;if(page&&!page.isClosed()){await shot('failure');writeFileSync(`${out}/failure-dom.txt`,await page.locator('body').innerText());}throw e;}
finally{writeFileSync(`${out}/results.json`,JSON.stringify(report,null,2));await browser.close();await host.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));}
