import '../gate-b/browser-launch.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {serve} from '../gate-b/test-server.mjs';
import {addGoldenExample} from './fixtures.js';
import {newDraft,transition as expenseTransition} from '../gate-b/model.js';
const core=JSON.parse(readFileSync(new URL('../gate-b/contract/semantic-core.json',import.meta.url)));
const root=process.env.PREVIEW_ROOT||resolve(new URL('../../..',import.meta.url).pathname),out=process.env.EVIDENCE_DIR||'/tmp/gate-c-recovery';mkdirSync(out,{recursive:true});
const host=await serve(root),browser=await chromium.launch({headless:true});
const report={status:'RUNNING',checks:[],errors:[],browser:browser.version(),scope:'Alternate methods, explicit source allocation, recovery controls, keyboard state and outer-host continuity'};
let page,context;
const pass=id=>report.checks.push({id,status:'PASS'});
const click=async n=>page.getByRole('link',{name:n,exact:true}).click();
const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest')));
const payment=async()=> (await data()).gateC.payments.at(-1);
const state=async s=>page.waitForFunction(v=>document.querySelector('#app>.screen')?.dataset.paymentState===v,s);
async function start(initial=addGoldenExample({},core),width=393){if(context)await context.close();context=await browser.newContext({viewport:{width,height:852},permissions:['clipboard-read','clipboard-write']});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.addInitScript(s=>{if(!localStorage.getItem('chopdot.preview-v2.guest'))localStorage.setItem('chopdot.preview-v2.guest',JSON.stringify(s));},initial);await page.goto(host.base+'/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=position');await page.locator('.person-row').first().waitFor();}
async function draft(other='Jeanine',amount='54.30'){await page.locator('.person-row').filter({hasText:other}).filter({hasText:'CHF'}).click();await click('Settle CHF '+amount);}
async function method(m){await page.locator('[href="#methods"]').click();await page.locator('.method-row').filter({has:page.locator('b',{hasText:new RegExp('^'+m+'$')})}).click();}
try{
 for(const [m,review,begin] of [['Bank transfer','Review transfer','Open bank app'],['Cash','Record a payment','Record as sent'],['PayPal','Review PayPal payment','Open PayPal']]){
  await start();await draft('Nina','30.00');await method(m);
  if(m==='Bank transfer'){await page.getByRole('link',{name:'Copy IBAN'}).click();await page.getByRole('status').filter({hasText:'Copied'}).waitFor();assert.match(await page.locator('#app').innerText(),/Copied/);assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'DEMO — NO BANK ACCOUNT');pass('bank-copy-demo-details');}
  await click(review);await state('prepared');const body=await page.locator('#app').innerText();assert.ok(!body.includes('CHF 54.30'));assert.ok(!body.includes('Jeanine'));pass('dynamic-'+m+'-recipient-amount');
  await click(begin);await click('Return to ChopDot');if(m!=='Cash')await click('Yes, I sent it');await state('sent');await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-nina');await click('Yes, it arrived');await state('received');await page.getByRole('button',{name:'Accept exact closure'}).click();await state('closed');assert.equal((await payment()).method,m);pass('complete-'+m);
 }
 await start();await page.locator('.person-row').filter({hasText:'Sam'}).filter({hasText:'EUR'}).click();await click('Settle €18.00');await page.locator('[href="#amount"]').click();assert.equal(await page.getByRole('link',{name:'CHF 20',exact:true}).count(),0);assert.equal(await page.getByRole('link',{name:'€20.00',exact:true}).getAttribute('aria-disabled'),'true');await page.getByRole('link',{name:'Half',exact:true}).click();assert.equal(await page.locator('.amount-chip.active').innerText(),'Half');assert.equal(await page.getByRole('textbox',{name:'Payment amount',exact:true}).inputValue(),'9.00');assert.equal(await page.locator('.amount-chip.active').filter({hasText:'Full'}).count(),0);await click('Use €9.00');await click('Continue');await state('prepared');assert.equal((await payment()).currency,'EUR');pass('EUR-shortcut-and-partial');

 let s=addGoldenExample({},core);s.group=s.groups.find(g=>g.id==='gc-zurich');const d={...newDraft(s,'gc-jeanine','extra-jeanine'),amountText:'74.30',description:'Additional supplies',date:'2026-10-03',payerId:'gc-jeanine',participantIds:['self','gc-jeanine'],method:'exact',exact:{self:'74.30','gc-jeanine':'0'}};
 s=expenseTransition(s,{type:'create',id:d.id,actor:'gc-jeanine',operationId:d.operationId,draft:d},core);
 await start(s);await draft('Jeanine','128.60');await page.locator('[href="#amount"]').click();await page.getByRole('textbox',{name:'Payment amount',exact:true}).fill('20.00');
 await page.getByRole('textbox',{name:'Pay toward Apartment supplies'}).fill('0.00');await page.getByRole('alert').filter({hasText:'add up'}).waitFor();assert.equal(await page.getByRole('link',{name:'Use CHF 20.00',exact:true}).getAttribute('aria-disabled'),'true');pass('invalid-allocation-preview-cleared');
 await page.getByRole('textbox',{name:'Pay toward Additional supplies'}).fill('20.00');const after=page.locator('section').filter({has:page.getByRole('heading',{name:'After this payment',exact:true})}).last();assert.equal((await after.innerText()).match(/CHF 54.30/g)?.length,2);pass('GC-REV-001-live-custom-allocation-preview');
 await page.screenshot({path:out+'/custom-allocation.png'});await click('Use CHF 20.00');await click('Continue');await state('prepared');await click('Open TWINT');await click('Return to ChopDot');await click('Yes, I sent it');await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-jeanine');await click('Payment details');await page.locator('[data-golden="receiver-breakdown"]').waitFor();const details=await page.locator('#app').innerText();assert.ok(!details.includes('You still owe'));assert.match(details,/Guest owes you/);assert.match(details,/Originally: You owe Guest/);pass('GC-REV-002-recipient-directions');
 await page.screenshot({path:out+'/recipient-details.png'});

 await start();await draft();await page.locator('[href="#breakdown"]').click();await page.getByRole('checkbox',{name:'Ski Trip · Ski passes'}).uncheck();await click('Use selected balances');assert.match(await page.locator('.amount-display').innerText(),/74.30/);await page.reload();assert.match(await page.locator('.amount-display').innerText(),/74.30/);pass('source-selection-reload-continuity');
 await page.getByRole('checkbox',{name:'Save failure',exact:true}).check();await click('Continue');assert.equal((await data()).gateC.payments.length,0);assert.match(await page.locator('[role=alert]').innerText(),/Could not save/);await page.getByRole('checkbox',{name:'Save failure',exact:true}).uncheck();await click('Continue');await state('prepared');pass('failed-prepare-retry-preserves-draft-identity');
 await page.getByRole('checkbox',{name:'Offline',exact:true}).check();await click('Open TWINT');assert.match(await page.locator('#app').innerText(),/offline/i);assert.equal((await payment()).state,'prepared');await page.getByRole('checkbox',{name:'Offline',exact:true}).uncheck();await click('Open TWINT');await click('Return to ChopDot');await page.getByRole('button',{name:'Simulate unknown result'}).click();await state('unknown');await click('Recover status');await state('recovering');
 await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-jeanine');await click('Yes, it arrived');await state('received');await page.getByRole('button',{name:'Accept exact closure'}).click();await state('closed');pass('GC-SEC-003-external-positive-recovery-browser');

 await start();await draft();await page.getByRole('checkbox',{name:'No method',exact:true}).check();await click('Continue');assert.match(await page.locator('#app').innerText(),/No payment details yet/);await click('Request payment details');assert.match(await page.locator('#app').innerText(),/No message has been sent/);assert.equal((await data()).gateC.payments.length,0);pass('no-method-explicit-request-boundary');

 for(const problem of ['wallet-connect','wallet-wrong','invalid-address','insufficient','fee-unavailable']){
  await start();await draft();await method('Wallet');await click('Review wallet payment');await state('prepared');await page.getByRole('combobox',{name:'Wallet precondition'}).selectOption(problem);await click('Approve in wallet');assert.equal((await payment()).state,'prepared');assert.equal(await page.locator('#app>.screen').getAttribute('data-golden'),problem);pass('wallet-precondition-'+problem);
 }
 for(const [control,expected] of [['Verify cancellation','cancelled'],['Verify expiry','expired']]){
  await start();await draft();await method('Wallet');await click('Review wallet payment');await click('Approve in wallet');await click('Return to ChopDot');await page.getByRole('button',{name:control}).click();await state(expected);assert.equal((await payment()).confirmed,'0');await click('Review and retry');await state('prepared');assert.equal((await payment()).attempt,2);pass('wallet-'+expected+'-safe-retry');
 }
 await start();await draft();await page.locator('[href="#amount"]').click();await page.getByRole('textbox',{name:'Payment amount',exact:true}).fill('20');const offset=page.getByRole('checkbox',{name:'Apply included offsets'});await offset.focus();await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Apply included offsets');const outline=await offset.evaluate(n=>getComputedStyle(n).outlineStyle);assert.notEqual(outline,'none');pass('keyboard-offset-focus-retained-visible');await click('Use CHF 20.00');
 // The outer host restores the exact inner payment route on reload.
 await page.goto(host.base+'/prototypes/integrated-product-preview-v2/index.html?fixtures=1&gateC=%23page%3Dsettle');const frame=page.frameLocator('#product-frame');await frame.getByRole('link',{name:'Continue',exact:true}).click();await frame.locator('[data-payment-state="prepared"]').waitFor();const initialId=(await data()).gateC.payments.at(-1).id;await page.waitForFunction(()=>new URL(location.href).searchParams.get('gateC')?.includes('page=payment'));await page.reload();await page.frameLocator('#product-frame').locator(`[data-payment-id="${initialId}"]`).waitFor();pass('outer-host-reload-restores-exact-payment');
 // A real J07 issue opened after sending blocks receipt without replacing payment identity.
 await start();await draft();await click('Continue');await state('prepared');await click('Open TWINT');await click('Return to ChopDot');await click('Yes, I sent it');await state('sent');const issuePayment=(await payment()).id;
 await click('Payment details');await page.locator('[data-golden="receiver-breakdown"]').waitFor();await page.locator('.gc-row').filter({hasText:'Apartment supplies'}).click();await page.waitForURL(/gate-b\/index/);await page.locator('[href="#review-handoff"]').first().click();await page.locator('[data-golden="already"]').waitFor();await page.locator('[href="#reasons"]').click();await page.locator('.reason').first().click();await page.getByLabel('Optional note').fill('Check before closing this payment.');await page.locator('#app .primary').click();await page.locator('[data-golden="issue-sent-share"]').waitFor();const issue=(await data()).expenses.find(e=>e.id==='gc-example-apartment-jeanine').issues.at(-1);
 await page.goto(host.base+`/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=payment&id=${issuePayment}`);await state('sent');await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-jeanine');await click('Yes, it arrived');await page.getByText('This payment needs attention.',{exact:true}).waitFor();assert.equal((await payment()).state,'sent');assert.equal((await payment()).confirmed,'0');pass('post-send-J07-issue-blocks-receipt');
 await page.getByRole('combobox',{name:'Test person'}).selectOption('self');await click('Payment details');await page.locator('[data-golden="receiver-breakdown"]').waitFor();await page.locator('.gc-row').filter({hasText:'Apartment supplies'}).click();await page.waitForURL(/gate-b\/index/);await page.locator('[href="#review-handoff"]').first().click();await page.locator('[data-golden="waiting-share"]').waitFor();await page.locator('[href="#withdraw"]').click();await page.locator('#app .primary').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest')).expenses.find(e=>e.id==='gc-example-apartment-jeanine').issues.at(-1).status!=='open');
 await page.goto(host.base+`/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=payment&id=${issuePayment}`);await state('sent');await page.getByRole('combobox',{name:'Test person'}).selectOption('gc-jeanine');await click('Yes, it arrived');await state('received');await page.getByRole('button',{name:'Accept exact closure'}).click();await state('closed');assert.equal((await payment()).id,issuePayment);assert.equal((await data()).expenses.find(e=>e.id==='gc-example-apartment-jeanine').issues.at(-1).id,issue.id);pass('issue-withdrawal-resumes-original-payment');
 assert.deepEqual(report.errors,[]);pass('console-health');report.status='PASS';
}catch(e){report.status='FAIL';report.failure=e.stack;if(page&&!page.isClosed()){await page.screenshot({path:out+'/failure.png'});writeFileSync(out+'/failure.txt',await page.locator('body').innerText());}throw e;}
finally{writeFileSync(out+'/results.json',JSON.stringify(report,null,2));await browser.close();await host.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out}));}
