const assert=require('node:assert/strict');const M=require('./model.cjs');let n=0;
const eq=(a,b)=>{assert.deepEqual(a,b);n++;};const ok=x=>{assert(x);n++;};
let s=M.create();eq(s.members.zurich.length,4);eq(M.owner(s),'dev');eq(M.routes.length,18);
s.person='jeanine';eq(M.balances(s,'jeanine','zurich'),{});eq(M.balances(s,'jeanine','all'),{CHF:-5430});eq(M.removalBlock(s),null);
const ledger=JSON.stringify(s.items);const c=M.requestRemoval(s);eq(c.person,'jeanine');eq(c.group,'zurich');eq(M.requestRemoval(s).id,c.id);eq(s.members.zurich.length,4);
eq(M.acceptRemoval(s,'wrong'),'stale');eq(M.acceptRemoval(s,c.id),'accepted');eq(M.acceptRemoval(s,c.id),'accepted');eq(s.members.zurich.length,3);eq(JSON.stringify(s.items),ledger);ok(s.members.apartment.includes('jeanine'));eq(M.balances(s,'jeanine','all'),{CHF:-5430});
s=M.create();s.person='marc';eq(M.removalBlock(s),'balance');eq(M.requestRemoval(s).blocked,'balance');eq(s.command,null);
s=M.create();s.person='dev';eq(M.removalBlock(s),'owner');s.person='jeanine';s.owners.zurich='marc';eq(M.removalBlock(s),'permission');s.online=false;eq(M.removalBlock(s),'offline');
s=M.create();s.person='jeanine';s.scope='all';const pay=M.resolveScope(s,'CHF');eq(pay.kind,'settle');eq(pay.amountMinor,5430);eq(pay.payer,'dev');eq(pay.recipient,'jeanine');eq(pay.sourceGroups,['apartment','ski']);eq(pay.sourceItems,['ja-apartment','ja-ski']);eq(pay.paymentMethod,'TWINT');eq(JSON.stringify(s.items),ledger);
s.person='sam';s.mixed=true;const cf=M.resolveScope(s,'CHF'),dt=M.resolveScope(s,'DOT');eq(cf.amountMinor,9110);eq(dt.amountMinor,2400000);eq(dt.currency,'DOT');eq(dt.sourceGroups,['hackathon']);eq(dt.payer,'sam');eq(dt.recipient,'dev');eq(dt.kind,'request');ok(!dt.sourceItems.includes('sam-zurich'));
s.person='luca';eq(M.resolveScope(s,'EUR').amountMinor,1800);eq(M.resolveScope(s,'CHF'),null);s.online=false;eq(M.resolveScope(s,'EUR'),null);
s=M.create();s.person='marc';s.issue=true;eq(M.resolveScope(s,'CHF'),null);eq(M.affected(s,'sam'),false);s.scope='ski';eq(M.resolveScope(s,'CHF').amountMinor,3000);s.scope='all';eq(M.resolveScope(s,'CHF'),null);
s=M.create();s.person='jeanine';s.privatePreference=true;eq(M.preference(s),null);s.privatePreference=false;eq(M.preference(s),'TWINT');
s=M.create();s.person='jeanine';let cmd=M.requestRemoval(s);s.command.status='unknown';eq(M.requestRemoval(s).id,cmd.id);eq(s.sequence,1);eq(s.members.zurich.length,4);s.command.status='recovering';eq(M.acceptRemoval(s,cmd.id),'accepted');eq(s.sequence,1);
s=M.create();s.person='jeanine';cmd=M.requestRemoval(s);s.version++;eq(M.acceptRemoval(s,cmd.id),'conflict');eq(s.members.zurich.length,4);
s=M.create();s.person='jeanine';cmd=M.requestRemoval(s);s.owners.zurich='marc';eq(M.acceptRemoval(s,cmd.id),'denied');eq(s.members.zurich.length,4);
s=M.create();s.person='jeanine';cmd=M.requestRemoval(s);s.items.push({id:'new',person:'jeanine',group:'zurich',currency:'CHF',minor:100});eq(M.acceptRemoval(s,cmd.id),'blocked');eq(s.members.zurich.length,4);
s=M.create();s.person='jeanine';cmd=M.requestRemoval(s);s.person='marc';eq(M.requestRemoval(s).blocked,'existing');eq(s.sequence,1);
s=M.create();s.query='JEAN';eq(M.directory(s),['jeanine']);s.query='zzzz';eq(M.directory(s),[]);eq(s.members.zurich.length,4);
s=M.create();s.access=false;eq(M.canView(s),false);s.scope='all';s.members.zurich=s.members.zurich.filter(p=>p!=='dev');eq(M.canView(s),true);ok(!M.visibleGroups(s,'jeanine').includes('zurich'));
console.log(JSON.stringify({ok:true,checks:n}));
