import type { GroupMoneyScenario } from '../types';

export const payoutInvestigationV1: GroupMoneyScenario = {
  id: 'payout-investigation-v1',
  title: 'P3 Payout — confirm gate',
  chapter: 'Summer trip · payout lab',
  skin: 'telegram',
  personas: {
    alex: { name: 'Alex', role: 'Organizer', color: '#2AABEE' },
    sam: { name: 'Sam', role: 'Member', color: '#53bdeb' },
    jordan: { name: 'Jordan', role: 'Payer', color: '#8696a0' },
  },
  steps: [
    {
      id: 'p-claim',
      beat: 'move',
      payoutSolutionId: 'P01',
      payoutMock: 'paid-confirm-flow',
      persona: 'jordan',
      message: 'Just Twinted you €40',
      chopdotAction: 'Jordan: /paid leg_8f2a · Alex: must /confirm — not auto.',
      stateExpectation: 'P01 L0: social rail + our confirm loop.',
    },
    {
      id: 'p-deeplink',
      beat: 'move',
      payoutSolutionId: 'P02',
      payoutMock: 'deep-link-pay',
      botReply: 'Pay Alex €40 (leg_8f2a)\n[Open Twint] · then Alex /confirm',
      chopdotAction: 'P02: prefilled deep link + legId in memo.',
      stateExpectation: 'Amount matches leg; no manual re-entry.',
    },
    {
      id: 'p-request',
      beat: 'move',
      payoutSolutionId: 'P03',
      systemNote: 'Fix on main: request-payment amounts',
      chopdotAction: 'Request payment must show real € — not zeroed (operator queue).',
      stateExpectation: 'P03 aids Move; broken today.',
    },
    {
      id: 'p-block',
      beat: 'end',
      payoutSolutionId: 'P01',
      payoutMock: 'close-blocked',
      persona: 'alex',
      message: '/close',
      botReply: '⛔ 1 open leg — Jordan → Alex €40 unconfirmed. /close when clear.',
      chopdotAction: 'Unavoidable: payout confirm gates History.',
      stateExpectation: 'Cannot skip confirm and still close.',
    },
    {
      id: 'p-psd2',
      beat: 'move',
      payoutSolutionId: 'P04',
      systemNote: 'L2 — EU bank initiate (defer)',
      chopdotAction: 'P04 PSD2 PI: bank redirect settle — G2 adapter, Tricount path.',
      stateExpectation: 'Score selected for L2; not v1 dinner splits.',
    },
    {
      id: 'p-reject',
      beat: 'move',
      payoutSolutionId: 'P20',
      systemNote: 'Hard reject — custody',
      chopdotAction: 'REJECT P20 escrow as core — G0 violation.',
      stateExpectation: 'Never hold group funds.',
    },
    {
      id: 'p-exit',
      beat: 'move',
      systemNote: 'P3 Payout exit proof',
      chopdotAction: 'Replay Jordan arc: claim → pay → confirm → openLegCount 0.',
      stateExpectation: 'Ready for P4 History close.',
    },
  ],
};
