import type { GroupMoneyScenario } from '../types';

export const tripChapterV1: GroupMoneyScenario = {
  id: 'trip-chapter-v1',
  title: 'Trip chapter — full loop',
  chapter: 'Friends trip (Airbnb + dinners)',
  skin: 'whatsapp',
  personas: {
    alex: { name: 'Alex', role: 'Organizer (you)', color: '#25D366' },
    sam: { name: 'Sam', role: 'Prompt payer', color: '#53bdeb' },
    jordan: { name: 'Jordan', role: 'Slow / claims paid early', color: '#8696a0' },
  },
  steps: [
    {
      id: '0-start',
      beat: 'catch',
      systemNote: 'Chapter starts in chat. Airbnb on Alex’s card.',
      chopdotAction: 'Create pot “Summer trip”, currency, add Sam + Jordan as members.',
      stateExpectation: 'Pot open. You are organizer.',
    },
    {
      id: '1-airbnb-chat',
      beat: 'catch',
      persona: 'alex',
      message: 'I put €480 on Airbnb — splitting 3 ways',
      chopdotAction: 'Add expense €480, paid by Alex, split 3 ways.',
      stateExpectation: 'Balances show Sam & Jordan owe Alex.',
    },
    {
      id: '2-link',
      beat: 'show',
      persona: 'alex',
      message: 'Track everything here 👇 [ChopDot link]',
      chopdotAction: 'Copy invite link → paste in lab chat mentally; open join as Sam in second browser if testing.',
      stateExpectation: 'Members can see same pot (Show begins).',
    },
    {
      id: '3-receipt',
      beat: 'catch',
      persona: 'sam',
      message: '[Photo: dinner receipt €120]',
      chopdotAction: 'Add expense €120, paid by Sam, split 3 ways (+ attach receipt if available).',
      stateExpectation: 'All three see updated balances — no Sheet re-type.',
    },
    {
      id: '4-venmo-claim',
      beat: 'show',
      persona: 'jordan',
      message: 'Sent you my share on Venmo already',
      chopdotAction: 'Do NOT mark chapter closed. Note: claimed in chat ≠ confirmed in pot.',
      stateExpectation: 'If Jordan marked paid but Alex not confirmed → still OPEN (core pain C).',
    },
    {
      id: '5-are-we-good',
      beat: 'show',
      persona: 'sam',
      message: 'We good?',
      chopdotAction: 'Open pot → answer honestly: can you see open items in one glance? (Target: “Are we good?” screen)',
      stateExpectation: 'Should show NOT good until all legs confirmed — not just net zero.',
    },
    {
      id: '6-request',
      beat: 'move',
      systemNote: 'Organizer unsticks without guilt-DM archaeology.',
      chopdotAction: 'Request payment from Jordan (real amount) OR settle-home for owed leg.',
      stateExpectation: 'Jordan gets context: amount + pot name.',
    },
    {
      id: '7-confirm',
      beat: 'move',
      persona: 'jordan',
      message: 'Ok checked — paid the rest',
      chopdotAction: 'Jordan: mark paid. Alex: confirm received (settlement confirmation flow).',
      stateExpectation: 'Leg moves marked_paid → receiver_confirmed. Open count drops.',
    },
    {
      id: '8-settle',
      beat: 'move',
      chopdotAction: 'Settle Up → review suggested transfers → complete any remaining legs.',
      stateExpectation: 'No silent “everyone owes zero” while confirmations missing.',
    },
    {
      id: '9-close',
      beat: 'end',
      persona: 'alex',
      message: 'Trip done — closing the books 🎉',
      chopdotAction: 'Closeout review → export JSON (optional onchain seal).',
      stateExpectation: 'Chapter artifact you would keep; next trip can start clean.',
    },
    {
      id: '10-reflect',
      beat: 'end',
      systemNote: 'Operator friction log — you are the evidence.',
      chopdotAction: 'Write: where did you still open WhatsApp/Sheet? Where did the loop hold?',
      stateExpectation: 'Honest Y/N: would you use this for your next chapter?',
    },
  ],
};

export const defaultScenario = tripChapterV1;
