import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),M=require('./model.cjs');const root=path.resolve(import.meta.dirname,'..');
const read=f=>fs.readFileSync(path.join(root,'source',f),'utf8');
const icon=(name)=>({back:'<path d="M15 18l-6-6 6-6"/>',chev:'<path d="M9 18l6-6-6-6"/>',group:'<path d="M3 7h18v12H3zM6 7V4h12v3M8 11h8"/>',trend:'<path d="M4 16l5-5 4 4 7-8"/><path d="M15 7h5v5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 8h.01"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4v-.2a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1z"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>',refresh:'<path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/>',home:'<path d="M3 11l9-8 9 8v10H3z"/><path d="M9 21v-6h6v6"/>',people:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M13.7 21a2 2 0 0 1-3.4 0"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',plus:'<path d="M12 5v14M5 12h14"/>',dot:'<circle cx="12" cy="12" r="8"/><path d="M8 12h8"/>',check:'<path d="M20 6L9 17l-5-5"/>'}[name]||'');
const svg=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icon(n)}</svg>`;
const nav=n=>svg(n).replace('<svg ','<svg class=\"nav-icon\" ');
const header=(title,sub='Insights')=>`<header class="j19-header"><a class="icon-btn" href="#home-preview" aria-label="Back">${svg('back')}</a><div class="j19-title"><b>${title}</b><span>${sub}</span></div><a class="demo-btn" href="#demo">Demo</a></header>`;
const tabs=`<footer class="app-footer"><nav class="tabbar"><a class="tab" href="#home-preview">${nav('home')}<span>Home</span></a><a class="tab" href="#handoff-group">${nav('group')}<span>Groups</span></a><a class="tab" href="#add-preview">${nav('plus')}<span>Add</span></a><a class="tab" href="#activity-preview">${nav('bell')}<span>Activity</span></a><a class="tab" href="#you-preview">${nav('user')}<span>You</span></a></nav></footer>`;
const ranges=(active)=>`<div class="j19-range"><a class="j19-chip ${active==='30'?'active':''}" href="#range-30">30 days</a><a class="j19-chip ${active==='90'?'active':''}" href="#overview">90 days</a><a class="j19-chip ${active==='365'?'active':''}" href="#range-365">12 months</a></div>`;
function summary(period){const s=M.snapshot(period),curr=Math.max(12,Math.round(52*(s.currentCHF/Math.max(s.currentCHF,s.previousCHF)))),prev=Math.max(12,Math.round(52*(s.previousCHF/Math.max(s.currentCHF,s.previousCHF))));const delta=s.deltaCHF;const copy=delta<0?`${M.money(-delta)} less than the previous ${period==='365'?'12 months':period+' days'}`:`${M.money(delta)} more than the previous ${period==='365'?'12 months':period+' days'}`;return `<div class="card j19-hero"><div class="j19-eyebrow">Shared spending · ${s.label}</div><div class="j19-value">${M.money(s.currentCHF)}</div><div class="j19-delta ${delta>0?'up':''}">${copy}</div><div class="j19-bars"><div class="j19-bar-wrap"><div class="j19-bar current"><i style="height:${curr}px"></i></div><div class="j19-bar-label">This period</div></div><div class="j19-bar-wrap"><div class="j19-bar"><i style="height:${prev}px"></i></div><div class="j19-bar-label">Previous period</div></div></div></div>`}
function topInsight(period){const s=M.snapshot(period),top=s.breakdown[0];return `<a class="card j19-insight" href="#biggest-group"><div><h3>${top.name} was your biggest shared-spend group</h3><p>${Math.round(top.share*100)}% of your CHF shared spending in this period.</p></div><div class="j19-metric"><b>${M.money(top.minor)}</b><span>${Math.round(top.share*100)}%</span></div><div class="j19-insight-foot"><span>See the group pattern</span>${svg('chev')}</div></a>`}
function statusInsight(period){const s=M.snapshot(period);return `<a class="card j19-insight" href="#settled-pattern"><div><h3>${s.settledGroups} groups ended the period settled</h3><p>${s.openGroups} group still has an open balance. Insights does not settle it for you.</p></div><div class="j19-metric"><b>${s.settledGroups}/${s.breakdown.length}</b><span>settled</span></div><div class="j19-insight-foot"><span>Understand the pattern</span>${svg('chev')}</div></a>`}
function otherAsset(period){const s=M.snapshot(period);if(!s.dot.length)return '';const d=s.dot[0];return `<a class="card j19-insight" href="#mixed-assets"><div><h3>${d.name} has separate DOT activity</h3><p>Kept outside the CHF comparison so an estimate cannot look payable.</p></div><div class="j19-metric"><b>${M.money(d.minor,'DOT',6)}</b><span>separate asset</span></div><div class="j19-insight-foot"><span>Why currencies stay separate</span>${svg('chev')}</div></a>`}
function overview(id,period){const s=M.snapshot(period);return `<section id="${id}" class="screen ${id==='overview'?'default':''}">${header('Insights',s.label)}<main class="j19-content">${ranges(period)}<a class="card j19-scope" href="#scope-picker"><div class="j19-ico">${svg('group')}</div><div><b>All groups</b><span>${s.breakdown.length} CHF groups${s.dot.length?' · 1 DOT group':''}</span></div>${svg('chev')}</a>${summary(period)}<div class="j19-section"><h2>What stands out</h2><span>Patterns, not transactions</span></div>${topInsight(period)}${statusInsight(period)}${otherAsset(period)}<div class="j19-note">${svg('info')}<div>Insights is read-only. It uses confirmed records you can currently access and never turns an estimate into a payment instruction.</div></div></main>${tabs}</section>`}
function breakdown(){const s=M.snapshot('90');return s.breakdown.map(x=>`<a class="j19-row" href="#group-${x.id}"><div><b>${x.name}</b><span>${Math.round(x.share*100)}% of CHF spending<div class="j19-mini"><i style="width:${Math.round(x.share*100)}%"></i></div></span></div><div class="amount">${M.money(x.minor)}</div></a>`).join('')}
function groupDetail(id){const g=M.insightForGroup('90',id),delta=g.deltaMinor,more=delta>=0;return `<section id="group-${id}" class="screen">${header(g.name,'Last 90 days')}<main class="j19-content"><div class="card j19-hero"><div class="j19-eyebrow">Shared spending</div><div class="j19-value">${M.money(g.minor)}</div><div class="j19-delta ${more?'up':''}">${M.money(Math.abs(delta))} ${more?'more':'less'} than the previous 90 days</div></div><div class="card j19-privacy"><h2>What this means</h2><p>This is the confirmed CHF shared spending currently visible to you in ${g.name}. Corrections use the latest accepted record instead of counting old and new versions twice.</p></div><div class="j19-note">${svg('shield')}<div>Opening the group re-checks current access. Insights does not preserve private group detail after access is removed.</div></div></main><footer class="j19-focus-footer"><a class="j19-primary" href="#handoff-group">View ${g.name}</a><a class="j19-secondary" href="#overview">Back to Insights</a></footer></section>`}
const simple=(id,title,body,primary='Back to Insights',href='#overview')=>`<section id="${id}" class="screen">${header(title)}<main class="j19-content">${body}</main><footer class="j19-focus-footer"><a class="j19-primary" href="${href}">${primary}</a></footer></section>`;
const empty=(title,copy,iconName='info')=>`<div class="card j19-empty"><div class="state-icon">${svg(iconName)}</div><h2>${title}</h2><p>${copy}</p></div>`;
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>ChopDot — Insights V1</title><style>${read('inherited.css')}</style><style>${read('shell.css')}</style><style>${read('insights.css')}</style></head><body><div class="lab"><main class="stage"><div class="device">${overview('overview','90')}${overview('range-30','30')}${overview('range-365','365')}
<section id="scope-picker" class="screen">${header('Choose scope','Insights')}<main class="j19-content"><div class="card j19-breakdown"><a class="j19-row" href="#overview"><div><b>All groups</b><span>Combined CHF pattern; DOT remains separate</span></div>${svg('chev')}</a>${breakdown()}</div><div class="j19-note">${svg('info')}<div>Changing scope changes only this view. It does not alter any group, expense or balance.</div></div></main><footer class="j19-focus-footer"><a class="j19-secondary" href="#overview">Cancel</a></footer></section>
${groupDetail('zurich')}${groupDetail('apartment')}${groupDetail('ski')}${groupDetail('geneva')}
${simple('biggest-group','Biggest group',`<div class="card j19-breakdown">${breakdown()}</div><div class="j19-note">${svg('info')}<div>Group ranking is by your authorized CHF shared-spend amount only. People are never ranked or scored.</div></div>`,'View Zurich Weekend','#handoff-group')}
${simple('settled-pattern','Settled groups',`<div class="card j19-insight"><div><h3>3 of 4 CHF groups ended settled</h3><p>One group still has an open balance. This is descriptive only; Insights cannot settle it.</p></div><div class="j19-metric"><b>3/4</b><span>settled</span></div></div><div class="j19-note good">${svg('check')}<div>Reading this card does not change the open balance or attention state.</div></div>`)}
${simple('mixed-assets','Separate assets',`<div class="card j19-privacy"><h2>CHF and DOT stay separate</h2><p>CHF shared spending is compared only with CHF. Hackathon activity is shown separately as DOT 2.400000.</p><p>No converted total is used as a payment instruction.</p></div><div class="card j19-breakdown"><div class="j19-row"><div><b>CHF shared spending</b><span>Last 90 days</span></div><div class="amount">CHF 1,020.00</div></div><div class="j19-row"><div><b>Hackathon</b><span>Separate asset</span></div><div class="amount">DOT 2.400000</div></div></div>`)}
${simple('insufficient','Not enough history',empty('Need a little more history','This scope has fewer than three confirmed records, so ChopDot will not invent a trend.','info'))}
${simple('offline','Offline',empty('Saved insights may be out of date','You can read the last saved pattern, but comparisons are not refreshed until you reconnect.','refresh'))}
${simple('loading','Loading insights',`<div class="card loading-card"><div class="skel short"></div><div class="skel"></div><div class="skel med"></div></div>`)}
${simple('error','Insights unavailable',empty('Could not refresh insights','No new pattern is inferred. Try again when the current records are available.','refresh'),'Try again','#overview')}
${simple('empty','No insights yet',empty('Nothing to compare yet','Once you have enough confirmed shared history, useful patterns will appear here.','trend'))}
${simple('access-changed','Access changed',empty('This group is no longer included','Insights recalculated from the groups you can currently access. Old private group detail is not restored.','shield'))}
${simple('partial-data','Comparison unavailable',`<div class="card j19-hero"><div class="j19-eyebrow">Shared spending · partial data</div><div class="j19-value">CHF 640.00</div><div class="bodycopy" style="margin-top:8px">Current period is incomplete, so no comparison is shown.</div></div><div class="j19-note pink">${svg('info')}<div>Partial sync must not look like a real increase or decrease.</div></div>`)}
${simple('privacy','How Insights works',`<div class="card j19-privacy"><h2>Useful patterns, not new money truth</h2><p>Insights reads accepted records that you are currently allowed to see. It dedupes corrected versions and compares only like-for-like currencies and periods.</p><p>It never changes an expense, balance, request, payment, savings position or group.</p></div><div class="j19-note">${svg('shield')}<div>No people scores, trust rankings or hidden cross-currency conversions.</div></div>`,'Review account preferences','#handoff-settings')}
${simple('handoff-group','Group Home preview',`<div class="j19-note">${svg('group')}<div>Journey 08 owns the group overview. This boundary preview preserves the selected group; it does not redesign Group Home.</div></div>`,'Return to Insights','#overview')}
${simple('handoff-settings','Account preferences preview',`<div class="j19-note">${svg('settings')}<div>Journey 27 owns account and preference controls. Insights does not create settings here.</div></div>`,'Return to Insights','#overview')}
${simple('home-preview','Home preview',`<div class="j19-note">${svg('home')}<div>Home remains an approved adjacent surface. This preview only demonstrates the Insights entry/return boundary.</div></div>`,'Open Insights','#overview')}
${simple('you-preview','You preview',`<div class="j19-note">${svg('user')}<div>You remains an adjacent surface. This preview only demonstrates the Insights entry/return boundary.</div></div>`,'Open Insights','#overview')}
${simple('activity-preview','Activity preview',`<div class="j19-note">${svg('bell')}<div>Activity remains Journey 18. Insights does not absorb its attention or notification behavior.</div></div>`,'Return to Insights','#overview')}
${simple('add-preview','Add preview',`<div class="j19-note">${svg('plus')}<div>Add remains an adjacent action. Insights is read-only and cannot create an expense.</div></div>`,'Return to Insights','#overview')}
<section id="demo" class="screen">${header('Demo states','Insights V1')}<main class="j19-content"><details class="j19-demo" open><summary>Review alternate states</summary><div class="j19-demo-links"><a href="#overview">90 days</a><a href="#range-30">30 days</a><a href="#range-365">12 months</a><a href="#scope-picker">Choose scope</a><a href="#mixed-assets">Mixed assets</a><a href="#insufficient">Not enough history</a><a href="#partial-data">Partial data</a><a href="#offline">Offline</a><a href="#loading">Loading</a><a href="#error">Error</a><a href="#empty">Empty</a><a href="#access-changed">Access changed</a><a href="#privacy">How it works</a></div></details></main><footer class="j19-focus-footer"><a class="j19-primary" href="#overview">Back to Insights</a></footer></section>
</div></main><aside class="labpanel"><h2>Journey 19 — Insights V1</h2><p>Prototype only. Read-only patterns from synthetic confirmed records.</p><div class="labsec"><div class="lablabel">Review</div><a class="compare" href="#overview">Overview</a><a class="compare" href="#range-30">30 days</a><a class="compare" href="#scope-picker">Group scope</a><a class="compare" href="#mixed-assets">Mixed assets</a><a class="compare" href="#partial-data">Partial data</a><a class="compare" href="#privacy">How Insights works</a></div><div class="labsec"><p class="note">No Golden HTML changes. TYPO-01 remains deferred.</p></div></aside></div><script>window.J19Model=${JSON.stringify({periods:M.PERIODS,groups:M.GROUPS})};
const valid=new Set(${JSON.stringify(['overview','range-30','range-365','scope-picker','group-zurich','group-apartment','group-ski','group-geneva','biggest-group','settled-pattern','mixed-assets','insufficient','offline','loading','error','empty','access-changed','partial-data','privacy','handoff-group','handoff-settings','home-preview','you-preview','activity-preview','add-preview','demo'])});
function normalize(){const id=location.hash.slice(1);if(id&&!valid.has(id))location.replace('#overview');}
addEventListener('hashchange',normalize);normalize();</script></body></html>\n`;
fs.writeFileSync(path.join(root,'v1-candidate.html'),html);console.log(crypto.createHash('sha256').update(html).digest('hex'));
