const assert=require('node:assert/strict'),M=require('./model.cjs');let assertions=0,scenarios=0;const eq=(a,b)=>{assertions++;assert.deepEqual(a,b)},ok=x=>{assertions++;assert(x)},test=(n,fn)=>{fn();scenarios++};
test('90-day totals',()=>{const s=M.snapshot('90');eq(s.currentCHF,102000);eq(s.previousCHF,113000);eq(s.deltaCHF,-11000);eq(s.breakdown.length,4)});
test('90-day top group',()=>{const s=M.snapshot('90');eq(s.breakdown[0].id,'zurich');eq(s.breakdown[0].minor,43000);ok(s.breakdown[0].share>.42&&s.breakdown[0].share<.43)});
test('30-day comparison',()=>{const s=M.snapshot('30');eq(s.currentCHF,36000);eq(s.previousCHF,42000);eq(s.deltaCHF,-6000);eq(s.dot.length,0)});
test('365-day comparison',()=>{const s=M.snapshot('365');eq(s.currentCHF,382000);eq(s.previousCHF,365000);eq(s.deltaCHF,17000);eq(s.dot[0].minor,4800000)});
test('DOT never enters CHF total',()=>{const s=M.snapshot('90');eq(s.currentCHF,Object.values(M.PERIODS['90'].groups).reduce((a,b)=>a+b,0));eq(s.dot[0].currency,'DOT');eq(M.money(s.dot[0].minor,'DOT',6),'DOT 2.400000')});
test('access removal recomputes totals',()=>{const s=M.snapshot('90',{authorized:['apartment','ski','geneva','hackathon']});eq(s.currentCHF,59000);eq(s.previousCHF,79000);ok(!s.breakdown.some(x=>x.id==='zurich'));eq(s.dot.length,1)});
test('access removal can remove asset too',()=>{const s=M.snapshot('90',{authorized:['zurich','apartment']});eq(s.currentCHF,78000);eq(s.dot.length,0)});
test('partial data suppresses comparison',()=>{const s=M.snapshot('90',{complete:false});eq(s.comparisonAvailable,false);eq(s.deltaCHF,null);eq(s.currentCHF,102000)});
test('group insight uses same period',()=>{const g=M.insightForGroup('90','zurich');eq(g.minor,43000);eq(g.previousMinor,34000);eq(g.deltaMinor,9000)});
test('unknown group has no insight',()=>eq(M.insightForGroup('90','missing'),null));
test('route only known groups',()=>{eq(M.routeForGroup('zurich'),'handoff-group');eq(M.routeForGroup('missing'),'overview')});
test('latest record wins correction',()=>{const rows=[{id:'e1',version:1,status:'active',currency:'CHF',group:'zurich',amountMinor:8460},{id:'e1',version:2,status:'active',currency:'CHF',group:'zurich',amountMinor:7460}];eq(M.aggregateRecords(rows),7460)});
test('duplicate same version not double counted',()=>{const rows=[{id:'e1',version:1,status:'active',currency:'CHF',group:'zurich',amountMinor:1000},{id:'e1',version:1,status:'active',currency:'CHF',group:'zurich',amountMinor:1000}];eq(M.aggregateRecords(rows),1000)});
test('deleted latest record excluded',()=>{const rows=[{id:'e1',version:1,status:'active',currency:'CHF',group:'zurich',amountMinor:1000},{id:'e1',version:2,status:'deleted',currency:'CHF',group:'zurich',amountMinor:1000}];eq(M.aggregateRecords(rows),0)});
test('record currency filter',()=>{const rows=[{id:'a',version:1,status:'active',currency:'CHF',group:'zurich',amountMinor:1000},{id:'b',version:1,status:'active',currency:'DOT',group:'hackathon',amountMinor:2400000}];eq(M.aggregateRecords(rows,{currency:'CHF'}),1000);eq(M.aggregateRecords(rows,{currency:'DOT'}),2400000)});
test('record access filter',()=>{const rows=[{id:'a',version:1,status:'active',currency:'CHF',group:'zurich',amountMinor:1000},{id:'b',version:1,status:'active',currency:'CHF',group:'apartment',amountMinor:2000}];eq(M.aggregateRecords(rows,{authorizedGroups:['apartment']}),2000)});
test('money formatting exact',()=>{eq(M.money(102000),'CHF 1,020.00');eq(M.money(43000),'CHF 430.00');eq(M.money(2400000,'DOT',6),'DOT 2.400000')});
test('unknown period rejected',()=>{assertions++;assert.throws(()=>M.snapshot('7'))});
console.log(JSON.stringify({ok:true,assertions,scenarios},null,2));
