import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const j=path.resolve(import.meta.dirname,'..');
const read=n=>fs.readFileSync(path.join(import.meta.dirname,n),'utf8');
const base=read('inherited.css'),extra=read('entry.css');
const model=read('model.cjs'),ui=read('ui.js');
const references={home:read('reference-home.html'),invite:read('reference-invite.html')};
const lab=`<aside class="labpanel"><h2>Journey 01 — Enter ChopDot</h2><p>Sign in. Keep your place. Start together.</p><div class="labsec"><div class="lablabel">Entry scenarios</div><button class="entry-testbtn" data-fixture="new">New person</button><button class="entry-testbtn" data-fixture="returning">Returning person</button><button class="entry-testbtn" data-fixture="invite">From a group invite</button><button class="entry-testbtn" data-fixture="reauth">Session expired · invite</button></div><div class="labsec"><div class="lablabel">Demo sign-in</div><p>Use code <b>123456</b>. No email, account or payment is created.</p><button class="entry-testbtn" data-fixture="expired">Expired email code</button><button class="entry-testbtn" data-fixture="wallet">Wallet sign-in</button><button class="entry-testbtn" data-demo-result="approved">Test result: approval verified</button><button class="entry-testbtn" data-demo-result="declined">Test result: approval declined</button><button class="entry-testbtn" data-demo-result="expired">Test result: approval expired</button><button class="entry-testbtn" data-demo-result="unknown">Test result: unknown</button></div><div class="labsec"><div class="lablabel">Connection</div><button class="entry-testbtn" data-fixture="offline">Offline with an invite</button><button class="entry-testbtn" data-online="true">Restore demo connection</button><button class="entry-testbtn" data-online="false">Disconnect demo</button></div><div class="labsec"><div class="lablabel">Review boundary</div><p>Email codes are the proposed default; wallet sign-in is optional. Authentication is simulated. Joining an invite and authorizing payments are separate actions.</p></div></aside>`;
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="prototype-only" content="No real authentication or payment"><title>ChopDot — Enter ChopDot V1 candidate</title><style id="inherited-golden-css">${base}</style><style id="entry-css">${extra}</style></head><body><div class="lab"><div class="stage"><div class="device"><section id="entry-screen" class="entry-screen" aria-label="Enter ChopDot"></section></div></div>${lab}</div><script type="application/json" id="references">${JSON.stringify(references).replace(/</g,'\\u003c')}</script><script>${model}\n${ui}</script></body></html>\n`;
fs.writeFileSync(path.join(j,'v1-candidate.html'),html);console.log(crypto.createHash('sha256').update(html).digest('hex'));
