(function(){
'use strict';
const M=EntryModel;let s=M.initial();const host=document.getElementById('entry-screen');
const P={back:'<path d="m15 18-6-6 6-6"/>',chevron:'<path d="m9 18 6-6-6-6"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',people:'<circle cx="9" cy="7" r="4"/><path d="M2 21v-2a4 4 0 0 1 4-4h6a4 4 0 0 1 4 4v2M17 4a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-3.9"/>',check:'<path d="m5 12 4 4L19 6"/>',receipt:'<path d="M5 3h14v18l-3-2-4 2-4-2-3 2V3Z"/><path d="M9 7h6M9 11h6M9 15h3"/>',wallet:'<path d="M20 8V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h15v11H5a3 3 0 0 1-3-3V6"/><path d="M20 12h-5v5h5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',lock:'<rect x="4" y="11" width="16" height="10" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/>',x:'<path d="m6 6 12 12M6 18 18 6"/>',alert:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/>',refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M5 8a8 8 0 0 1 13-3l2 2M4 17l2 2a8 8 0 0 0 13-3"/>',wifi:'<path d="m2 2 20 20M2 8a16 16 0 0 1 4-3M9 4a16 16 0 0 1 13 4M5 12a11 11 0 0 1 4-2M13 10a11 11 0 0 1 6 2M8 16a6 6 0 0 1 8 0M12 20h.01"/>'};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${P[n]}</svg>`;
const btn=(t,e,style='primary',extra='')=>`<button type="button" class="${style}" data-action="${e}" ${extra}>${t}</button>`;
const head=(title,back='welcome',brand=false)=>brand?`<header class="root-header"><div class="brand"><span class="mark"></span>ChopDot</div><button class="entry-demobadge" data-action="HELP">Demo</button></header>`:`<header class="detail-header"><button class="icon-btn" aria-label="Back" data-action="GO" data-route="${back}">${icon('back')}</button><div class="header-title"><b>${title}</b><span>${s.destination==='invite'?'Geneva Weekend':'ChopDot'}</span></div><button class="entry-demobadge" data-action="HELP">Demo</button></header>`;
const heading=(h,p)=>`<div><h1 class="entry-heading" tabindex="-1">${h}</h1>${p?`<p class="entry-lead">${p}</p>`:''}</div>`;
const notice=()=>`<p class="entry-error" role="alert">${esc(s.error)}</p><p class="entry-notice" role="status">${esc(s.notice)}</p>`;
const token=(n,cls='')=>`<span class="entry-token ${cls}">${icon(n)}</span>`;
const row=(n,t,p,action='',extra='')=>`<${action?'button':'div'} class="entry-row" ${action?`data-action="${action}" ${extra} style="width:100%;text-align:left;background:transparent"`:''}>${token(n)}<div><strong>${t}</strong><small>${p}</small></div>${action?icon('chevron'):'<span></span>'}</${action?'button':'div'}>`;
function render(){
 const r=s.route;host.dataset.state=r;host.dataset.destination=s.destination;let H='',B='',F='';
 switch(r){
 case 'welcome':H=head('',null,true);B=`<div class="entry-welcome">${heading('Shared expenses.<br>Less back-and-forth.','One place for who paid what.')}</div><section class="card">${row('people','Bring your people.','A trip, a home, or just dinner.')}${row('receipt','Keep things clear.','Add expenses. Know where you stand.')}</section><p class="entry-quiet">Start with an email. No wallet needed.</p>`;F=btn(`${icon('mail')} Continue with email`,'EMAIL')+btn(`${icon('wallet')} Use a wallet`,'WALLET','secondary');break;
 case 'invite':H=head('',null,true);B=heading('Your invite is waiting.','Sign in, then decide whether to join.')+`<section class="card">${row('people','Geneva Weekend','Devinson invited you · 3 people · CHF')}</section><p class="entry-quiet">Expenses stay private until you join.</p>`;F=btn('Continue with email','EMAIL')+btn('Use a wallet','WALLET','secondary')+btn('Not now','START_OVER','text-link');break;
 case 'email':H=head('Continue with email',s.destination==='invite'?'invite':'welcome');B=heading('What’s your email?','Use the same email each time.')+`<form id="email-form"><label class="entry-field" for="email">Email</label><input id="email" class="entry-input" type="email" autocomplete="email" inputmode="email" value="${esc(s.email)}" placeholder="you@example.com" required aria-describedby="email-help"><p id="email-help" class="entry-quiet" style="margin-top:10px">We’ll send you a sign-in code.</p>${notice()}</form>`+(s.destination==='invite'?`<section class="card">${row('people','Geneva Weekend','Your invite stays with you.')}</section>`:'');F=`<button class="primary" form="email-form" type="submit">Send code</button>`+btn('Use a wallet instead','WALLET','text-link');break;
 case 'code':H=head('Check your email','email');B=`<div class="entry-icon-large">${icon('mail')}</div>`+heading('Enter your code.',`Sent to ${esc(s.email)}.`)+`<form id="code-form"><label class="entry-field" for="code">6-digit code</label><input id="code" class="entry-input code" autocomplete="one-time-code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" placeholder="000000" required>${notice()}</form><div class="entry-inline">${btn('Send a new code','RESEND','entry-flat')}${btn('Change email','BACK_TO_EMAIL','entry-flat')}</div>`;F=`<button class="primary" form="code-form" type="submit">Continue</button>`;break;
 case 'profile':H=head('A name for your groups','email');B=heading('What should we call you?','This is the name your group sees.')+`<form id="profile-form"><label class="entry-field" for="name">Your name</label><input id="name" class="entry-input" autocomplete="given-name" value="${esc(s.name)}" placeholder="Your name" maxlength="40" required>${notice()}</form>`;F=`<button class="primary" form="profile-form" type="submit">Continue</button>`;break;
 case 'wallet':H=head('Use a wallet',s.destination==='invite'?'invite':'welcome');B=heading('Choose your account.','Sign in only. No payment is requested.')+`<section class="card">${row('wallet','Everyday','Account ending 9Kq','REQUEST_APPROVAL','data-account="Everyday"')}${row('wallet','Travel','Account ending 7Hr','REQUEST_APPROVAL','data-account="Travel"')}</section><p class="entry-quiet">Confirm the sign-in request in your wallet.</p>`;F=btn('Use email instead','EMAIL','secondary');break;
 case 'approval-waiting':case 'approval-unknown':case 'approval-expired':case 'approval-declined':{
  const data={'approval-waiting':['clock','Check your wallet.','Approve the sign-in request there.'],'approval-unknown':['refresh','Still checking.','We have not received a sign-in result yet.'],'approval-expired':['clock','Request expired.','Request a fresh sign-in approval.'],'approval-declined':['x','Sign-in declined.','Nothing changed. You can try again.']}[r];
  H=head('Wallet sign-in','wallet');B=`<div class="entry-icon-large">${icon(data[0])}</div>`+heading(data[1],data[2])+`<section class="card">${row('wallet',esc(s.account||'Everyday'),'Sign-in request · no payment')}</section>`+notice();
  F=(r==='approval-waiting'||r==='approval-unknown'?btn('Check again','REFRESH_APPROVAL'):btn('Try again','REQUEST_APPROVAL','primary',`data-account="${esc(s.account||'Everyday')}"`))+btn('Cancel','CANCEL_APPROVAL','secondary');break;}
 case 'offline':H=head('No connection','email');B=`<div class="entry-icon-large">${icon('wifi')}</div>`+heading('You’re offline.','Connect to the internet to sign in.')+`<section class="card">${row('mail','Your place is saved.',s.destination==='invite'?'Geneva Weekend is still waiting.':'You can continue when you reconnect.')}</section>`;F=btn('Try again','RETRY_CONNECTION')+btn('Back','BACK_TO_EMAIL','secondary');break;
 case 'session-expired':H=head('',null,true);B=`<div class="entry-icon-large">${icon('lock')}</div>`+heading('Welcome back.','Sign in again to pick up where you left off.')+`<section class="card">${row(s.destination==='invite'?'people':'lock',s.destination==='invite'?'Geneva Weekend':'Your groups','Use your original sign-in.')}</section>`;F=btn('Continue with email','EMAIL')+btn('Use a wallet','WALLET','secondary');break;
 case 'wrong-account':H=head('Check your sign-in','email');B=`<div class="entry-icon-large">${icon('alert')}</div>`+heading('Use your original sign-in.','This is a different account.')+`<section class="card">${row('mail',esc(s.email||s.account),'No groups have been opened.')}</section>`;F=btn('Use another email','BACK_TO_EMAIL')+btn('Back','START_OVER','secondary');break;
 case 'ready':H=head('Signed in','welcome');B=`<div class="entry-icon-large success">${icon('check')}</div>`+heading(s.isNew?'You’re ready.':'Welcome back.',s.destination==='invite'?'Your invite is right where you left it.':s.isNew?'Start a group when you’re ready.':'Your groups are ready when you are.')+`<section class="card entry-body"><p class="entry-name">${esc(s.name||'Dev')}</p><div class="entry-account">${esc(s.method==='wallet'?(s.account+' · Wallet account'):s.email)}</div></section>`+(s.destination==='invite'?`<section class="card">${row('people','Geneva Weekend','You have not joined yet.')}</section>`:'');F=btn(s.destination==='invite'?'Continue to invite':'Open ChopDot','OPEN_DESTINATION')+btn('Use a different account','BACK_TO_EMAIL','text-link');break;
 case 'load-error':H=head('ChopDot','welcome');B=`<div class="entry-icon-large">${icon('refresh')}</div>`+heading('Couldn’t finish signing in.','Try again. Your invite stays here.');F=btn('Try again','EMAIL')+btn('Back','START_OVER','secondary');break;
 case 'home-reference':case 'invite-reference':{
 H=head(r==='home-reference'?'Home':'Group invitation','ready');B='';F=btn('Back to sign-in result','READY','secondary');
 host.innerHTML=H+`<div class="entry-refwrap"><iframe class="entry-ref" id="golden-frame" title="${r==='home-reference'?'Home reference':'Invite reference'}" sandbox="allow-same-origin"></iframe></div><footer class="focus-footer">${F}<p class="entry-refnote">Approved journey reference · demo data</p></footer>`;
 const frame=document.getElementById('golden-frame');const ref=r==='home-reference'?'home':'invite';frame.srcdoc=JSON.parse(document.getElementById('references').textContent)[ref];
 frame.onload=()=>{const doc=frame.contentDocument;const show=id=>{const target=doc.getElementById(id);if(!target)return;doc.querySelectorAll('.screen').forEach(el=>el.style.display=el===target?'grid':'none');};if(ref==='invite')show('join');doc.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();if((a.getAttribute('href')||'').startsWith('#'))show(a.getAttribute('href').slice(1));});};return;}
 }
 host.innerHTML=H+`<main class="app-content">${B}<div class="entry-demohelp" id="demo-help" hidden>Prototype only. No email or account is created. Use code <b>123456</b>. <b>dev@example.com</b> previews a returning person; any other valid example email previews a new person. For the wallet demo, use these separate test results:<button class="entry-testbtn" data-demo-result="approved">Test result: approval verified</button><button class="entry-testbtn" data-demo-result="declined">Test result: approval declined</button><button class="entry-testbtn" data-demo-result="unknown">Test result: unknown</button><button class="entry-testbtn" data-online="true">Restore demo connection</button></div></main><footer class="focus-footer"><div class="footer-stack">${F}</div></footer>`;
}
function go(event,payload={},replace=false){const before=s.route;s=M.apply(s,event,payload);const fragment='#'+s.route+(s.destination==='invite'?'/invite':'');if(replace)history.replaceState(null,'',fragment);else if(before!==s.route||location.hash!==fragment)history.pushState(null,'',fragment);render();}
function fixture(name){s=M.initial();
 if(name==='invite')s=M.apply(s,'INVITE');
 if(name==='returning'){s.email='dev@example.com';s.route='email';}
 if(name==='reauth')s=M.apply(s,'REAUTH',{destination:'invite'});
 if(name==='offline'){s.destination='invite';s.online=false;s.email='sam@example.com';s.route='offline';}
 if(name==='wallet'){s=M.apply(s,'WALLET');}
 if(name==='ready'){s={...s,verified:true,method:'email',name:'Dev',email:'dev@example.com',isNew:false,route:'ready'};}
 if(name==='expired'){s={...s,method:'email',route:'code',email:'sam@example.com',expired:true,challenge:1};}
 go('NAVIGATE',{route:s.route});
}
 document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='email-form'){s=M.apply(s,'SET_EMAIL',{value:document.getElementById('email').value});go('SEND_CODE');}if(e.target.id==='code-form')go('VERIFY_CODE',{code:document.getElementById('code').value});if(e.target.id==='profile-form')go('PROFILE',{name:document.getElementById('name').value});});
 document.addEventListener('click',e=>{
 const f=e.target.closest('[data-fixture]');if(f){fixture(f.dataset.fixture);return;}
 const d=e.target.closest('[data-demo-result]');if(d){go('APPROVAL_RESULT',{request:s.request,result:d.dataset.demoResult});return;}
 const net=e.target.closest('[data-online]');if(net){s.online=net.dataset.online==='true';s.notice=s.online?'Demo connection restored.':'Demo connection is offline.';render();return;}
 const t=e.target.closest('[data-action]');if(!t)return;const a=t.dataset.action;
 if(a==='HELP'){document.getElementById('demo-help')?.toggleAttribute('hidden');return;}
 if(a==='GO'){if(['approval-waiting','approval-unknown'].includes(s.route))go('CANCEL_APPROVAL');else go('NAVIGATE',{route:t.dataset.route});return;}
 if(a==='READY'){go('NAVIGATE',{route:'ready'});return;}
 go(a,{account:t.dataset.account||s.account});
 });
 window.addEventListener('popstate',()=>{s=M.apply(s,'NAVIGATE',{route:location.hash.slice(1).split('/')[0]||'welcome'});render();});
 document.addEventListener('input',e=>{if(e.target.id==='email')s=M.apply(s,'SET_EMAIL',{value:e.target.value});});
 window.EntryDemo={get:()=>JSON.parse(JSON.stringify(s)),dispatch:go,fixture};
 const parts=location.hash.slice(1).split('/');let requested=parts[0];if(parts[1]==='invite')s.destination='invite';if(['code','profile','ready','home-reference','invite-reference'].includes(requested))requested='email';if(requested==='invite')fixture('invite');else if(requested==='session-expired')fixture('reauth');else if(requested==='offline')fixture('offline');else go('NAVIGATE',{route:requested||'welcome'},true);
})();
