/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ChopDotEscrowVault {
  export type EscrowCaseStruct = {
    mode: BytesLike;
    token: AddressLike;
    creator: AddressLike;
    releaseRecipient: AddressLike;
    rulesHash: BytesLike;
    deadline: BigNumberish;
    totalRequired: BigNumberish;
    totalDeposited: BigNumberish;
    requiredApprovalCount: BigNumberish;
    approvalCount: BigNumberish;
    participantCount: BigNumberish;
    state: BigNumberish;
  };

  export type EscrowCaseStructOutput = [
    mode: string,
    token: string,
    creator: string,
    releaseRecipient: string,
    rulesHash: string,
    deadline: bigint,
    totalRequired: bigint,
    totalDeposited: bigint,
    requiredApprovalCount: bigint,
    approvalCount: bigint,
    participantCount: bigint,
    state: bigint
  ] & {
    mode: string;
    token: string;
    creator: string;
    releaseRecipient: string;
    rulesHash: string;
    deadline: bigint;
    totalRequired: bigint;
    totalDeposited: bigint;
    requiredApprovalCount: bigint;
    approvalCount: bigint;
    participantCount: bigint;
    state: bigint;
  };

  export type RequirementStruct = {
    participantId: BytesLike;
    amount: BigNumberish;
    deposited: BigNumberish;
    exists: boolean;
    complete: boolean;
    refunded: boolean;
  };

  export type RequirementStructOutput = [
    participantId: string,
    amount: bigint,
    deposited: bigint,
    exists: boolean,
    complete: boolean,
    refunded: boolean
  ] & {
    participantId: string;
    amount: bigint;
    deposited: bigint;
    exists: boolean;
    complete: boolean;
    refunded: boolean;
  };
}

export interface ChopDotEscrowVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveRelease"
      | "createCase"
      | "deposit"
      | "getCase"
      | "getParticipant"
      | "getRequirement"
      | "hasApproved"
      | "isApprover"
      | "nextCaseId"
      | "refund"
      | "release"
      | "voidCase"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CaseCreated"
      | "Deposited"
      | "Refunded"
      | "ReleaseApproved"
      | "Released"
      | "Voided"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCase",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike[],
      BytesLike[],
      BigNumberish[],
      AddressLike[],
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipant",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequirement",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprover",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCaseId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "release",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voidCase",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createCase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isApprover", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextCaseId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voidCase", data: BytesLike): Result;
}

export namespace CaseCreatedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    mode: BytesLike,
    creator: AddressLike,
    token: AddressLike,
    totalRequired: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    mode: string,
    creator: string,
    token: string,
    totalRequired: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    mode: string;
    creator: string;
    token: string;
    totalRequired: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    participant: AddressLike,
    participantId: BytesLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    participant: string,
    participantId: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    participant: string;
    participantId: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    participant: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    participant: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    participant: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleaseApprovedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    approver: AddressLike,
    approvalCount: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    approver: string,
    approvalCount: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    approver: string;
    approvalCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReleasedEvent {
  export type InputTuple = [
    caseId: BigNumberish,
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    caseId: bigint,
    recipient: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    caseId: bigint;
    recipient: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoidedEvent {
  export type InputTuple = [caseId: BigNumberish, reasonHash: BytesLike];
  export type OutputTuple = [caseId: bigint, reasonHash: string];
  export interface OutputObject {
    caseId: bigint;
    reasonHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChopDotEscrowVault extends BaseContract {
  connect(runner?: ContractRunner | null): ChopDotEscrowVault;
  waitForDeployment(): Promise<this>;

  interface: ChopDotEscrowVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveRelease: TypedContractMethod<
    [caseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCase: TypedContractMethod<
    [
      mode: BytesLike,
      token: AddressLike,
      requiredApprovalCount: BigNumberish,
      releaseRecipient: AddressLike,
      participants: AddressLike[],
      participantIds: BytesLike[],
      amounts: BigNumberish[],
      approvalAddresses: AddressLike[],
      rulesHash: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [caseId: BigNumberish, participantId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  getCase: TypedContractMethod<
    [caseId: BigNumberish],
    [ChopDotEscrowVault.EscrowCaseStructOutput],
    "view"
  >;

  getParticipant: TypedContractMethod<
    [caseId: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;

  getRequirement: TypedContractMethod<
    [caseId: BigNumberish, participant: AddressLike],
    [ChopDotEscrowVault.RequirementStructOutput],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [caseId: BigNumberish, actor: AddressLike],
    [boolean],
    "view"
  >;

  isApprover: TypedContractMethod<
    [caseId: BigNumberish, actor: AddressLike],
    [boolean],
    "view"
  >;

  nextCaseId: TypedContractMethod<[], [bigint], "view">;

  refund: TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;

  release: TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;

  voidCase: TypedContractMethod<
    [caseId: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveRelease"
  ): TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCase"
  ): TypedContractMethod<
    [
      mode: BytesLike,
      token: AddressLike,
      requiredApprovalCount: BigNumberish,
      releaseRecipient: AddressLike,
      participants: AddressLike[],
      participantIds: BytesLike[],
      amounts: BigNumberish[],
      approvalAddresses: AddressLike[],
      rulesHash: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [caseId: BigNumberish, participantId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getCase"
  ): TypedContractMethod<
    [caseId: BigNumberish],
    [ChopDotEscrowVault.EscrowCaseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipant"
  ): TypedContractMethod<
    [caseId: BigNumberish, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequirement"
  ): TypedContractMethod<
    [caseId: BigNumberish, participant: AddressLike],
    [ChopDotEscrowVault.RequirementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [caseId: BigNumberish, actor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprover"
  ): TypedContractMethod<
    [caseId: BigNumberish, actor: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCaseId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[caseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voidCase"
  ): TypedContractMethod<
    [caseId: BigNumberish, reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CaseCreated"
  ): TypedContractEvent<
    CaseCreatedEvent.InputTuple,
    CaseCreatedEvent.OutputTuple,
    CaseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Refunded"
  ): TypedContractEvent<
    RefundedEvent.InputTuple,
    RefundedEvent.OutputTuple,
    RefundedEvent.OutputObject
  >;
  getEvent(
    key: "ReleaseApproved"
  ): TypedContractEvent<
    ReleaseApprovedEvent.InputTuple,
    ReleaseApprovedEvent.OutputTuple,
    ReleaseApprovedEvent.OutputObject
  >;
  getEvent(
    key: "Released"
  ): TypedContractEvent<
    ReleasedEvent.InputTuple,
    ReleasedEvent.OutputTuple,
    ReleasedEvent.OutputObject
  >;
  getEvent(
    key: "Voided"
  ): TypedContractEvent<
    VoidedEvent.InputTuple,
    VoidedEvent.OutputTuple,
    VoidedEvent.OutputObject
  >;

  filters: {
    "CaseCreated(uint256,bytes32,address,address,uint256)": TypedContractEvent<
      CaseCreatedEvent.InputTuple,
      CaseCreatedEvent.OutputTuple,
      CaseCreatedEvent.OutputObject
    >;
    CaseCreated: TypedContractEvent<
      CaseCreatedEvent.InputTuple,
      CaseCreatedEvent.OutputTuple,
      CaseCreatedEvent.OutputObject
    >;

    "Deposited(uint256,address,bytes32,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "Refunded(uint256,address,address,uint256)": TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;
    Refunded: TypedContractEvent<
      RefundedEvent.InputTuple,
      RefundedEvent.OutputTuple,
      RefundedEvent.OutputObject
    >;

    "ReleaseApproved(uint256,address,uint256)": TypedContractEvent<
      ReleaseApprovedEvent.InputTuple,
      ReleaseApprovedEvent.OutputTuple,
      ReleaseApprovedEvent.OutputObject
    >;
    ReleaseApproved: TypedContractEvent<
      ReleaseApprovedEvent.InputTuple,
      ReleaseApprovedEvent.OutputTuple,
      ReleaseApprovedEvent.OutputObject
    >;

    "Released(uint256,address,address,uint256)": TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;
    Released: TypedContractEvent<
      ReleasedEvent.InputTuple,
      ReleasedEvent.OutputTuple,
      ReleasedEvent.OutputObject
    >;

    "Voided(uint256,bytes32)": TypedContractEvent<
      VoidedEvent.InputTuple,
      VoidedEvent.OutputTuple,
      VoidedEvent.OutputObject
    >;
    Voided: TypedContractEvent<
      VoidedEvent.InputTuple,
      VoidedEvent.OutputTuple,
      VoidedEvent.OutputObject
    >;
  };
}
