/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChopDotEscrowVault } from "./ChopDotEscrowVault";
export type { IERC20Minimal } from "./IERC20Minimal";
