import {requirePrototypeWriter,assertPrototypeWriter} from '../prototype-writer.js';
import {repository,activity,openItem,pending,deletionBlockers,offline,available} from './model.js';
import {repository as payments,scopeProof} from '../gate-c/model.js';
import {formatPreviewMoney} from '../money-v1.js';
await requirePrototypeWriter();
const repo=repository(localStorage,assertPrototypeWriter),pay=payments(localStorage,assertPrototypeWriter);
const fixture=new URLSearchParams(location.search).has('fixtures');
let actor=fixture?sessionStorage.getItem('chopdot.gate-b.actor')||'self':'self';
const docs={},defs={};
for(const j of ['j18','j27','j28']){const r=await fetch(`./goldens/${j}.html`);if(!r.ok)throw Error('Approved source unavailable');docs[j]=new DOMParser().parseFromString(await r.text(),'text/html');if(j!=='j18')defs[j]=await fetch(`./${j}-definitions.json`).then(r=>r.json());}
let s,route,screen,content;const app=document.querySelector('#app');
const el=(t,cls='',value)=>{const n=document.createElement(t);n.className=cls;if(value!==undefined)n.textContent=value;return n;};
const guard=fn=>(...args)=>{try{return fn(...args);}catch(e){error(e);}};
const button=(label,fn,kind='ghost')=>{const b=el('button',screen?.dataset.journey==='j18'?'j18-secondary':'btn '+kind,label);b.type='button';b.onclick=guard(fn);return b;};
const go=(page,extra={})=>{const h=new URLSearchParams({page,...extra}).toString();if(location.hash.slice(1)===h)render();else location.hash=h;};
const notice=(message,bad=false)=>{const n=el('p','gd-message'+(bad?' gd-error':''),message);n.role=bad?'alert':'status';content.prepend(n);return n;};
const money=m=>m?formatPreviewMoney(m):'';
function owner(kind,id='',group=''){
 sessionStorage.setItem('chopdot.gate-d.return',route?.page==='notifications'?'notifications':'activity');
 if(kind==='expense'&&group)pay.selectGroup(group);
 const page=kind==='expense'?'detail':kind==='payment'?'payment':kind==='group'?'group':'position';
 const folder=['expense','group'].includes(kind)?'gate-b':'gate-c';
 location.href=`../${folder}/index.html${fixture?'?fixtures=1':''}#${new URLSearchParams({page,...(id?{id}:{})})}`;
}
function entry(){if(parent!==window)parent.postMessage({type:'chopdot-gate-d-entry'},location.origin);else location.href=`../index.html?entry=signin${fixture?'&fixtures=1':''}`;}
function mount(j,id){document.querySelector('#golden-style').textContent=[...docs[j].querySelectorAll('style')].map(n=>n.textContent).join('\n');screen=(j==='j18'?docs[j].getElementById(id):docs[j].querySelector('.device')).cloneNode(true);screen.dataset.journey=j;screen.dataset.golden=id;screen.tabIndex=-1;screen.querySelectorAll('script,.review-rail').forEach(n=>n.remove());app.replaceChildren(screen);screen.querySelectorAll('.add-tab').forEach(n=>n.textContent='+');content=screen.querySelector(j==='j18'?'.j18-content':'#content');if(j!=='j18')content.replaceChildren();screen.querySelectorAll('a').forEach(a=>{a.onclick=e=>{e.preventDefault();const label=a.textContent.trim(),href=a.getAttribute('href');if(a.id==='back'||a.getAttribute('aria-label')==='Back')go(j==='j28'?'account-overview':'activity');else if(label==='Pots'||label==='Groups')owner('group');else if(label==='People')owner('position');else if(a.getAttribute('aria-label')==='Add')location.href=`../gate-b/index.html${fixture?'?fixtures=1':''}#page=editor`;else if(label==='You')go('account-overview');else go('activity');};});}
function view(j,id,{title,lead,facts,actions,notice:message}={}){
 mount(j,id);const def=defs[j][id];if(!def)throw Error('Unknown approved state '+id);content.dataset.testState=id;content.dataset.stateCode=def.code;
 if(def.status){const card=el('div','card status-card'),icon=el('div','status-icon '+def.status,def.status==='success'?'✓':def.status==='danger'?'×':def.status==='warn'?'!':'↻');card.append(icon,el('b','',title||def.title),el('p','',lead||def.lead));content.append(card);}else{const head=el('div');head.append(el('div','eyebrow',def.eyebrow),el('h1','hero',title||def.title),el('p','lead',lead||def.lead));content.append(head);}
 const note=message??def.notice;if(note){const n=el('div','notice '+(def.tone||''));n.append(el('span','mark','i'),el('span','',note));content.append(n);}
 const card=el('div','card pad');for(const [k,v]of facts||def.facts||[]){const row=el('div','row');row.append(el('span','',k),el('b','',String(v)));card.append(row);}content.append(card);
 screen.querySelector('#back').onclick=e=>{e.preventDefault();if(j==='j28'){if(route.owner==='payment')owner('payment',route.id);else if(route.owner==='expense')owner('expense',route.id);else go(route.id?'operation':'account-overview',route.id?{id:route.id}:{});}else go(def.back==='you-home-boundary'?'activity':def.back||'account-overview');};
 const stack=el('div','actions');for(const [label,fn,kind]of actions||[])stack.append(button(label,fn,kind));content.append(stack);
 if(j==='j27')screen.querySelector('.header-title span').textContent=`${s.gateD.account.displayName} · ${s.gateD.session.status==='active'?'local session':'guest'}`;
 return stack;
}
function error(e){if(!content){app.textContent=`Saved data could not be read: ${e.message}. It has not been overwritten.`;return;}notice(e.message,true);if(['OFFLINE','READ','CONFLICT','PENDING','SAVE','SESSION'].includes(e.code))content.append(button('Open recovery',()=>go('recovery',{owner:'account',id:pending(repo.read())?.id||'',reason:e.code})));}
function appearance(value){document.documentElement.dataset.appearance=value==='System'?(matchMedia('(prefers-color-scheme: dark)').matches?'Dark':'Light'):value;}
function activityPage(){
 const data=activity(s,actor),notifications=route.page==='notifications',filter=route.filter||'all',read=s.gateD.read[actor]||{};
 mount('j18',notifications?'notifications':filter==='all'?'activity':'filter-'+filter);
 const rows=notifications?data.events:filter==='attention'?data.attention:filter==='payments'?data.events.filter(e=>e.owner==='payment'):filter==='groups'?data.events.filter(e=>e.owner==='expense'):data.events;
 const unread=data.events.filter(e=>!read[e.id]).length;
 screen.querySelectorAll('[data-unread-badge]').forEach(n=>{n.textContent=unread;n.hidden=!unread;});screen.querySelectorAll('[data-unread-label]').forEach(n=>n.textContent=`${unread} unread`);
 const seg=content.querySelector('.j18-seg')?.cloneNode(true);content.replaceChildren();
 if(seg){content.append(seg);const values=['all','attention','payments','groups'];seg.querySelectorAll('a').forEach((a,i)=>{a.classList.toggle('active',values[i]===filter);if(i===1)a.textContent=`Needs attention · ${data.attention.length}`;a.onclick=e=>{e.preventDefault();go('activity',{filter:values[i]});};});}
 if(notifications){notice('Unread is not unresolved. Reading a notification does not complete the underlying task.');content.append(button('Mark all read',()=>{repo.commit({type:'read',actor,ids:data.events.map(e=>e.id)});render();}));}
 function list(items,title){content.append(el('div','j18-section',title));const card=el('div','card');if(!items.length)card.append(el('p','gd-message',notifications?'No notifications yet.':filter==='attention'?'Nothing needs your attention.':'No activity yet. Changes to your expenses and payments will appear here.'));
  for(const item of items){const row=docs.j18.querySelector('#activity .j18-row').cloneNode(true);row.dataset.itemId=item.id;row.href='#';row.classList.toggle('j18-unread',notifications&&!read[item.id]);row.querySelector('.j18-copy b').textContent=item.title;row.querySelector('.j18-copy span').textContent=item.detail;row.querySelector('time').textContent=item.at?new Date(item.at).toLocaleString():'Current state';row.querySelector('.j18-side b').textContent=money(item.money);row.querySelector('.j18-side span').textContent=item.owner==='payment'?'Open payment':'Open expense';row.onclick=guard(ev=>{ev.preventDefault();const target=openItem(repo.read(),item,actor);if(notifications)repo.commit({type:'read',actor,ids:[item.id]});if(target.stale){go('changed',{owner:target.owner,id:target.id,group:target.group||''});}else owner(target.owner,target.id,target.group);});card.append(row);}content.append(card);
 }
 if(!notifications&&filter==='all'&&data.attention.length)list(data.attention,'Needs your attention');list(rows,notifications?'Delivery copies':'Recent activity');
 content.append(button('Refresh',()=>render()));screen.querySelectorAll('[data-action="open-notifications"],.j18-bell').forEach(a=>a.onclick=e=>{e.preventDefault();go('notifications');});
 if(offline(s))notice('Offline. Showing saved activity; it may be out of date.');if(s.gateD.environment.readFailed)notice('Could not refresh. Showing saved activity. Retry when the record is available.',true);
}
function draft(kind){const old=s.gateD.draft;return old?.kind===kind?old:{kind,baseRevision:s.gateD.account.revision,values:kind==='profile'?{displayName:s.gateD.account.displayName}:kind==='appearance'?{appearance:s.gateD.account.appearance}:{activity:s.gateD.account.activity,reminders:s.gateD.account.reminders,pushPreference:s.gateD.account.pushPreference}};}
function saveDraft(d){repo.commit({type:'draft',actor,kind:d.kind,values:d.values,baseRevision:d.baseRevision});}
function begin(kind,values={},revision=s.gateD.account.revision){const id=crypto.randomUUID();const next=repo.commit({type:'begin',actor,id,kind,values,baseRevision:revision});const o=next.gateD.operations[id];if(o.status==='succeeded'&&['signout','deletion'].includes(kind))entry();else go('operation',{id});}
function edit(kind){
 const d=draft(kind),id=kind==='appearance'?'appearance-preview':kind+'-edit';
 const stack=view('j27',id,{title:kind==='profile'?'Edit display name':kind==='appearance'?'Preview appearance':'Edit notifications',lead:kind==='profile'?'Prepare a reversible display-name draft before saving.':kind==='appearance'?'Preview this appearance before saving.':'Choose app preferences. System permission remains separate.',notice:kind==='appearance'?`Cancel restores your saved ${s.gateD.account.appearance} appearance.`:'Draft changes are not saved account truth.',facts:[['Saved version',s.gateD.account.revision]],actions:[['Review',()=>{saveDraft(d);go('review',{kind});},'accent'],['Cancel',()=>{repo.commit({type:'discard',actor});go(kind+'-overview');}]]});
 const fields=el('div','card pad');
 const field=(key,label,type)=>{const wrap=el('label','gd-field',label);let input;if(type==='select'){input=el('select','gd-input');for(const v of ['System','Light','Dark']){const o=el('option','',v);o.value=v;input.append(o);}input.value=d.values[key];}else{input=el('input',type==='checkbox'?'':'gd-input');input.type=type;if(type==='checkbox')input.checked=d.values[key];else input.value=d.values[key];}input.name=key;input.oninput=guard(()=>{d.values[key]=type==='checkbox'?input.checked:input.value;saveDraft(d);if(kind==='appearance')appearance(d.values.appearance);});wrap.append(input);fields.append(wrap);};
 if(kind==='profile')field('displayName','Display name','text');else if(kind==='appearance'){field('appearance','Appearance','select');appearance(d.values.appearance);}else for(const [key,label]of [['activity','Activity'],['reminders','Reminders'],['pushPreference','Push notifications']])field(key,label,'checkbox');stack.before(fields);
}
function accountPage(){
 const d=s.gateD,a=d.account,id=route.page;
 if(d.session.status!=='active'||a.status==='deleted'){view('j27','account-entry',{title:a.status==='deleted'?'Account working state removed':'You’re using a local guest session',lead:'Your participant identity and shared expense history stay intact.',facts:[['Participant','self'],['Account capabilities','Unavailable until verified Entry result']],actions:[['Sign in through Entry',entry,'accent'],['Return to Activity',()=>go('activity')]]});return;}
 if(offline(s)||d.environment.readFailed){view('j27',offline(s)?'account-offline':'account-load-failed',{facts:[['Saved name',a.displayName],['Saved appearance',a.appearance],['Writes','Unavailable']],actions:[['Refresh current truth',()=>render(),'accent'],['Open recovery',()=>go('recovery',{owner:'account',reason:offline(s)?'OFFLINE':'READ'})]]});return;}
 if(pending(s)&&id!=='operation'){go('operation',{id:pending(s).id});return;}
 if(id==='account-overview')view('j27',id,{facts:[['Display name',a.displayName],['Notifications',a.activity?'Activity on':'Activity off'],['Appearance',a.appearance],['Session','This device · local prototype']],actions:[['Profile',()=>go('profile-overview'),'primary'],['Notifications',()=>go('notifications-overview')],['Appearance',()=>go('appearance-overview')],['Security',()=>go('security-overview')],['Delete account',()=>go('deletion-entry'),'danger']]});
 else if(['profile-overview','notifications-overview','appearance-overview','security-overview'].includes(id)){
  const kind=id.split('-')[0];const facts=kind==='profile'?[['Display name',a.displayName],['Participant identity','self · unchanged'],['History attribution','Preserved']]:kind==='appearance'?[['Saved appearance',a.appearance]]:kind==='security'?[['Session','This device only · prototype'],['Participant','self'],['Authentication provider','None connected']]:[['Activity',a.activity?'On':'Off'],['Reminders',a.reminders?'On':'Off'],['Push preference',a.pushPreference?'On':'Off'],['OS permission',d.environment.osPermission||'Not requested'],['Effective push',a.pushPreference&&d.environment.osPermission==='granted'?'Simulated only':'Off']];
  view('j27',id,{facts,actions:kind==='security'?[['Sign out',()=>go('signout-review'),'accent'],['Back to account',()=>go('account-overview')]]:[['Edit '+(kind==='profile'?'display name':kind),()=>go(kind==='appearance'?'appearance-preview':kind+'-edit'),'accent'],...(kind==='notifications'?[['System notification permission',()=>go('notification-system-boundary')]]:[]),['Back to account',()=>go('account-overview')]]});
 }else if(['profile-edit','notifications-edit','appearance-preview'].includes(id))edit(id.split('-')[0]);
 else if(id==='review'){
  const dft=s.gateD.draft;if(!dft||dft.kind!==route.kind){go('account-overview');return;}
  view('j27',dft.kind==='appearance'?'appearance-preview':dft.kind+'-review',{title:'Save these changes?',lead:'Review the exact change against the current accepted version.',notice:dft.kind==='appearance'?`Leaving without saving returns to your saved ${s.gateD.account.appearance} preference.`:'Only an accepted version-checked save changes these preferences.',facts:Object.entries(dft.values).flatMap(([k,v])=>[['Current '+k,String(s.gateD.account[k])],['New '+k,String(v)]]),actions:[['Save '+(dft.kind==='profile'?'display name':dft.kind),()=>begin(dft.kind,dft.values,dft.baseRevision),'accent'],['Back to draft',()=>go(dft.kind==='appearance'?'appearance-preview':dft.kind+'-edit')],['Cancel',()=>{repo.commit({type:'discard',actor});go('account-overview');}]]});
 }else if(id==='signout-review')view('j27',id,{facts:[['Session','This device'],['Groups, balances and history','Preserved']],actions:[['Sign out this device',()=>begin('signout'),'danger'],['Cancel',()=>go('security-overview')]]});
 else if(id==='deletion-entry'||id==='deletion-type-confirm'||id==='deletion-final-review'){
  const blockers=deletionBlockers(s);if(blockers.owners.length||blockers.money.length||blockers.pending.length){view('j27',blockers.owners.length?'deletion-blocked-owner':'deletion-blocked-money',{facts:[['Active groups you own',blockers.owners.length],['Unresolved money items',blockers.money.length+blockers.pending.length]],actions:[[blockers.owners.length?'Ownership transfer requirements':'Open balances',()=>blockers.owners.length?go('ownership-transfer-boundary'):owner('position'),'accent'],['Export first',()=>go('export-boundary')],['Refresh prerequisites',()=>render()],['Cancel',()=>go('account-overview')]]});return;}
  if(id==='deletion-entry')view('j27','deletion-review',{facts:[['Account working state','Removed locally'],['Participant and shared history','Retained'],['External data','No erasure claimed']],actions:[['Continue',()=>go('deletion-type-confirm'),'danger'],['Export first',()=>go('export-boundary')],['Cancel',()=>go('account-overview')]]});
  else if(id==='deletion-type-confirm'){const stack=view('j27',id,{title:'Type your current display name',facts:[['Current display name',a.displayName]],actions:[['Cancel',()=>go('account-overview')]]});const label=el('label','gd-field','Confirmation'),input=el('input','gd-input');input.name='confirmation';label.append(input);stack.before(label);stack.prepend(button('Check confirmation',()=>{if(input.value!==a.displayName)throw Error('Type the exact current display name.');saveDraft({kind:'deletion',values:{confirmation:input.value},baseRevision:a.revision});go('deletion-final-review');},'danger'));}
  else{const dft=d.draft;if(dft?.kind!=='deletion'){go('deletion-type-confirm');return;}view('j27',id,{facts:[['Account working state','Removed only after accepted result'],['Shared history','Retained']],actions:[['Delete local account working state',()=>begin('deletion',dft.values,dft.baseRevision),'danger'],['Cancel',()=>go('account-overview')]]});}
 }else if(['export-boundary','ownership-transfer-boundary'].includes(id))view('j27',id,{facts:[['Owner',id==='export-boundary'?'J24 · Export':'J26 · Ownership transfer'],['Integrated capability','Not implemented in Gate D'],['Current records','Unchanged']],actions:[['Return to deletion prerequisites',()=>go('deletion-entry'),'accent'],['Back to account',()=>go('account-overview')]]});
 else if(id==='notification-system-boundary')view('j27',id,{facts:[['ChopDot push preference',a.pushPreference?'On':'Off'],['System permission',d.environment.osPermission||'Not requested'],['Actual OS permission','Not changed by this prototype']],actions:[['Refresh permission status',()=>render(),'accent'],['Back to notifications',()=>go('notifications-overview')]]});
 else go('account-overview');
}
function operationPage(){const o=s.gateD.operations[route.id];if(!o)throw Error('Operation unavailable. No new operation was created.');const prefix=o.kind==='signout'?'signout':o.kind==='deletion'?'deletion':o.kind;const golden=o.status==='succeeded'?(o.kind==='signout'?'signed-out':o.kind==='deletion'?'deleted':prefix+'-saved'):o.status==='no-effect'?prefix+'-failed':prefix+'-unknown';view('j27',golden,{title:o.status==='succeeded'?'Change saved':o.status==='no-effect'?'No change was made':'Result unknown',lead:o.status==='succeeded'?'The exact reviewed change has been saved in this local prototype.':o.status==='no-effect'?'The accepted account state is unchanged. Review before trying again.':'Keep this operation reference. Reconcile its result before starting another change.',notice:'Participant identity and shared expense/payment history are preserved.',facts:[['Operation reference',o.id],['Status',o.status],['Accepted version',s.gateD.account.revision]],actions:o.status==='succeeded'?[['Back to account',()=>go('account-overview'),'accent']]:o.status==='no-effect'?[['Review safe retry',()=>{repo.commit({type:'draft',actor,kind:o.kind,values:o.values,baseRevision:s.gateD.account.revision});go(o.kind==='signout'?'signout-review':o.kind==='deletion'?'deletion-type-confirm':'review',{kind:o.kind});},'accent'],['Stop safely',()=>go('account-overview')]]:[['Check same operation',()=>go('recovery',{owner:'account',id:o.id}),'accent'],['Stop without guessing',()=>go('recovery',{owner:'account',id:o.id,stopped:'1'})]]});}
function recovery(){
 if(route.owner==='expense'){const e=s.expenses.find(e=>e.id===route.id);view('j28',route.reason==='CONFLICT'?'stale-detected':route.reason==='DUPLICATE'?'duplicate-detected':'read-failed',{facts:[['Operation reference',route.operation||'No accepted effect'],['Owner','Expense'],['Expense',e?.description||'Retained draft'],['Current revision',e?.revision||'Not yet saved']],actions:[['Return to expense owner',()=>{location.href=`../gate-b/index.html${fixture?'?fixtures=1':''}#${new URLSearchParams({page:route.returnPage||'detail',id:route.id||''})}`;},'accent'],['Stop safely',()=>go('activity')]]});return;}
 const account=route.owner!=='payment';const o=account?s.gateD.operations[route.id]:s.gateC.payments.find(p=>p.id===route.id);
 if(!account&&(!o||![o.payer,o.recipient].includes(actor)))throw Error('This payment recovery record is unavailable.');
 let id=route.stopped?'blocked-stop':route.reason==='OFFLINE'?'offline-before-action':route.reason==='READ'||route.reason==='SAVE'?'read-failed':route.reason==='CONFLICT'?'stale-detected':o?.status==='no-effect'||o?.retryEligible?'reconcile-not-found':o?.status==='succeeded'||o?.state==='closed'?'reconcile-success':o?.state==='received'||o?.state==='partial'?'partial-result':o?.state==='cancelled'?'cancelled-verified':'result-unknown';
 const status=account?o?.status||'No account operation started':o.state;
 const actions=[...(account&&route.reason==='CONFLICT'&&s.gateD.draft?[['Review against current version',()=>{const latest=repo.read(),draft=latest.gateD.draft;repo.commit({type:'draft',actor,kind:draft.kind,values:draft.values,baseRevision:latest.gateD.account.revision});go('review',{kind:draft.kind});},'accent']]:[]),['Refresh owner truth',()=>{if(account&&o)repo.commit({type:'reconcile',actor,id:o.id});render();},'accent'],['Return to owning journey',()=>account?go(o?'operation':'account-overview',o?{id:o.id}:{}):owner('payment',o.id)],['Stop without guessing',()=>go('recovery',{owner:route.owner,id:route.id||'',reason:route.reason||'',stopped:'1'})]];
 view('j28',id,{facts:[['Operation reference',o?.id||'No effect started'],['Owner',account?'Account & preferences':'Payment'],['Current status',status],...(!account?[['Accepted amount',money({v:1,minorUnits:o.confirmed,currency:o.currency,exponent:o.exponent})],['Payment identity',o.idempotencyKey]]:[])],actions});
 if(fixture&&o&&['unknown','pending'].includes(o.status)){const card=el('div','gd-message','Prototype external-result fixtures · same operation only');for(const [label,result]of [['Still pending','pending'],['Verified no effect','no-effect'],['Verified saved','succeeded']])card.append(button(label,()=>{repo.commit({type:'reconcile',actor,id:o.id,result},'prototype-fixture');const latest=repo.read();if(latest.gateD.session.status==='signed-out')entry();else render();}));content.append(card);}
 // Payment result acceptance stays in the existing payer/recipient/fixture owner UI.
 if(!account)notice('Recovery does not execute settlement. Reopen the same payment to inspect receipt, cancellation or retry eligibility.');
}
function fixtures(){const bar=document.querySelector('#fixtures');if(!fixture)return;bar.hidden=false;document.body.classList.add('fixture-mode');bar.replaceChildren(el('b','','Gate D · explicit local preconditions'));
 const select=el('select');select.setAttribute('aria-label','Fixture actor');for(const p of [{id:'self',name:'You'},...s.people]){const n=el('option','',p.name);n.value=p.id;select.append(n);}select.value=actor;select.onchange=()=>{actor=select.value;sessionStorage.setItem('chopdot.gate-b.actor',actor);go('activity');};bar.append(select);
 for(const [key,label]of [['offline','Offline'],['readFailed','Read failure'],['failSave','Known save failure'],['unknown','Unknown result']]){const wrap=el('label','',label),input=el('input');input.type='checkbox';input.checked=!!s.gateD.environment[key];input.onchange=guard(()=>{repo.commit({type:'fixture',patch:{[key]:input.checked}},'prototype-fixture');render();});wrap.prepend(input);bar.append(wrap);}
 if(s.gateD.session.status==='guest')bar.append(button('Verified local Entry fixture',()=>{repo.commit({type:'entry'},'entry-verified');render();}));
 if(route.page==='notification-system-boundary')for(const v of ['granted','denied'])bar.append(button('OS fixture: '+v,()=>{repo.commit({type:'fixture',patch:{osPermission:v}},'prototype-fixture');render();}));
 document.documentElement.style.setProperty('--fixture-height',bar.offsetHeight+'px');}
function render(){try{s=repo.read();route=Object.fromEntries(new URLSearchParams(location.hash.slice(1)));route.page||='activity';appearance(s.gateD.account.appearance);if(['signed-out','expired'].includes(s.gateD.session.status)||s.gateD.account.status==='deleted'){entry();return;}available(s,actor);
 if(['activity','notifications'].includes(route.page))activityPage();else if(route.page==='recovery')recovery();else if(route.page==='operation')operationPage();else if(route.page==='changed')view('j28','conflict-current',{title:'This item has changed',lead:'The delivery copy is older than the current record. Open the owner to see its current state.',facts:[['Old action','Not replayed']],actions:[['Open current record',()=>{const target=openItem(repo.read(),{owner:route.owner,recordId:route.id},actor);owner(target.owner,target.id,target.group);},'accent'],['Back to Activity',()=>go('activity')]]});else accountPage();
 fixtures();screen?.focus({preventScroll:true});if(parent!==window)parent.postMessage({type:'chopdot-gate-d-route',hash:location.hash||'#page=activity'},location.origin);
 }catch(e){error(e);}}
window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key==='chopdot.preview-v2.guest')render();});render();
