import '../gate-b/browser-launch.mjs';import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {serve} from '../gate-b/test-server.mjs';
const root=process.env.PREVIEW_ROOT||resolve(new URL('../../..',import.meta.url).pathname),out=process.env.EVIDENCE_DIR||'/tmp/chopdot-gate-d-browser';mkdirSync(out,{recursive:true});const host=await serve(root),browser=await chromium.launch({headless:true});
const report={status:'RUNNING',browser:browser.version(),flow:'Activity → owner → Account drafts/save/reconcile → signout → Entry',checks:[],consoleErrors:[],screenshots:[]};let page,context;
const check=(id,fn)=>{fn();report.checks.push({id,status:'PASS'});};
const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest')));
const button=label=>page.getByRole('button',{name:label,exact:true}).click();
const go=async hash=>{await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-d/index.html?fixtures=1#${hash}`);await page.locator('#app > *').waitFor();};
const screen=async id=>page.waitForFunction(id=>document.querySelector('#content')?.dataset.testState===id,id);
const shot=async name=>{const path=`${out}/${name}.png`;await page.screenshot({path});report.screenshots.push(path);};
async function scene(width=393){context=await browser.newContext({viewport:{width,height:width===430?890:852}});page=await context.newPage();page.on('pageerror',e=>report.consoleErrors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=position`);await button('Add Golden example');await page.locator('.person-row').first().waitFor();await go('page=activity');}
try{
 await scene();check('GD-B01-page-identity',()=>assert.match(awaitlessTitle(),/./));
 const before=await state();await page.getByRole('link',{name:'Notifications',exact:true}).click();await button('Mark all read');const read=await state();check('GD-B02-mark-read-preserves-owners',()=>{assert.deepEqual(read.expenses,before.expenses);assert.deepEqual(read.gateC,before.gateC);assert.ok(Object.keys(read.gateD.read.self).length);});await page.reload();await page.locator('[data-unread-label]').waitFor();const reloaded=await state();check('GD-B03-read-persists',()=>assert.deepEqual(reloaded.gateD.read,read.gateD.read));await shot('notifications-393');
 await go('page=activity&filter=payments');check('GD-B04-empty-payments',()=>assert.equal((before.gateC.payments||[]).length,0));await page.getByText('No activity yet.',{exact:false}).waitFor();
 await go('page=activity');await page.locator('.j18-row').first().click();await page.waitForURL(/gate-b\/index/);await page.locator('#app>.screen').waitFor();check('GD-B05-opens-owning-expense',()=>assert.match(page.url(),/page=detail/));
 await go('page=account-overview');await button('Verified local Entry fixture');await screen('account-overview');await button('Profile');await button('Edit display name');await page.getByRole('textbox',{name:'Display name',exact:true}).fill('Morgan');await button('Review');await page.reload();await screen('profile-review');const draftState=await state();check('GD-B06-draft-reload-unaccepted',()=>{assert.equal(draftState.gateD.account.displayName,'You');assert.equal(draftState.gateD.draft.values.displayName,'Morgan');});await button('Save display name');await screen('profile-saved');let current=await state();check('GD-B07-profile-preserves-business',()=>{assert.equal(current.gateD.account.displayName,'Morgan');assert.deepEqual(current.expenses,before.expenses);assert.deepEqual(current.people,before.people);});await shot('profile-saved-393');
 await button('Back to account');await button('Appearance');await button('Edit appearance');await page.getByRole('combobox',{name:'Appearance',exact:true}).selectOption('Dark');current=await state();check('GD-B08-preview-not-saved',()=>assert.equal(current.gateD.account.appearance,'System'));await button('Cancel');await screen('appearance-overview');current=await state();const theme=await page.locator('html').getAttribute('data-appearance');check('GD-B09-cancel-restores-appearance',()=>{assert.equal(current.gateD.account.appearance,'System');assert.equal(theme,'Light');});
 await button('Edit appearance');await page.getByRole('combobox',{name:'Appearance',exact:true}).selectOption('Dark');await button('Review');await button('Save appearance');await screen('appearance-saved');await page.reload();current=await state();check('GD-B10-accepted-appearance-reloads',()=>assert.equal(current.gateD.account.appearance,'Dark'));await shot('dark-saved-393');
 await button('Back to account');await button('Notifications');await button('Edit notifications');await page.getByRole('checkbox',{name:'Push notifications',exact:true}).check();await button('Review');await button('Save notifications');await screen('notifications-saved');await button('Back to account');await button('Notifications');await button('System notification permission');await button('OS fixture: denied');current=await state();check('GD-B11-system-permission-separate',()=>{assert.equal(current.gateD.account.pushPreference,true);assert.equal(current.gateD.environment.osPermission,'denied');});
 await go('page=account-overview');await page.getByRole('checkbox',{name:'Offline',exact:true}).check();await screen('account-offline');await shot('offline-393');await page.getByRole('checkbox',{name:'Offline',exact:true}).uncheck();await screen('account-overview');
 await button('Profile');await button('Edit display name');await page.getByRole('textbox',{name:'Display name'}).fill('Unknown Morgan');await button('Review');await page.getByRole('checkbox',{name:'Unknown result',exact:true}).check();await button('Save display name');await screen('profile-unknown');const op=(await state()).gateD.operations;const pending=Object.values(op).find(o=>o.status==='unknown');await button('Check same operation');await screen('result-unknown');await page.reload();await screen('result-unknown');await button('Still pending');current=await state();check('GD-B12-unknown-reload-same-operation',()=>{assert.equal(current.gateD.operations[pending.id].status,'unknown');assert.equal(current.gateD.account.displayName,'Morgan');});await shot('unknown-recovery-393');await button('Verified no effect');await screen('reconcile-not-found');await button('Return to owning journey');await screen('profile-failed');await page.getByRole('checkbox',{name:'Unknown result',exact:true}).uncheck();await button('Review safe retry');await button('Save display name');await screen('profile-saved');current=await state();check('GD-B13-no-effect-retry-one-new-operation',()=>{assert.equal(current.gateD.account.displayName,'Unknown Morgan');assert.equal(current.gateD.operations[pending.id].status,'no-effect');});
 await button('Back to account');await button('Delete account');await screen('deletion-blocked-owner');check('GD-B14-deletion-real-prerequisites',()=>assert.ok(current.groups.length));await shot('deletion-blocked-393');await button('Cancel');await button('Security');await button('Sign out');await button('Sign out this device');await page.waitForURL(/index.html\?entry=signin/);await page.locator('#product-frame').waitFor();current=await state();check('GD-B15-signout-preserves-business',()=>{assert.equal(current.gateD.session.status,'signed-out');assert.deepEqual(current.expenses,before.expenses);});await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-c/index.html#page=position`);await page.waitForURL(/index.html\?entry=signin/);check('GD-B16-direct-link-session-guard',()=>assert.equal(current.gateD.session.status,'signed-out'));await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-b/index.html#page=group`);await page.waitForURL(/index.html\?entry=signin/);check('GD-SEC-001-Gate-B-direct-link-blocked',()=>assert.match(page.url(),/entry=signin/));await context.close();
 await scene(430);await shot('activity-430');await go('page=account-overview');await button('Verified local Entry fixture');await screen('account-overview');await shot('account-430');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);check('GD-B17-no-horizontal-overflow',()=>assert.equal(overflow,false));await context.close();
 check('GD-B18-browser-health',()=>assert.deepEqual(report.consoleErrors,[]));report.status='PASS';
}catch(e){report.status='FAIL';report.error=e.stack;console.error(e);if(page)await shot('failure').catch(()=>{});process.exitCode=1;}finally{writeFileSync(`${out}/results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,error:report.error},null,2));await browser.close();await host.close();}
function awaitlessTitle(){return page.url();}
