import '../gate-b/browser-launch.mjs';import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {serve} from '../gate-b/test-server.mjs';
const root=process.env.PREVIEW_ROOT||resolve(new URL('../../..',import.meta.url).pathname),out=process.env.EVIDENCE_DIR||'/tmp/chopdot-gate-d-recovery';mkdirSync(out,{recursive:true});const host=await serve(root),browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:393,height:852}}),page=await context.newPage();const report={status:'RUNNING',checks:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));const check=(id,fn)=>{fn();report.checks.push({id,status:'PASS'});};const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest'))),btn=name=>page.getByRole('button',{name,exact:true}).click(),screen=id=>page.waitForFunction(id=>document.querySelector('#content')?.dataset.testState===id,id);
const go=async hash=>{await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-d/index.html?fixtures=1#${hash}`);await page.locator('#app>*').waitFor();};
try{
 await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-c/index.html?fixtures=1#page=position`);await btn('Add Golden example');await page.locator('.person-row').first().waitFor();
 // Set up accepted payment owner milestones through the real transition API, not an Activity result store.
 const id=await page.evaluate(async()=>{const {transition,scopeProof}=await import('./model.js');let s=JSON.parse(localStorage.getItem('chopdot.preview-v2.guest'));const id='gd-payment',step=(type,extra={},authority='user')=>s=transition(s,{type,id,actor:'self',operationId:crypto.randomUUID(),...extra},authority);
 step('prepare',{idempotencyKey:'gd-key',scope:{payer:'self',recipient:'gc-jeanine',currency:'CHF',exponent:2,groupIds:['gc-apartment','gc-ski'],kind:'person'},amount:'5430',method:'TWINT',reviewed:true,plan:{useOffsets:true}});step('start');step('sent');step('confirm',{actor:'gc-jeanine',amount:'4000'});step('close',{proof:scopeProof(s.gateC.payments[0])},'prototype-fixture');localStorage.setItem('chopdot.preview-v2.guest',JSON.stringify(s));return id;});
 await go('page=activity');const before=await state();const waitRow=page.locator('.j18-row').filter({hasText:'Payment waiting'});await waitRow.click();await screen('conflict-current');await btn('Open current record');await page.waitForURL(/gate-c\/index.*page=payment/);await page.getByRole('link',{name:'Recovery options',exact:true}).click();await screen('partial-result');const partial=await state();check('GD-R01-stale-payment-routes-current-owner',()=>assert.deepEqual(partial.gateC,before.gateC));await page.getByRole('link',{name:'Back',exact:true}).click();await page.waitForURL(/gate-c\/index.*page=payment/);check('GD-REC-002-payment-back-returns-owner',()=>assert.match(page.url(),/page=payment/));
 await go('page=activity');const amounts=await page.locator('.j18-row').filter({hasText:'Open payment remainder'}).innerText();check('GD-SEC-004-actual-remainder-row',()=>assert.match(amounts,/14\.30/));const accepted=await page.locator('.j18-row').filter({hasText:'Payment partly completed'}).innerText();check('GD-R02-accepted-partial-row',()=>assert.match(accepted,/40\.00/));
 await go('page=account-overview');await btn('Verified local Entry fixture');await btn('Profile');await btn('Edit display name');await page.getByRole('textbox',{name:'Display name'}).fill('Reviewed draft');await btn('Review');
 await page.evaluate(async()=>{const {repository}=await import('./model.js');const r=repository(localStorage);r.commit({type:'begin',id:'newer-profile',kind:'profile',values:{displayName:'Newer account'},baseRevision:r.read().gateD.account.revision});});await btn('Save display name');await page.getByRole('alert').waitFor();await btn('Open recovery');await screen('stale-detected');const newer=await state();check('GD-R03-stale-save-preserves-newer',()=>assert.equal(newer.gateD.account.displayName,'Newer account'));
 // The owner's accepted other write clears draft. Re-enter review explicitly after observing current truth.
 await btn('Return to owning journey');await btn('Profile');await btn('Edit display name');await page.getByRole('textbox',{name:'Display name'}).fill('After refresh');await btn('Review');await page.getByRole('checkbox',{name:'Known save failure'}).check();await btn('Save display name');await screen('profile-failed');const failed=await state();check('GD-R04-known-failure-not-accepted',()=>assert.equal(failed.gateD.account.displayName,'Newer account'));await page.getByRole('checkbox',{name:'Known save failure'}).uncheck();await btn('Review safe retry');await btn('Save display name');await screen('profile-saved');
 await btn('Back to account');await btn('Profile');await btn('Edit display name');await page.getByRole('link',{name:'Back',exact:true}).click();await screen('account-overview');check('GD-REC-002-profile-back-account',()=>assert.match(page.url(),/account-overview/));await btn('Delete account');await btn('Export first');await screen('export-boundary');const exportText=await page.locator('#content').innerText();check('GD-REC-004-export-boundary-reachable',()=>assert.match(exportText,/Not implemented in Gate D/));
 await go('page=account-overview');await page.getByRole('checkbox',{name:'Read failure'}).check();await screen('account-load-failed');await btn('Open recovery');await screen('read-failed');await page.getByRole('checkbox',{name:'Read failure'}).uncheck();await btn('Return to owning journey');await screen('account-overview');check('GD-R05-read-failure-retry-owner',()=>assert.equal(report.errors.length,0));
 // Test deletion only against a new empty synthetic context. Existing user or shared history is never erased.
 const empty=await browser.newContext({viewport:{width:430,height:890}}),p2=await empty.newPage();await p2.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-d/index.html?fixtures=1#page=account-overview`);await p2.getByRole('button',{name:'Verified local Entry fixture'}).click();await p2.getByRole('button',{name:'Delete account',exact:true}).click();await p2.getByRole('button',{name:'Continue',exact:true}).click();await p2.getByRole('textbox',{name:'Confirmation'}).fill('Wrong');await p2.getByRole('button',{name:'Check confirmation'}).click();await p2.getByRole('alert').waitFor();await p2.getByRole('textbox',{name:'Confirmation'}).fill('You');await p2.getByRole('button',{name:'Check confirmation'}).click();await p2.getByRole('button',{name:'Delete local account working state'}).click();await p2.waitForURL(/entry=signin/);const removed=await p2.evaluate(()=>JSON.parse(localStorage.getItem('chopdot.preview-v2.guest')));check('GD-R06-typed-prototype-deletion',()=>{assert.equal(removed.gateD.account.status,'deleted');assert.deepEqual(removed.expenses,[]);assert.equal(removed.gateD.history.length,1);});await empty.close();
 check('GD-R07-browser-health',()=>assert.deepEqual(report.errors,[]));report.status='PASS';
}catch(e){report.status='FAIL';report.error=e.stack;console.error(e);await page.screenshot({path:`${out}/failure.png`}).catch(()=>{});process.exitCode=1;}finally{writeFileSync(`${out}/results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,checks:report.checks.length,error:report.error}));await browser.close();await host.close();}
