import '../gate-b/browser-launch.mjs';import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';import {serve} from '../gate-b/test-server.mjs';
const root=process.env.PREVIEW_ROOT||resolve(new URL('../../..',import.meta.url).pathname),out=process.env.EVIDENCE_DIR||'/tmp/chopdot-gate-d-visual';mkdirSync(out,{recursive:true});const host=await serve(root),browser=await chromium.launch({headless:true}),report={status:'RUNNING',pairs:[],errors:[],scope:'Approved Golden layout and control hierarchy at393x852 and430x890; dynamic records differ deliberately. Screenshots require human/agent visual inspection; no pixel-identical claim.'};
try{for(const [width,height]of [[393,852],[430,890]]){const context=await browser.newContext({viewport:{width,height}}),page=await context.newPage(),golden=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-d/index.html#page=activity`);
 await page.evaluate(async()=>{const {repository}=await import('./model.js');repository(localStorage).commit({type:'entry'},'entry-verified');});
 for(const [j,state,hash]of [['j18','activity','page=activity'],['j27','account-overview','page=account-overview'],['j27','profile-edit','page=profile-edit'],['j28','read-failed','page=recovery&owner=account&reason=READ']]){
 await page.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-d/index.html#${hash}`);await page.locator('#app>*').waitFor();await golden.goto(`${host.base}/prototypes/integrated-product-preview-v2/gate-d/goldens/${j}.html#${state}`);
 await golden.addStyleTag({content:`html,body{margin:0!important;padding:0!important}.lab,.stage{display:block!important;padding:0!important;margin:0!important}.review-rail{display:none!important}.device{width:${width}px!important;height:${height}px!important;max-height:none!important;border:0!important;border-radius:0!important;box-shadow:none!important;margin:0!important}.demo-btn{visibility:hidden!important}`});
 const current=`${out}/${j}-${state}-${width}-integrated.png`,reference=`${out}/${j}-${state}-${width}-golden.png`;await page.screenshot({path:current});await golden.screenshot({path:reference});
 const metrics=await page.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,heading:document.querySelector('h1,.j18-title,.status-card>b')?.textContent,controls:[...document.querySelectorAll('#app a,#app button')].filter(n=>n.getBoundingClientRect().width).length}));assert.equal(metrics.overflow,false);assert.ok(metrics.heading);assert.ok(metrics.controls>2);report.pairs.push({j,state,width,height,integrated:current,golden:reference,metrics});
 }await context.close();}assert.deepEqual(report.errors,[]);report.status='PASS';}catch(e){report.status='FAIL';report.error=e.stack;process.exitCode=1;}finally{writeFileSync(`${out}/results.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,pairs:report.pairs.length,error:report.error}));await browser.close();await host.close();}
