import {publishPrototypeRoute} from '../prototype-route.js';
import {createQRUI} from './qr-ui.js';
import {createWalletUI} from './wallet-ui.js';
import {createPortabilityUI} from './portability-ui.js';
import {createLifecycleUI} from './lifecycle-ui.js';
import {createInsightsUI} from './insights.js';
import {createSavingsUI} from './savings-ui.js';
import {repository,activeMembers,visibleGroups,access,group,name,requestSnapshot,requestStatus,relationship,removalBlock,money,shareStatus,METHOD_FIELDS} from './model.js';
import {peopleProjection,requestProjection,receiveProjection} from './adapters.js';
import {renderPeople} from './render-09.js';
import {renderRequest} from './render-13.js';
import {renderReceive} from './render-14.js';
import {currentActor,signFixture,consumeFixture} from '../create-join/authority.js';
import {requirePrototypeWriter,assertPrototypeWriter} from '../prototype-writer.js';
import {repository as settlementRepository} from '../gate-c/model.js';
await requirePrototypeWriter();
const repo=repository(localStorage,assertPrototypeWriter), ledger=settlementRepository(localStorage,assertPrototypeWriter),actor=currentActor(),device=document.querySelector('#device');
const fixture=new URLSearchParams(location.search).has('fixtures'),docs={};
for(const id of ['09','13','14','15','16','17','19','20','21','22','23','24','25','26'])docs[id]=new DOMParser().parseFromString(await (await fetch('./authority/j'+id+'.html')).text(),'text/html');
const defs={};for(const id of ['24','25','26'])defs[id]=await(await fetch('./authority/j'+id+'-states.json')).json();
const QR_DATA=await(await fetch('./authority/receive-qr.json')).json();
let route={},trail=[],s=repo.read(),view,alert='';
const qrUI=createQRUI(()=>({s,actor,route,device,staticScreen,esc,name,money,push,go,owner,fixture}));
const walletUI=createWalletUI(()=>({s,actor,route,device,staticScreen,esc,money,name,commit,push,owner,ledger}));
const portabilityUI=createPortabilityUI(()=>({s,actor,route,docs,defs,device,esc,staticScreen,commit,prepare,submit,push,go}));
const lifecycleUI=createLifecycleUI(()=>({s,actor,route,docs,defs,device,esc,name,commit,prepare,submit,push,go,owner}));
const insightsUI=createInsightsUI(()=>({s,actor,route,staticScreen,device,esc,money,push,owner,ledger}));
const savingsUI=createSavingsUI(()=>({s,actor,route,staticScreen,device,esc,money,name,commit,prepare,submit,push,go}));
const parse=()=>Object.fromEntries(new URLSearchParams(location.hash.slice(1)));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function push(patch={},replace=false){const prior=s.expansion.operations[route.operation];if(patch.operation===''&&prior?.actor===actor&&prior.status==='prepared')commit({type:'cancel',id:prior.id});if(!replace)trail.push({...route});route=Object.fromEntries(Object.entries({...route,...patch}).filter(([,v])=>v!==undefined&&v!==null));const hash='#'+new URLSearchParams(route);history[replace?'replaceState':'pushState'](null,'',hash);publishPrototypeRoute('chopdot-expansion-route',hash);render();}
function go(family,page,extra={}){push({family,page,person:'',id:'',operation:'',...extra});}
function commit(c,authority){const command=signFixture(repo.read(),{...c,actor,operationId:crypto.randomUUID()});const state=repo.commit(command,authority);consumeFixture(command);s=state;return state;}
function owner(path,hash){if(route.group&&access(s,actor,route.group))ledger.selectGroup(route.group);location.href=`../${path}/index.html${fixture?'?fixtures=1':''}${hash}`;}
function back(){const pending=s.expansion.operations[route.operation];if(pending?.status==='prepared')commit({type:'cancel',id:pending.id});const previous=trail.pop();if(previous){if(pending?.status==='prepared'&&previous.operation===pending.id)previous.operation='';push(previous,true);}else if(route.family==='09'&&route.page==='members')owner('gate-b','#page=group');else go('09','members',{group:route.group||s.group?.id});}
function shell(id,d){document.querySelector('#golden-style').textContent=[...docs[id].querySelectorAll('style')].map(n=>n.textContent).join('\n');device.innerHTML=`<section class="screen mp-screen ${id==='13'?'rq-screen':''}" data-journey="J${id}" data-route="${esc(route.page)}"><header class="detail-header"><button class="icon-btn" data-action="back" aria-label="Back">${d.icon('back')}</button><div class="header-title"><b>${esc(d.header)}</b><span>${esc(d.sub)}</span></div></header><main class="app-content">${d.body}</main><footer class="focus-footer"><div class="footer-stack">${d.foot}</div></footer></section>`;}
function records(){return (s.gateC?.payments||[]).filter(p=>[p.payer,p.recipient].includes(actor)&&(!route.group||p.groupIds.includes(route.group)));}
function historyView(){
 const payments=records(),chosen=payments.find(p=>p.id===route.id),status=p=>p.state==='closed'?'Complete':p.state==='partial'?'Partial':['returned','reversed'].includes(p.state)?'Reversed':p.state==='cancelled'?'Cancelled':['failed','expired'].includes(p.state)?'Failed':'Waiting';
 const screen=staticScreen('15',chosen?(status(chosen)==='Cancelled'?'failed':status(chosen).toLowerCase()):'all'),main=screen.querySelector('main'),footer=screen.querySelector('footer');
 main.replaceChildren();footer.replaceChildren();const action=(label,act,cls='primary')=>`<button class="${cls}" data-action="${act}">${esc(label)}</button>`;
 if(!chosen){main.innerHTML='<div class="section-head"><h2 class="h2">Recent payments</h2><span>Read only</span></div><div class="segmented" role="group" aria-label="Payment status"></div><div class="card list-card"></div>';const filters=main.querySelector('.segmented');for(const f of ['All','Complete','Partial','Waiting','Failed','Reversed','Cancelled']){const b=document.createElement('button');b.className='segment'+((route.filter||'All')===f?' active':'');b.textContent=f;b.dataset.action='history-filter';b.dataset.filter=f;filters.append(b);}const list=main.querySelector('.list-card');
 for(const p of payments.filter(p=>!route.filter||route.filter==='All'||route.filter===status(p))){const retained=p.groupIds.some(g=>!access(s,actor,g)),b=document.createElement('button');b.className='list-row';b.dataset.action='payment-record';b.dataset.id=p.id;b.innerHTML=`<div class="status-icon ${status(p)==='Complete'?'':'wait'}">${esc(status(p).slice(0,1))}</div><div class="row-main"><b>${esc(p.payer===actor?'You paid '+name(s,p.recipient):name(s,p.payer)+' paid you')}</b><span>${esc(p.method)} · ${retained?'Retained payment record':p.groupIds.map(g=>esc(group(s,g)?.name||'Former group')).join(' · ')}</span></div><div><div class="amount">${money(p.confirmed,p.currency,p.exponent)}</div><div class="pill2">${status(p)}</div></div>`;list.append(b);}if(!list.childElementCount)list.innerHTML='<div class="info gray">No payment records in this view. Requests and copies do not create payments.</div>';
 main.insertAdjacentHTML('beforeend','<div class="info gray"><span aria-hidden="true">ⓘ</span><div>History explains what happened. It cannot retry, confirm, reverse or edit a payment.</div></div>');footer.innerHTML=action('Back','back');
 }else{const retained=chosen.groupIds.some(g=>!access(s,actor,g)),original=BigInt(chosen.original||chosen.amount),confirmed=BigInt(chosen.confirmed||0),remaining=original-confirmed;main.innerHTML=`<div class="card summary-card"><div class="summary-hero"><h2>${money(confirmed,chosen.currency,chosen.exponent)} confirmed</h2><p>${esc(status(chosen))} · ${esc(chosen.method)}</p></div><div class="fact"><span>Original balance</span><b>${money(original,chosen.currency,chosen.exponent)}</b></div><div class="fact"><span>Confirmed</span><b>${money(confirmed,chosen.currency,chosen.exponent)}</b></div><div class="fact"><span>Still open</span><b>${money(remaining,chosen.currency,chosen.exponent)}</b></div><div class="fact"><span>Reference</span><b>${esc(chosen.id)}</b></div></div>`;
 const events=(s.gateC.history||[]).filter(h=>h.paymentId===chosen.id),timeline=document.createElement('div');timeline.className='card status-card';timeline.innerHTML='<div class="timeline"></div>';for(const h of events){const row=document.createElement('div');row.className='timeline-row done';const labels={'cancel':'Cancelled before execution','expire':'Expired before execution','start':'Payment started','confirm':'Receipt confirmed','prepare':'Payment reviewed','sent':'Sent','confirm-receipt':'Receipt confirmed','close':'Payment item closed','return':'Returned','wallet-result':'Wallet result checked'};row.innerHTML=`<b>${esc(labels[h.type]||h.type.replaceAll('-',' '))}</b>${esc(h.at||'Recorded in this prototype')}`;timeline.firstElementChild.append(row);}if(!events.length)timeline.firstElementChild.innerHTML='<div class="timeline-row"><b>Recorded result</b>Earlier step timing is unavailable in this record.</div>';main.append(timeline);
 main.insertAdjacentHTML('beforeend',`<div class="info gray"><span aria-hidden="true">ⓘ</span><div>${retained?'Group access ended. This minimal participating payment record is retained; group expenses, people and private details are unavailable.':'The remainder belongs to the current balance. History does not execute payments.'}</div></div>`);if(!retained)footer.innerHTML=action(status(chosen)==='Waiting'?'Open owning payment':'View remaining balance',status(chosen)==='Waiting'?'payment':'history-balance');footer.innerHTML+=action('Back to history','history','secondary-btn');}
}
function staticScreen(id,page){const doc=docs[id],source=doc.getElementById(page);if(!source)throw Error('Approved state is unavailable: '+id+'/'+page);document.querySelector('#golden-style').textContent=[...doc.querySelectorAll('style')].map(n=>n.textContent).join('\n');const screen=source.cloneNode(true);screen.classList.add('active');screen.style.setProperty('display','grid','important');screen.querySelectorAll('script').forEach(n=>n.remove());const symbols=doc.querySelector('body>svg');device.replaceChildren(...(symbols?[symbols.cloneNode(true)]:[]),screen);screen.querySelectorAll('a').forEach(a=>{a.removeAttribute('href');a.setAttribute('role','button');a.setAttribute('tabindex','0');a.dataset.action=a.closest('footer')?(a.classList.contains('add-tab')?'expense-home':a.textContent.includes('People')?'people-home':a.textContent.includes('Activity')?'activity-home':a.textContent.includes('You')?'account-home':'global-home'):'back';});screen.querySelectorAll('[data-action="demo"],.demo-btn,.demo').forEach(n=>n.remove());return screen;}
function methodView(){const m=s.expansion.methods.find(m=>m.id===route.id&&m.owner===actor&&!m.removed),candidate=s.expansion.operations[route.operation],o=candidate?.actor===actor?candidate:null;const variant=(m?.method||route.method||'Bank transfer')==='Bank transfer'?'bank':(m?.method||route.method)==='TWINT'?'twint':(m?.method||route.method)==='PayPal'?'paypal':'crypto';const status=o?.status;
 const page=o&&status!=='prepared'?(status==='succeeded'?o.kind==='method-remove'?'remove-accepted':'save-accepted':status==='no-effect'?'save-failed':'save-unknown'):route.page==='detail'?'detail-'+variant:route.page==='edit'?'edit-'+variant:route.page==='add'?'add-'+variant:route.page==='review'?'review-new-'+variant:route.page==='remove-confirm'?'remove-confirm':s.expansion.methods.some(m=>m.owner===actor&&!m.removed)?'overview':'empty';
 const screen=staticScreen('20',page),main=screen.querySelector('main'),footer=screen.querySelector('footer');main.replaceChildren();footer.replaceChildren();footer.className='j20-footer';const button=(label,action,cls='primary')=>{const b=document.createElement('button');b.className=cls==='primary'?'j20-primary':cls==='secondary'?'j20-secondary':cls.includes('danger')?'j20-danger':cls;b.textContent=label;b.dataset.action=action;footer.append(b);return b;};const heading=(title,copy)=>{main.innerHTML=`<div class="j20-form-title"><h1>${esc(title)}</h1><p>${esc(copy)}</p></div>`;const header=screen.querySelector('.header-title b');if(header)header.textContent=title;};const rows=items=>{const card=document.createElement('section');card.className='card j20-review';card.innerHTML='<div class="j20-facts">'+items.map(([k,v])=>`<div class="j20-fact"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')+'</div>';main.append(card);};
 if(o&&status!=='prepared'){heading(status==='succeeded'?(o.kind==='method-remove'?'Payment method removed':'Payment method saved'):status==='no-effect'?'No change saved.':'Still checking.',status==='succeeded'?(o.kind==='method-remove'?'It is no longer available for future payment/share handoffs. Existing settlement history retains the destination version used.':'The accepted destination is readable as its own version. No payment or balance changed.'):'Reconcile this same operation before retrying.');rows([['Operation',o.id],['Status',o.status]]);if(status==='no-effect')button('Retry same operation','method-retry');if(['pending','unknown'].includes(status))button('Check status','method-recover');button('Back to methods','methods','secondary');return;}
 if(['add','edit'].includes(route.page)){const method=m?.method||route.method||'Bank transfer';heading(m?'Update '+(m.fields.find(f=>f[0]==='Label')?.[1]||m.method):method==='Bank transfer'?'Add your '+(route.currency||'CHF')+' account':method==='Wallet'?'Add a receiving destination':'Add '+method,m?'This saved destination is currently version v'+m.version+'.':method==='TWINT'?'Use a phone number or supported handle.':method==='Wallet'?'Choose the exact asset and network. This is not wallet connection.':'Use the destination you want to receive with.');const d=s.expansion.drafts[actor+':method'],values=d?.id===(m?.id||'new')?d:m||{id:'new',method,currency:method==='Wallet'?'DOT':'CHF',exponent:method==='Wallet'?6:2,fields:[],visible:true,preferred:false};const form=document.createElement('div');form.className='j20-form';const required=method==='Bank transfer'?['Label','Account holder','IBAN','Reference note']:method==='TWINT'?['Label','Phone','Handle']:method==='PayPal'?['Label','Email','Username']:['Label','Public address','Network'];
  for(const field of ['Currency',...required]){const label=document.createElement('label');label.className='j20-field';const title=document.createElement('span');title.textContent=field;label.append(title);const input=document.createElement('input');input.name=field;input.className='j20-input';input.setAttribute('aria-label',field);input.value=field==='Currency'?values.currency:values.fields.find(r=>r[0]===field)?.[1]||'';label.append(input);form.append(label);}for(const [key,title]of [['visible','Available to receive'],['preferred','Preferred for matching currency/network']]){const label=document.createElement('label');label.className='j20-field';const span=document.createElement('span');span.textContent=title;label.append(span);const input=document.createElement('input');input.name=key;input.type='checkbox';input.checked=values[key];label.append(input);form.append(label);}main.append(form);main.insertAdjacentHTML('beforeend','<div class="j20-note gray"><span aria-hidden="true">ⓘ</span><div>Full values stay owner-only here. Other people see only masked context until a payment/share flow authorizes disclosure. These local receiving records do not verify real account ownership.</div></div>');button('Review method','method-review');button('Cancel','methods','secondary');return;
 }
 if(route.page==='review'&&o){heading('Before saving','Confirm the exact destination and how it can be suggested.');rows([['Method',o.payload.method],['Currency',o.payload.currency],...o.payload.fields,['Available',o.payload.visible?'Yes':'No'],['Suggested',o.payload.preferred?'Compatible contexts only':'No']]);button('Save method','method-submit');button('Edit details','method-edit-review','secondary');return;}
 if(route.page==='remove-confirm'&&m){heading('Remove this method?','Old sharing references will stop showing these details. Copies cannot be recalled. Requests and payments stay unchanged.');rows([['Method',m.method],['Currency',m.currency]]);button('Remove method','method-remove','primary danger');button('Keep method','method-detail','secondary');return;}
 if(route.page==='detail'&&m){heading(m.fields.find(f=>f[0]==='Label')?.[1]||m.method,'Only your receiving fields. Saved destinations do not connect a wallet or authorize payment.');rows([['Method',m.method],['Currency',m.currency],...m.fields,['Version',m.version],['Available',m.visible?'Yes':'No'],['Preference',m.preferred?'Compatible asset/network only':'None']]);button('Edit method','method-edit');button('Share receiving details','receive');button('Remove method','method-remove-review','text-link danger');button('Back to methods','methods','secondary');return;}
 heading('How people can pay you.','Saved methods stay separate from authentication, wallet connection and payment execution.');const list=s.expansion.methods.filter(m=>m.owner===actor&&!m.removed);for(const m of list){const b=document.createElement('button');b.className='j20-method';b.dataset.action='method-detail';b.dataset.id=m.id;const target=m.fields.find(f=>['IBAN','Phone','Handle','Email','Username','Public address'].includes(f[0]))?.[1]||'';b.innerHTML=`<div class="j20-method-copy"><div class="j20-method-title"><b>${esc(m.fields.find(f=>f[0]==='Label')?.[1]||m.method)}</b>${m.preferred?'<span class="j20-pill good">Suggested</span>':''}</div><span>${esc(m.currency)} · •••• ${esc(target.slice(-4))}</span><small>${m.visible?'Available to receive':'Not shared for receiving'}</small></div>`;main.append(b);}if(!list.length)rows([['Saved receiving methods','None']]);for(const method of Object.keys(METHOD_FIELDS)){const b=button('Add '+method,'method-add');b.dataset.method=method;}button('Back','back','secondary');
}
function render(){s=repo.read();route={family:'09',page:'members',group:s.group?.id||'',...parse()};alert='';publishPrototypeRoute('chopdot-expansion-route',location.hash);
 try{
  if(actor==='visitor'||actor==='self'&&s.gateD?.session?.status!=='active')throw Error('Sign in through Entry before opening private records.');
  if(!['15','20','21','22','14','16','19','23','24','25','26'].includes(route.family)&&!visibleGroups(s,actor).length)throw Error('Join a group before opening private people or payment records.');
  if(route.group&&!['15','20','21','22','16','19','23','24','25','26'].includes(route.family)&&!access(s,actor,route.group))throw Error('This group is no longer available to your Participant. Return to an authorized group.');
  if(route.family==='09'){view=peopleProjection(s,actor,route);if(route.person&&!view.M.PEOPLE[route.person])throw Error('This person is not in your authorized shared groups.');shell('09',renderPeople(view.s,view.M));}
  else if(route.family==='13'){view=requestProjection(s,actor,route);if(!view.M.P.PEOPLE[view.s.context.person])throw Error('Choose a person from your shared groups.');route.page=view.s.route;shell('13',renderRequest(view.s,view.M));}
  else if(route.family==='14'){view=receiveProjection(s,actor,route,QR_DATA);route.page=view.s.route;shell('14',renderReceive(view.s,view.M));if(!view.M.own()&&!route.payment){device.querySelectorAll('[data-action=exit]').forEach(n=>n.textContent='Back to You');device.querySelectorAll('.mp-row .sub').forEach(n=>{if(n.textContent==='For this payment only')n.textContent='Only this sharing context';});}}
  else if(route.family==='20')methodView();
  else if(route.family==='22')qrUI.view();else if(route.family==='21')walletUI.view();else if(['23','24','25'].includes(route.family))portabilityUI.view();else if(route.family==='26')lifecycleUI.view();else if(route.family==='19')insightsUI.view();else if(['16','17'].includes(route.family))savingsUI.view();else if(route.family==='15')historyView();else throw Error('This family is still being integrated.');
  const section=document.createElement('details');section.className='integration-nav';section.innerHTML='<summary>Prototype journeys</summary><nav><button data-action="group-home">Group Home</button><button data-action="history">Settlement history</button><button data-action="methods">Payment methods</button><button data-action="wallet-home">Wallet</button><button data-action="qr-home">Scan QR</button><button data-action="receive-home">Receive money</button><button data-action="savings-list">Savings</button><button data-action="insights-home">Insights</button><button data-action="lifecycle-list">All groups</button><button data-action="data-export-home">Export my data</button><button data-action="data-import-home">Import data</button><button data-action="data-storage-home">Storage & recovery</button><button data-action="lifecycle-settings-entry">Group settings</button></nav>';device.querySelector('main,.content')?.append(section);if(actor!=='self'&&route.family==='09'){const link=document.createElement('a');link.className='btn secondary';link.textContent='Your membership';link.href='../create-join/index.html'+(fixture?'?fixtures=1':'')+'#page=member';device.querySelector('main,.content')?.append(link);}
  if(fixture)fixtures();
 }catch(e){device.innerHTML=`<main><div class="integration-alert" role="alert">${esc(e.message)}</div><button data-action="group-home">Return to Group Home</button></main>`;}
}
function fixtures(){const panel=document.querySelector('#fixtures');panel.innerHTML='<details><summary>Fixtures</summary><div><span>Local prototype preconditions · no service or funds</span></div></details>';const bar=panel.querySelector('div');for(const [key,label]of [['offline','Offline'],['unknown','Unknown result'],['knownFailure','Known failure'],['externalFinality','External finality'],['groupRule','Group approval rule']]){const b=document.createElement('button');b.textContent=label+(s.expansion.environment[key]?' on':' off');b.onclick=()=>{repo.commit({type:'fixture',patch:{[key]:!s.expansion.environment[key]}},'prototype-fixture');render();};bar.append(b);}const o=s.expansion.operations[route.operation];if(o&&['pending','unknown'].includes(o.status))for(const [label,result]of [['Verified accepted','succeeded'],['Verified no effect','no-effect'],['Still pending','pending']]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>guard(()=>{commit({type:'reconcile',id:o.id,result,evidence:{confirmation:true,externalFinality:s.expansion.environment.externalFinality===true,groupRule:s.expansion.environment.groupRule===true}},'prototype-fixture');after(o.id);});bar.append(b);}}
function after(id){const state=repo.read(),o=state.expansion.operations[id];if(o.kind.startsWith('data-'))push({family:['data-backup','data-restore'].includes(o.kind)?'25':o.kind==='data-import'?'23':'24',page:'operation',operation:id});else if(o.kind.startsWith('lifecycle-'))push({family:'26',group:o.payload.groupId,page:'settings',operation:id});else if(o.kind.startsWith('savings-'))push({family:o.kind==='savings-create'?'16':'17',group:o.payload.groupId||o.payload.id,page:'home',operation:id});else if(o.kind==='remove')push({page:o.status==='succeeded'?'removed':o.status==='no-effect'?'remove-failed':'remove-unknown',operation:id});else if(o.kind.startsWith('method-'))push({page:'operation',operation:id,id:o.payload.id});else if(o.kind.startsWith('share'))push({page:'ready',operation:id,id:state.expansion.shares.find(r=>r.operationId===id)?.id||route.id});else push({page:o.status==='prepared'?'review':o.status==='succeeded'?(o.kind==='withdraw-request'?'withdrawn':'detail'):'unknown',operation:id,id:o.kind==='request'&&o.status==='succeeded'?id:route.id});}
function submit(id,retry=false){commit({type:retry?'retry':'submit',id});const state=repo.read(),o=state.expansion.operations[id];after(id);if(o.status==='pending'&&!o.kind.startsWith('savings-')||o.status==='pending'&&o.kind==='savings-create'){// The normal local service response is a labeled simulation, not hosted acceptance.
  setTimeout(()=>guard(()=>{commit({type:'result',id,result:'succeeded'},'prototype-fixture');after(id);}),180);
 }}
function prepare(kind,payload){const id=crypto.randomUUID();commit({type:'prepare',id,kind,payload});return id;}
function guard(fn){const show=e=>{const node=document.createElement('div');node.className='integration-alert';node.role='alert';node.textContent=e.message;device.querySelector('main,.content')?.prepend(node);};try{const value=fn();if(value?.then)value.catch(show);}catch(e){show(e);}}
function action(a,el){
 if(a==='qr-home')return go('22','entry',{group:route.group});if(qrUI.action(a,el))return;
 if(a==='wallet-home')return go('21','handoff',{group:route.group});if(walletUI.action(a,el))return;
 if(a.startsWith('data-'))return portabilityUI.action(a,el);
 if(a==='lifecycle-settings-entry')return go('26','settings',{group:route.group||s.group?.id});if(savingsUI.action(a,el)||insightsUI.action(a,el)||lifecycleUI.action(a,el))return;
 if(a==='global-home'){if(parent!==window)parent.postMessage({type:'chopdot-gate-b-home'},location.origin);else location.href='../index.html?home=1';return;}
 if(a==='people-home')return go('09','directory',{group:s.group?.id});if(a==='activity-home')return owner('gate-d','#page=activity');if(a==='account-home')return owner('gate-d','#page=account');if(a==='expense-home')return owner('gate-b','#page=editor');
 if(a==='methods'||a==='own-methods'||a==='manage'&&route.family==='14')return go('20','overview',{group:route.group,request:route.request});
 if(a==='receive-home')return go('14','methods',{group:route.group,request:route.family==='13'?route.id:route.request});
 if(route.family==='20'){
  if(a==='method-add')return go('20','add',{method:el.dataset.method,group:route.group,request:route.request});if(a==='method-detail')return push({page:'detail',id:el.dataset.id||route.id,operation:''});if(a==='method-edit')return push({page:'edit',operation:''});
  if(a==='method-review'){const old=s.expansion.methods.find(m=>m.id===route.id&&m.owner===actor&&!m.removed),method=old?.method||route.method||'Bank transfer',inputs=Object.fromEntries([...device.querySelectorAll('input')].map(i=>[i.name,i.type==='checkbox'?i.checked:i.value]));const currency=inputs.Currency?.trim().toUpperCase(),p={id:old?.id||crypto.randomUUID(),version:old?.version||0,method,currency,exponent:currency==='DOT'?6:2,fields:METHOD_FIELDS[method].filter(k=>typeof inputs[k]==='string'&&inputs[k].trim()).map(k=>[k,inputs[k].trim()]),visible:inputs.visible,preferred:inputs.preferred};commit({type:'draft',family:'method',values:{...p,id:old?.id||'new'}});const id=prepare('method-save',p);return push({page:'review',operation:id});}
  if(a==='method-submit')return submit(route.operation);if(a==='method-retry')return submit(route.operation,true);if(a==='method-recover'){commit({type:'reconcile',id:route.operation});return after(route.operation);}if(a==='method-edit-review'){const o=s.expansion.operations[route.operation];commit({type:'cancel',id:o.id});return push({page:o.payload.version?'edit':'add',operation:'',method:o.payload.method});}
  if(a==='method-remove-review')return push({page:'remove-confirm',operation:''});if(a==='method-remove'){const m=s.expansion.methods.find(m=>m.id===route.id&&m.owner===actor);if(!m)throw Error('Method unavailable.');return submit(prepare('method-remove',{id:m.id,version:m.version}));}if(a==='receive')return go('14','details',{method:route.id,group:route.group,request:route.request});
 }
 if(route.family==='14'){
  if(a.startsWith('method:'))return push({page:'details',method:a.slice(7),id:'',operation:''});if(a==='start-share')return push({page:route.request?'review':'audience',audience:view.request?.payload.payer||route.audience});if(a.startsWith('audience:'))return push({page:'review',audience:a.slice(9)});
  if(a==='prepare'){const m=view.method,r=view.request;if(!m)throw Error('Review a current receiving method.');const p={methodId:m.id,methodVersion:m.version,currency:m.currency,exponent:m.exponent,audience:route.audience,...(r?{requestId:r.id,amount:r.payload.amount,sourceVersion:r.payload.sourceVersion}:{})};const prior=s.expansion.shares.find(q=>q.owner===actor&&q.audience===p.audience&&q.methodId===m.id&&q.requestId===p.requestId&&shareStatus(s,q)==='active');if(prior)return push({page:'ready',id:prior.id,operation:''});return submit(prepare('share',p));}
  if(a==='stop')return submit(prepare('share-stop',{shareId:route.id}));if(a==='recover'){commit({type:'reconcile',id:route.operation});return after(route.operation);}if(a==='retry')return submit(route.operation,true);
  if(['details','methods','ready','code','recipient','stop-confirm','copy-review','share-preview'].includes(a))return push({page:a});if(a==='refresh')return push({page:'methods',method:'',id:'',operation:''});if((a==='safe-exit'||a==='exit')&&!view.M.own())return route.payment?owner('gate-c','#'+new URLSearchParams({page:'payment',id:route.payment})):owner('gate-d','#page=account');if(a==='safe-exit'||a==='exit')return route.request?go('13','detail',{id:route.request,group:route.group}):go('20','overview',{group:route.group});
  if(a==='copy-raw'||a==='copy-link'){const fresh=receiveProjection(repo.read(),actor,route,QR_DATA);if(!fresh.method||fresh.M.record()&&shareStatus(repo.read(),fresh.M.record(),Date.now(),route.payment)!=='active')throw Error('Recheck this exact current receiving reference before copying.');const text=a==='copy-raw'?fresh.M.raw():fresh.M.link(),expected=route.id||route.method;navigator.clipboard.writeText(text).then(()=>{if((route.id||route.method)===expected)push({copy:'copied',toast:'Copied demo receiving details.'},true);}).catch(()=>{if((route.id||route.method)===expected)push({copy:'failed',toast:'Copy unavailable. Select the reviewed text instead.'},true);});return;}
  if(['share-done','share-cancel','share-fail'].includes(a))return push({page:'share-return',shareResult:a==='share-done'?'returned':a==='share-cancel'?'cancelled':'failed'});
 }
 if(a==='payment'&&route.family==='09'){const currency=el.dataset.currency,rows=relationship(s,actor,route.person,route.scope==='all'?null:route.scope).filter(r=>r.currency===currency),exponent=rows[0]?.exponent||2,n=-rows.reduce((n,r)=>n+BigInt(r.minor),0n);if(n>0n)return go('13','compose',{person:route.person,group:route.group,scope:route.scope,currency,exponent:String(exponent)});return owner('gate-c','#'+new URLSearchParams({page:'person',other:route.person,currency,exponent,group:route.scope==='all'?'':route.scope}));}
 if(a==='back')return back();if(a==='group-home')return owner('gate-b','#page=group');if(a==='history-balance'){const p=records().find(p=>p.id===route.id);if(!p||p.groupIds.some(g=>!access(s,actor,g)))throw Error('Current group access is required.');return owner('gate-c','#'+new URLSearchParams({page:'person',other:p.payer===actor?p.recipient:p.payer,currency:p.currency,exponent:p.exponent,group:p.groupIds.length===1?p.groupIds[0]:''}));}if(a==='history-filter')return push({filter:el.dataset.filter});if(a==='history')return go('15','all',{group:route.group});if(a==='payment-record')return go('15','record',{id:el.dataset.id,group:route.group});if(a==='payment'){const p=records().find(p=>p.id===route.id)||(s.gateC?.payments||[]).find(p=>p.sources.some(r=>view?.M.current()?.payload.sourceItems.includes(r.id))&&[p.payer,p.recipient].includes(actor));if(!p)throw Error('No owning payment exists. A request cannot manufacture a payment.');return owner('gate-c','#'+new URLSearchParams({page:'payment',id:p.id}));}
 if(route.family==='09'){
  if(a==='members')return push({page:'members',scope:route.group,person:'',query:''});if(['directory','safe-directory'].includes(a))return push({page:'directory',scope:'all',person:''});if(a==='person')return push({page:'person',person:el.dataset.person});if(['person-return','roles','preferences','groups','manage'].includes(a))return push({page:a==='person-return'?'person':a});if(a==='open-group')return push({page:'person',scope:el.dataset.group,group:el.dataset.group});
  if(a==='invite'||a==='invite-detail'){if((group(s,route.group)?.ownerId||'self')!==actor)throw Error('Only the current group owner may manage invitations.');ledger.selectGroup(route.group);return owner('create-join','#page=invite');}
  if(a==='payment'){return;}
  if(a==='remove'){const b=removalBlock(s,actor,route.person,route.group);return push({page:b==='balance'?'remove-blocked':b==='offline'?'offline':b?'access-changed':'remove-confirm'});}
  if(a==='confirm-remove'){const id=prepare('remove',{person:route.person,groupId:route.group});return submit(id);}
  if(a==='recover'){commit({type:'reconcile',id:route.operation});return after(route.operation);}if(a==='retry')return submit(route.operation,true);
  if(a==='review-issue'){const r=relationship(s,actor,route.person,route.scope==='all'?null:route.scope).find(r=>r.disputed);if(r)return owner('gate-b','#'+new URLSearchParams({page:'review',id:r.expenseId}));}
 }
 if(route.family==='13'){
  if(a==='review'){const context=view.s.context,p=requestSnapshot(s,actor,context.person,context.currency,context.exponent,context.scope==='all'?null:context.scope,view.s.note);const existing=s.expansion.requests.find(r=>['active','payment-progress'].includes(requestStatus(s,r))&&r.payload.payer===p.payer&&r.payload.recipient===actor&&r.payload.sourceItems.some(id=>p.sourceItems.includes(id)));if(existing)return push({page:'duplicate',id:existing.id});const id=prepare('request',p);return push({page:'review',operation:id});}
  if(a==='send')return submit(route.operation);if(['edit','sources','withdraw-review'].includes(a)){if(a==='edit'&&s.expansion.operations[route.operation]?.status==='prepared'){commit({type:'cancel',id:route.operation});return push({page:'compose',operation:''});}return push({page:a==='edit'?'compose':a==='withdraw-review'?'withdraw-confirm':a});}if(a==='withdraw'){const id=prepare('withdraw-request',{requestId:route.id});return submit(id);}if(a==='retry')return submit(route.operation,true);if(a==='recover'){commit({type:'reconcile',id:route.operation});return after(route.operation);}if(a==='open-existing')return push({page:'detail'});if(['return','safe-return','resume'].includes(a))return go('09','person',{person:view.s.context.person,group:route.group,scope:route.scope});
  if(a==='retry-delivery'){commit({type:'delivery',id:route.id,result:'queued'},'prototype-fixture');return render();}
 }
 throw Error('This adjacent owner action is being integrated. No record changed.');
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)guard(()=>action(el.dataset.action,el));});
document.addEventListener('input',e=>{if(savingsUI.input(e.target)||lifecycleUI.input(e.target))return;if(e.target.id==='people-search'){const q=e.target.value,position=e.target.selectionStart;push({query:q},true);const input=document.querySelector('#people-search');input.focus();input.setSelectionRange(position,position);}else if(route.family==='20'&&['add','edit'].includes(route.page)&&e.target.name){guard(()=>{const old=s.expansion.methods.find(m=>m.id===route.id&&m.owner===actor),inputs=Object.fromEntries([...device.querySelectorAll('input')].map(i=>[i.name,i.type==='checkbox'?i.checked:i.value]));commit({type:'draft',family:'method',values:{id:old?.id||'new',method:old?.method||route.method,currency:inputs.Currency,fields:METHOD_FIELDS[old?.method||route.method||'Bank transfer'].filter(k=>inputs[k]).map(k=>[k,inputs[k]]),visible:inputs.visible,preferred:inputs.preferred}});});}else if(e.target.id==='request-note'){guard(()=>{commit({type:'draft',family:'request',values:{note:e.target.value}});view.s.note=e.target.value;const count=document.querySelector('#note-count');if(count)count.textContent=e.target.value.length;});}});
window.addEventListener('popstate',()=>{const old=s.expansion.operations[route.operation],next=parse();if(old?.actor===actor&&old.status==='prepared'&&next.operation!==old.id)guard(()=>commit({type:'cancel',id:old.id}));render();});render();

document.addEventListener('keydown',e=>{const el=e.target.closest('[role=button][data-action]');if(el&&['Enter',' '].includes(e.key)){e.preventDefault();el.click();}});
