import {membershipActive} from '../create-join/model.js';
// Pure current-access projection. No second ledger, converted aggregate, or invented coverage.
export function insights(s,actor,{days=90,groupId=null,now=Date.now()}={}){
 if(![30,90,365].includes(Number(days)))throw Error('Choose an approved period.');
 const groups=(s.groups||[s.group]).filter(g=>g&&!g.deleted&&g.kind!=='savings'&&membershipActive(s,actor,g.id)&&(!groupId||g.id===groupId)),allowed=new Set(groups.map(g=>g.id)),latest=new Map();
 for(const e of s.expenses||[]){const prior=latest.get(e.id);if(!prior||(e.revision||1)>(prior.revision||1))latest.set(e.id,e);}
 const windowStart=now-Number(days)*86400000,totals={},byGroup={},included=[],undated=[];
 for(const e of latest.values()){if(e.deleted||!allowed.has(e.groupId))continue;const date=Date.parse(e.date);if(!Number.isFinite(date)){undated.push(e.id);continue;}if(date<windowStart||date>now)continue;const m=e.money||e.allocation?.total;if(!m)continue;const key=JSON.stringify([m.currency,m.exponent]);totals[key]=(BigInt(totals[key]||0)+BigInt(m.minorUnits)).toString();byGroup[e.groupId]||={};byGroup[e.groupId][key]=(BigInt(byGroup[e.groupId][key]||0)+BigInt(m.minorUnits)).toString();included.push(e.id);}
 return {days:Number(days),groups,totals,byGroup,included,undated,comparison:null,coverage:'unverified',offline:!!s.expansion?.environment.offline||!!s.gateB?.environment.offline};
}
export function createInsightsUI(context){
 function view(){const {s,actor,route,staticScreen,esc,money}=context(),data=insights(s,actor,{days:Number(route.days||90),groupId:route.scope&&route.scope!=='all'?route.scope:null}),screen=staticScreen('19','overview'),main=screen.querySelector('main');
 screen.querySelector('.j19-title span').textContent='Last '+data.days+' days';const range=main.querySelector('.j19-range');range.innerHTML=[30,90,365].map(d=>`<button class="j19-chip ${data.days===d?'active':''}" data-action="insights-period" data-days="${d}">${d===365?'12 months':d+' days'}</button>`).join('');const scope=main.querySelector('.j19-scope');scope.dataset.action='insights-scope';scope.querySelector('b').textContent=route.scope&&route.scope!=='all'?data.groups[0]?.name||'Unavailable group':'All groups';scope.querySelector('span').textContent=data.groups.length+' authorized groups';const hero=main.querySelector('.j19-hero');hero.innerHTML=`<div class="j19-eyebrow">Shared spending · Last ${data.days} days</div>${Object.entries(data.totals).map(([key,n])=>{const[c,e]=JSON.parse(key);return `<div class="j19-value">${money(n,c,e)}</div>`;}).join('')||'<div class="j19-value">No accepted spending yet</div>'}<div class="j19-delta">${data.offline?'Offline · cached records. ':''}Need a little more history. Comparable period coverage is unverified; no trend is claimed.</div>`;
 main.querySelectorAll('.j19-insight').forEach(n=>n.remove());for(const[key,total]of Object.entries(data.totals)){const[c,e]=JSON.parse(key),rank=Object.entries(data.byGroup).filter(([,v])=>v[key]).sort((a,b)=>BigInt(a[1][key])>BigInt(b[1][key])?-1:1),top=rank[0],g=data.groups.find(g=>g.id===top?.[0]);if(!g)continue;const card=document.createElement('button');card.className='card j19-insight';card.dataset.action='insights-group';card.dataset.group=g.id;card.innerHTML=`<div><h3>${esc(g.name)} has the largest accepted ${esc(c)} shared spending in this view</h3><p>From current authorized records. ${data.undated.length?'Undated records are withheld.':''} Assets and precisions stay separate.</p></div><div class="j19-metric"><b>${money(top[1][key],c,e)}</b><span>${BigInt(total)>0n?String(BigInt(top[1][key])*100n/BigInt(total))+'%':'0%'}</span></div><div class="j19-insight-foot"><span>Open group</span></div>`;main.querySelector('.j19-note').before(card);}screen.querySelectorAll('.tab').forEach(n=>n.dataset.action=n.textContent.trim()==='People'?'people-home':n.textContent.trim()==='Activity'?'activity-home':n.textContent.trim()==='You'?'account-home':'group-home');screen.querySelector('.add-tab').dataset.action='expense-home';
 if(route.page==='scope'){const chooser=document.createElement('div');chooser.className='card list-card';chooser.innerHTML='<button class="list-row" data-action="insights-select" data-group="all">All groups</button>'+insights(s,actor,{days:data.days}).groups.map(g=>`<button class="list-row" data-action="insights-select" data-group="${esc(g.id)}">${esc(g.name)}</button>`).join('');hero.after(chooser);}
 }
 function action(a,el){const{push,owner}=context();if(a==='insights-home'){push({family:'19',page:'overview',group:'',scope:'all',days:'90',operation:'',id:''});return true;}if(a==='insights-period'){push({days:el.dataset.days});return true;}if(a==='insights-scope'){push({page:'scope'});return true;}if(a==='insights-select'){push({page:'overview',scope:el.dataset.group});return true;}if(a==='insights-group'){const{ledger}=context();ledger.selectGroup(el.dataset.group);owner('gate-b','#page=group');return true;}return false;}
 return {view,action};
}
