import {definitionView} from './definition-view.js';import {groupMembers,membershipActive} from '../create-join/model.js';import {openGroupItems} from './lifecycle.js';
export function createLifecycleUI(context){
 const a=(label,action,kind='ghost',extra='')=>({label,action,kind,extra});
 function view(){const{s,actor,route,docs,defs,device,esc,name}=context(),o=s.expansion.operations[route.operation]?.actor===actor?s.expansion.operations[route.operation]:null,g=[s.group,...s.groups].find(g=>g?.id===(o?.payload.groupId||route.group)),owner=g&&(g.ownerId||'self')===actor,op=o?.kind.slice(10),draft=s.expansion.drafts[actor+':lifecycle:'+g?.id]||{};let page=route.page||'settings',fields=[],actions=[],special='',title;
 if(page==='list'){const gs=s.groups.filter(g=>!g.deleted&&groupMembers(s,g).some(p=>p.id===actor));definitionView(docs['26'],device,document.querySelector('#golden-style'),{...defs['26']['settings-overview-owner'],title:'Your groups',facts:[],actions:gs.map(g=>a(g.name+(g.archived?' · Archived':''),'lifecycle-open','ghost',`data-id="${esc(g.id)}"`))},esc);return;}
 if(!g)throw Error('This group is unavailable.');if(!membershipActive(s,actor,g.id)||g.deleted){if(o?.status==='succeeded'&&['lifecycle-leave','lifecycle-delete'].includes(o.kind)){const reviewed=JSON.parse(o.source).group;definitionView(docs['26'],device,document.querySelector('#golden-style'),{title:o.kind==='lifecycle-leave'?'You left '+reviewed.name:reviewed.name+' was deleted here',lead:'Your accepted receipt is retained. Current private group records are unavailable.',facts:[['Operation',o.id],['Result','Accepted'],['Historical attribution','Preserved']],actions:[a('Return to Home','lifecycle-home','accent')]},esc);return;}throw Error('This group is no longer available to your Participant.');}if(o){page=o.status==='prepared'?op==='currency'?'config-review':op==='delete'?'delete-final-review':op==='rename'?'rename-review':op+'-confirm':o.status==='succeeded'?op==='rename'?'renamed':op==='currency'?'config-saved':op==='archive'?'archived':op==='unarchive'?'unarchived':op==='transfer'?'transferred':op==='leave'?'left-group':'deleted':o.status==='no-effect'?op+'-failed':op+'-unknown';}
 const source=defs['26'][page]||defs['26'][owner?'settings-overview-owner':'settings-overview-member'],v={...source,state:page,eyebrow:g.name+' · '+(owner?'owner':'member'),header:g.name+' · '+groupMembers(s,g).length+' people · '+g.currency,facts:fields};
 if(o){fields.push(['Operation',o.id],['Status',o.status],['Group',g.name],['Scope','This group only · ledger and attribution unchanged']);if(op==='rename')fields.push(['Reviewed new name',o.payload.name]);if(op==='currency')fields.push(['Future expense default',o.payload.currency]);if(op==='transfer')fields.push(['New owner',name(s,o.payload.successor)]);if(o.status==='prepared')actions=[a(source.actions?.[0]?.label||'Confirm change','lifecycle-submit','accent'),a('Cancel','lifecycle-cancel')];else if(o.status==='no-effect')actions=[a('Retry same operation','lifecycle-retry','accent'),a('Back to settings','lifecycle-settings')];else if(['pending','unknown'].includes(o.status))actions=[a('Check original result','lifecycle-check','accent'),a('Back to settings','lifecycle-settings')];else actions=[a(['leave','delete'].includes(op)?'Return to Home':'Back to settings',['leave','delete'].includes(op)?'lifecycle-home':'lifecycle-settings','accent')];if(o.status==='prepared'){title=op==='rename'?'Rename '+g.name+' to '+o.payload.name+'?':op==='currency'?'Use '+o.payload.currency+' for future expenses?':op==='transfer'?'Make '+name(s,o.payload.successor)+' the owner?':op==='unarchive'?'Restore '+g.name+'?':source.title.replaceAll('Zurich Weekend',g.name);actions[0].label=op==='unarchive'?'Restore group':op==='rename'?'Rename group':op==='currency'?'Save future default':op==='transfer'?'Transfer ownership':op==='archive'?'Archive group':op==='leave'?'Leave group':'Delete group';v.lead=op==='rename'?'Only the group name changes. Balances and history stay unchanged.':op==='currency'?'Existing MoneyV1 records retain their recorded currencies and exact allocations.':op==='transfer'?'Only the owner role changes. Account, payment and wallet authority do not transfer.':op==='unarchive'?'Return this same group to active organization. Historical financial facts remain unchanged.':v.lead;}if(o.status==='succeeded')title=op==='rename'?'Group name saved':op==='currency'?'Future default saved':op==='archive'?'Group archived':op==='unarchive'?'Group restored':op==='transfer'?'Ownership transferred':op==='leave'?'You left '+g.name:g.name+' was deleted here';}
 else if(page==='settings'){fields.push(['Name',g.name],['Future expense default',g.currency],['Status',g.archived?'Archived':'Active'],['Members',groupMembers(s,g).length+' active'],['Your role',owner?'Owner':'Member'],['Open items',openGroupItems(s,g.id)?'Present':'None']);title='Group settings';actions=owner?[a('Rename group','lifecycle-rename','accent'),...(g.kind==='savings'?[]:[a('Change future default','lifecycle-currency')]),a(g.archived?'Restore group':'Archive group',g.archived?'lifecycle-unarchive':'lifecycle-archive'),a('Transfer ownership','lifecycle-transfer'),a('Review leaving','lifecycle-leave'),...(g.archived?[a('Review deletion','lifecycle-delete','danger')]:[])]:[a('Review leaving group','lifecycle-leave','accent')];}
 else if(page==='rename-edit'){title='Rename the group';fields.push(['Current name',g.name],['History / balances','Unchanged']);special=`<section class="card pad"><div class="field"><label for="lifecycle-name">Group name</label><input id="lifecycle-name" name="lifecycle-name" value="${esc(draft.name??g.name)}" maxlength="80"></div></section>`;actions=[a('Review new name','lifecycle-review-rename','accent'),a('Cancel','lifecycle-settings')];}
 else if(page==='config-edit'){title='Choose a default currency';fields.push(['Current default',g.currency],['Existing expenses','Stay in recorded currencies']);special=`<section class="card pad"><div class="field"><label for="lifecycle-currency">Currency for future expenses</label><select id="lifecycle-currency" name="lifecycle-currency">${['CHF','EUR','USD'].map(c=>`<option ${(draft.currency??g.currency)===c?'selected':''}>${c}</option>`).join('')}</select></div></section>`;actions=[a('Review default change','lifecycle-review-currency','accent'),a('Cancel','lifecycle-settings')];}
 else if(page==='transfer-review'){title='Transfer ownership';fields.push(['Current owner',name(s,g.ownerId||'self')],['Your role after success','Member'],['Balances / history','Unchanged']);actions=groupMembers(s,g).filter(p=>p.id!==actor).map(p=>a('Review transfer to '+name(s,p.id),'lifecycle-review-transfer','accent',`data-successor="${esc(p.id)}"`));actions.push(a('Manage eligible members','lifecycle-people'),a('Cancel','lifecycle-settings'));}
 else if(page==='leave-owner-blocked'){title='Transfer ownership before leaving';fields.push(['Your role','Owner']);actions=[a('Transfer ownership','lifecycle-transfer','accent'),a('Back to settings','lifecycle-settings')];}
 else if(page==='leave-blocked-open-items'){title='Resolve your open items first';fields.push(['Position','Open items remain · zero net is insufficient']);actions=[a('View settlement','lifecycle-settle','accent'),a('Back to settings','lifecycle-settings')];}
 else if(page==='delete-review'){title='Deletion has strict prerequisites';fields.push(['Group status',g.archived?'Archived':'Active'],['Active members',groupMembers(s,g).length],['Open items',openGroupItems(s,g.id)?'Present':'None']);actions=[...(g.archived&&groupMembers(s,g).length===1&&!openGroupItems(s,g.id)?[a('All prerequisites met','lifecycle-type-delete','danger')]:[]),a('Manage members first','lifecycle-people'),a('Resolve open items','lifecycle-settle'),a('Cancel','lifecycle-settings')];}
 else if(page==='delete-type-confirm'){title='Type “'+g.name+'”';special=`<section class="card pad"><div class="field"><label for="delete-name">Group name</label><input id="delete-name" autocomplete="off" value="${esc(draft.confirmation||'')}"><div class="hint">Exact match required. Nothing is deleted by typing.</div></div></section>`;actions=[a('Continue','lifecycle-review-delete','danger'),a('Cancel deletion','lifecycle-settings')];}
 else if(['archive-review','unarchive-review','leave-review'].includes(page)){title=source.title.replaceAll('Zurich Weekend',g.name);fields.push(['Group',g.name],['Current status',g.archived?'Archived':'Active'],['Historical attribution / ledger','Preserved']);actions=[a('Continue to confirmation','lifecycle-review-'+page.split('-')[0],'accent'),a('Cancel','lifecycle-settings')];}
 if(!o){const unresolved=Object.values(s.expansion.operations).filter(q=>q.actor===actor&&q.kind.startsWith('lifecycle-')&&q.payload.groupId===g.id&&['pending','unknown','no-effect'].includes(q.status));actions.push(...unresolved.map(q=>a('Reopen original '+q.kind.slice(10)+' · '+q.status,'lifecycle-reopen','ghost',`data-id="${esc(q.id)}"`)));}
 definitionView(docs['26'],device,document.querySelector('#golden-style'),{...v,facts:fields,actions,special,title:title||source.title.replaceAll('Zurich Weekend',g.name)},esc);
 }
 function action(a,el){if(!a.startsWith('lifecycle-'))return false;const{s,actor,route,commit,prepare,submit,push,go,owner}=context(),g=[s.group,...s.groups].find(g=>g?.id===route.group),payload={groupId:route.group,version:g?.revision||1};
 if(a==='lifecycle-reopen')push({page:'operation',operation:el.dataset.id});else if(a==='lifecycle-open')go('26','settings',{group:el.dataset.id});else if(a==='lifecycle-list')go('26','list',{group:''});else if(a==='lifecycle-settings')push({page:'settings',operation:''});else if(a==='lifecycle-home'){if(parent!==window)parent.postMessage({type:'chopdot-gate-b-home'},location.origin);else location.href='../index.html?home=1';}
 else if(a==='lifecycle-people')go('09','members',{group:route.group});else if(a==='lifecycle-settle')owner('gate-c','#'+new URLSearchParams({page:'group',group:route.group}));
 else if(a==='lifecycle-rename')push({page:'rename-edit',operation:''});else if(a==='lifecycle-currency')push({page:'config-edit',operation:''});else if(a==='lifecycle-transfer')push({page:'transfer-review',operation:''});else if(a==='lifecycle-archive'||a==='lifecycle-unarchive')push({page:a.slice(10)+'-review',operation:''});else if(a==='lifecycle-leave')push({page:(g.ownerId||'self')===actor?'leave-owner-blocked':openGroupItems(s,g.id,actor)?'leave-blocked-open-items':'leave-review',operation:''});else if(a==='lifecycle-delete')push({page:'delete-review',operation:''});else if(a==='lifecycle-type-delete')push({page:'delete-type-confirm'});
 else if(a.startsWith('lifecycle-review-')){const kind=a.slice(17),extra=kind==='rename'?{name:document.querySelector('#lifecycle-name').value}:kind==='currency'?{currency:document.querySelector('#lifecycle-currency').value}:kind==='transfer'?{successor:el.dataset.successor}:kind==='delete'?{confirmation:document.querySelector('#delete-name').value,finalReview:true}:{};const id=prepare('lifecycle-'+kind,{...payload,...extra});push({page:'review',operation:id});}
 else if(a==='lifecycle-submit')submit(route.operation);else if(a==='lifecycle-retry')submit(route.operation,true);else if(a==='lifecycle-check'){commit({type:'reconcile',id:route.operation});push({},true);}else if(a==='lifecycle-cancel'){commit({type:'cancel',id:route.operation});push({page:'settings',operation:''});}else return false;return true;
 }
 function input(el){if(!el.name?.startsWith('lifecycle-')&&el.id!=='delete-name')return false;const{s,actor,route,commit}=context(),family='lifecycle:'+route.group,old=s.expansion.drafts[actor+':'+family]||{};commit({type:'draft',family,values:{...old,[el.id==='delete-name'?'confirmation':el.name.slice(10)]:el.value}});return true;}
 return {view,action,input};
}
