import {membershipActive,groupMembers,member,fail} from '../create-join/model.js';import {sources,unresolved} from '../gate-c/ledger.js';
const owner=(g,actor)=>(g.ownerId||'self')===actor;
export function openGroupItems(s,id,actor=null){return (actor?[actor]:[...new Set(['self',...(s.expenses||[]).filter(e=>e.groupId===id).flatMap(e=>[e.payerId,...e.participantIds])])]).flatMap(p=>sources(s,p)).some(r=>r.groupId===id&&(BigInt(r.minor)!==0n||r.disputed))||(s.expenses||[]).some(e=>!e.deleted&&e.groupId===id&&(!actor||[e.payerId,...e.participantIds].includes(actor))&&e.issues?.some(i=>i.status==='open'))||(s.gateC?.payments||[]).some(p=>p.groupIds.includes(id)&&(!actor||[p.payer,p.recipient].includes(actor))&&unresolved(s,p))||Object.values(s.expansion?.operations||{}).some(o=>o.kind.startsWith('savings-')&&o.payload.groupId===id&&['pending','unknown'].includes(o.status))||(s.expansion?.savingsEvents||[]).filter(e=>e.groupId===id&&(!actor||e.actor===actor)).reduce((n,e)=>n+BigInt(e.delta),0n)!==0n;}
export function validateLifecycle(s,kind,p,actor){if(!['lifecycle-rename','lifecycle-currency','lifecycle-archive','lifecycle-unarchive','lifecycle-transfer','lifecycle-leave','lifecycle-delete'].includes(kind))fail('COMMAND','Unsupported lifecycle operation.');const g=[s.group,...s.groups].find(g=>g?.id===p.groupId&&!g.deleted);if(!g||!membershipActive(s,actor,g.id))fail('ACCESS','Your group membership changed.');if(p.version!==(g.revision||1))fail('STALE','The group changed. Refresh and review current facts.');if(kind!=='lifecycle-leave'&&!owner(g,actor))fail('ROLE','Only the current owner may make this group-wide change.');
 if(kind==='lifecycle-rename'&&(!p.name?.trim()||p.name.length>80))fail('NAME','Use a group name between 1 and 80 characters.');
 if(kind==='lifecycle-currency'&&(!['CHF','EUR','USD'].includes(p.currency)||g.kind==='savings'))fail('CURRENCY','Change only the supported default for future expenses. Savings keeps its exact asset.');
 if(kind==='lifecycle-archive'&&g.archived||kind==='lifecycle-unarchive'&&!g.archived)fail('STATE','Review the current archive status.');
 if(kind==='lifecycle-transfer'&&(p.successor===actor||!groupMembers(s,g).some(m=>m.id===p.successor)))fail('MEMBER','Choose a different already-active member.');
 if(kind==='lifecycle-leave'){if(owner(g,actor))fail('OWNER','Transfer ownership before leaving.');if(openGroupItems(s,g.id,actor))fail('OPEN','Resolve your individual open items first; zero net does not clear them.');}
 if(kind==='lifecycle-delete'){if(!g.archived||groupMembers(s,g).length!==1||!owner(g,actor)||openGroupItems(s,g.id))fail('DELETE','Deletion requires archived status, sole active owner and no open items.');if(p.confirmation!==g.name||p.finalReview!==true)fail('CONFIRM','Type the exact group name and complete a separate final review.');}
 return {group:g,members:groupMembers(s,g).map(m=>m.id)};
}
export function effectLifecycle(s,o){const p=o.payload;for(const g of new Set([s.group,...s.groups].filter(g=>g?.id===p.groupId))){if(o.kind==='lifecycle-rename')g.name=p.name.trim();else if(o.kind==='lifecycle-currency')g.currency=p.currency;else if(o.kind==='lifecycle-archive')g.archived=true;else if(o.kind==='lifecycle-unarchive')g.archived=false;else if(o.kind==='lifecycle-transfer')g.ownerId=p.successor;else if(o.kind==='lifecycle-leave'){g.removedMemberIds=[...new Set([...(g.removedMemberIds||[]),o.actor])];}else if(o.kind==='lifecycle-delete')g.deleted=true;g.revision=(g.revision||1)+1;}if(o.kind==='lifecycle-leave'){const m=member(s,o.actor);if(m)m.capabilityVersion++;}}
