import {walletTransition} from './wallet.js';
import {validatePortability,effectPortability} from './portability.js';
import {validateLifecycle,effectLifecycle} from './lifecycle.js';
import {validateSavings,effectSavings,savingsResultGuard} from './savings.js';
// Integrated local prototype domain. All projections and effects use the existing canonical store.
import {allGroups,sources,unresolved} from '../gate-c/ledger.js';
import {groupMembers,member,online,fail} from '../create-join/model.js';
import {assertParticipantCommand} from '../create-join/authority.js';
import {moneyFromMinorUnits,moneyToDecimal} from '../money-v1.js';
export const KEY='chopdot.preview-v2.guest';
const clone=x=>structuredClone(x), fingerprint=x=>JSON.stringify(x);
export function upgrade(input){const s=clone(input||{});s.groups=allGroups(s);s.people||=[];s.expenses||=[];s.expansion||={version:1,sequence:0,operations:{},history:[],drafts:{},requests:[],shares:[],methods:[],environment:{}};for(const key of ['history','requests','shares','methods','savingsEvents','artifacts','imports','importedHistory'])s.expansion[key]||=[];for(const key of ['operations','drafts','environment'])s.expansion[key]||={};return s;}
export const group=(s,id)=>allGroups(s).find(g=>g.id===id&&!g.deleted);
export const name=(s,id)=>id==='self'?(s.gateD?.account?.displayName||'You'):s.people.find(p=>p.id===id)?.name||'Former participant';
export const activeMembers=(s,g)=>groupMembers(s,g).filter(p=>!g.removedMemberIds?.includes(p.id));
export function access(s,actor,groupId){const g=group(s,groupId);if(!g)return false;if(g.removedMemberIds?.includes(actor))return false;return activeMembers(s,g).some(p=>p.id===actor);}
export const visibleGroups=(s,actor)=>allGroups(s).filter(g=>access(s,actor,g.id));
export function account(s,c){if(c.actor==='visitor')fail('ACCESS','Join before opening private records.');if(c.actor==='self'){if(s.gateD?.session?.status!=='active')fail('ACCOUNT','Continue through the approved Entry fixture.');}else{assertParticipantCommand(s,c);if(member(s,c.actor)?.identity!=='linked')fail('ACCOUNT','An account bound to this Participant is required.');}}
export function relationship(s,actor,person,groupId=null){const gs=visibleGroups(s,actor).filter(g=>activeMembers(s,g).some(p=>p.id===person)&&(!groupId||g.id===groupId));const allowed=new Set(gs.map(g=>g.id));return sources(s,actor,person).filter(r=>allowed.has(r.groupId));}
export function removalBlock(s,actor,person,groupId){const g=group(s,groupId);if(!online(s)||s.expansion?.environment.offline)return 'offline';if(!access(s,actor,groupId)||(g.ownerId||'self')!==actor)return 'permission';if(person===actor||person===(g.ownerId||'self'))return 'owner';if(!activeMembers(s,g).some(p=>p.id===person))return 'missing';if(sources(s,person).some(r=>r.groupId===groupId&&(BigInt(r.minor)!==0n||r.disputed))||(s.gateC?.payments||[]).some(p=>[p.payer,p.recipient].includes(person)&&p.groupIds.includes(groupId)&&unresolved(s,p)))return 'balance';return null;}
export function requestSnapshot(s,actor,person,currency,exponent=2,groupId=null,note=''){
 const rows=relationship(s,actor,person,groupId).filter(r=>r.currency===currency&&r.exponent===Number(exponent)&&BigInt(r.minor)!==0n);const amount=-rows.reduce((n,r)=>n+BigInt(r.minor),0n);
 if(person===actor||!rows.length||amount<=0n)fail('NOTHING','Nothing to request in this exact scope.');if(rows.some(r=>r.disputed))fail('ISSUE','Resolve the related expense issue first.');if(typeof note!=='string'||note.length>160)fail('NOTE','Keep the note to 160 characters.');
 return {requester:actor,payer:person,recipient:actor,currency,exponent:Number(exponent),amount:amount.toString(),groupId,sourceItems:rows.map(r=>r.id),sourceGroups:[...new Set(rows.map(r=>r.groupId))],sourceVersion:fingerprint(rows.map(r=>[r.id,r.revision,r.minor,r.disputed])),note:note.trim(),audience:[actor,person]};
}
export function requestStatus(s,r){if(r.status!=='active')return r.status;const payments=(s.gateC?.payments||[]).filter(p=>p.payer===r.payload.payer&&p.recipient===r.payload.recipient&&p.currency===r.payload.currency&&p.exponent===r.payload.exponent&&p.sources.some(x=>r.payload.sourceItems.includes(x.id)));if(payments.some(p=>unresolved(s,p)))return 'payment-progress';const rows=sources(s,r.payload.requester,r.payload.payer).filter(x=>r.payload.sourceItems.includes(x.id));if(payments.some(p=>['closed','partial'].includes(p.state))&&rows.every(x=>BigInt(x.minor)===0n))return 'paid';return 'active';}
export const METHOD_FIELDS={'Bank transfer':['Account holder','IBAN','BIC','Bank','Reference note','Label'],TWINT:['Phone','Handle','Label'],PayPal:['Email','Username','Label'],Wallet:['Public address','Network','Label']};
export function validateMethod(p){if(!METHOD_FIELDS[p.method]||!p.currency||!Number.isInteger(p.exponent)||p.exponent<0||p.exponent>18||!Array.isArray(p.fields)||p.fields.length===0)fail('DESTINATION','Review the method, exact currency and receiving fields.');if(p.fields.some(r=>!Array.isArray(r)||r.length!==2||!METHOD_FIELDS[p.method].includes(r[0])||typeof r[1]!=='string'||!r[1].trim()||r[1].length>240)||new Set(p.fields.map(r=>r[0])).size!==p.fields.length)fail('FIELDS','Only the method’s receiving fields are allowed. Never enter credentials or private keys.');const keys=new Set(p.fields.map(r=>r[0]));if(p.method==='Bank transfer'&&(!keys.has('Account holder')||!keys.has('IBAN'))||p.method==='TWINT'&&!keys.has('Phone')&&!keys.has('Handle')||p.method==='PayPal'&&!keys.has('Email')&&!keys.has('Username')||p.method==='Wallet'&&(!keys.has('Public address')||!keys.has('Network')))fail('DESTINATION','Required receiving fields are missing.');if(['TWINT','Bank transfer'].includes(p.method)&&p.currency!=='CHF'&&p.method==='TWINT')fail('CURRENCY','TWINT cannot be suggested for this currency.');return p;}
export function shareStatus(s,r,now=Date.now(),paymentId=null){if(r.status!=='active')return r.status;const method=s.expansion.methods.find(m=>m.id===r.methodId&&!m.removed);if(!method||method.version!==r.methodVersion)return 'changed';if(now>=r.expiresAt)return 'expired';if(!visibleGroups(s,r.owner).some(g=>activeMembers(s,g).some(p=>p.id===r.audience))||member(s,r.audience)?.identity==='guest')return 'unavailable';if(r.requestId){const request=s.expansion.requests.find(q=>q.id===r.requestId);const status=request&&requestStatus(s,request),payment=paymentId&&(s.gateC?.payments||[]).find(p=>p.id===paymentId),same=(a,b)=>JSON.stringify([...a].sort())===JSON.stringify([...b].sort()),samePending=status==='payment-progress'&&payment&&unresolved(s,payment)&&payment.payer===r.audience&&payment.recipient===r.owner&&payment.currency===r.currency&&payment.exponent===r.exponent&&payment.amount===r.amount&&same(payment.groupIds,request.payload.sourceGroups)&&same(payment.sources.map(x=>x.id),request.payload.sourceItems);if(!request||status!=='active'&&!samePending||request.payload.amount!==r.amount||request.payload.sourceVersion!==r.sourceVersion)return 'changed';try{const p=requestSnapshot(s,r.owner,request.payload.payer,request.payload.currency,request.payload.exponent,request.payload.groupId,request.payload.note);if(p.sourceVersion!==r.sourceVersion)return 'changed';}catch{return 'changed';}}return 'active';}
function requestConflict(s,p){return s.expansion.requests.find(r=>['active','payment-progress'].includes(requestStatus(s,r))&&r.payload.payer===p.payer&&r.payload.recipient===p.recipient&&r.payload.currency===p.currency&&r.payload.exponent===p.exponent&&r.payload.sourceItems.some(id=>p.sourceItems.includes(id)));}
function validate(s,kind,p,actor){
 if(kind.startsWith('data-'))return validatePortability(s,kind,p,actor);
 if(kind.startsWith('lifecycle-'))return validateLifecycle(s,kind,p,actor);
 if(kind.startsWith('savings-'))return validateSavings(s,kind,p,actor);
 if(kind==='remove'){const b=removalBlock(s,actor,p.person,p.groupId);if(b)fail(b.toUpperCase(),b==='balance'?'Settle up first. Open items in this group prevent removal.':'Current group owner permission and active membership are required.');return {group:group(s,p.groupId),members:activeMembers(s,group(s,p.groupId)).map(x=>x.id)};}
 if(kind==='request'){const exact=requestSnapshot(s,actor,p.payer,p.currency,p.exponent,p.groupId,p.note);if(fingerprint(exact)!==fingerprint(p))fail('STALE','The request scope changed. Review current sources again.');const existing=requestConflict(s,p);if(existing)fail('DUPLICATE','Open the existing request. No second request was created.',{id:existing.id});return exact;}
 if(kind==='withdraw-request'){const r=s.expansion.requests.find(r=>r.id===p.requestId);if(!r||r.payload.requester!==actor||!r.payload.sourceGroups.every(g=>access(s,actor,g)))fail('ACCESS','This request is unavailable.');if(requestStatus(s,r)!=='active')fail('PAYMENT','Payment progress or a terminal result prevents withdrawing the request.');return r;}
 if(kind==='method-save'){validateMethod(p);const old=s.expansion.methods.find(m=>m.id===p.id);if(old&&(old.owner!==actor||old.removed||old.version!==p.version))fail('STALE','Review the current receiving method version.');if(s.expansion.methods.some(m=>m.id!==p.id&&!m.removed&&m.owner===actor&&m.method===p.method&&m.currency===p.currency&&fingerprint(m.fields)===fingerprint(p.fields)))fail('DUPLICATE','This receiving method already exists.');return old||p;}
 if(kind==='method-remove'){const m=s.expansion.methods.find(m=>m.id===p.id&&!m.removed&&m.owner===actor);if(!m||m.version!==p.version)fail('STALE','This receiving method changed or was removed.');return m;}
 if(kind==='share'){const m=s.expansion.methods.find(m=>m.id===p.methodId&&m.owner===actor&&!m.removed&&m.visible);if(!m||m.version!==p.methodVersion)fail('STALE','Review current available receiving details.');validateMethod(m);if(p.audience===actor||!visibleGroups(s,actor).some(g=>activeMembers(s,g).some(q=>q.id===p.audience))||member(s,p.audience)?.identity==='guest')fail('AUDIENCE','Choose one account-backed Participant from your shared groups.');if(m.currency!==p.currency||m.exponent!==p.exponent)fail('CURRENCY','Keep the exact destination currency and asset precision.');if(p.requestId){const r=s.expansion.requests.find(r=>r.id===p.requestId&&r.payload.requester===actor);if(!r||requestStatus(s,r)!=='active'||r.payload.payer!==p.audience||r.payload.currency!==m.currency||r.payload.exponent!==m.exponent||r.payload.amount!==p.amount||r.payload.sourceVersion!==p.sourceVersion)fail('STALE','The originating request changed.');const current=requestSnapshot(s,actor,r.payload.payer,r.payload.currency,r.payload.exponent,r.payload.groupId,r.payload.note);if(current.sourceVersion!==p.sourceVersion)fail('STALE','The originating request scope changed.');}
  if(s.expansion.shares.some(r=>r.owner===actor&&r.audience===p.audience&&r.methodId===p.methodId&&r.requestId===p.requestId&&shareStatus(s,r)==='active'))fail('DUPLICATE','Use the existing scoped share.');if(s.expansion.shares.length>=32)fail('CAPACITY','The approved inert QR fixture supports 32 references. No real receiving link was created.');return {method:m,audience:p.audience,request:p.requestId?s.expansion.requests.find(r=>r.id===p.requestId):null};}
 if(kind==='share-stop'){const r=s.expansion.shares.find(r=>r.id===p.shareId&&r.owner===actor);if(!r||r.status!=='active')fail('SHARE','This sharing reference is no longer active.');return r;}
 fail('COMMAND','This operation is not implemented.');
}
function effect(s,o,now){const p=o.payload;if(o.kind.startsWith('data-')){effectPortability(s,o,now);return;}if(o.kind.startsWith('lifecycle-')){effectLifecycle(s,o);return;}if(o.kind.startsWith('savings-')){effectSavings(s,o,now);return;}if(o.kind==='remove'){for(const g of new Set([s.group,...s.groups].filter(g=>g?.id===p.groupId))){g.removedMemberIds=[...new Set([...(g.removedMemberIds||[]),p.person])];g.revision=(g.revision||1)+1;}const participant=member(s,p.person);if(participant)participant.capabilityVersion++;}
 else if(o.kind==='request')s.expansion.requests.push({id:o.id,payload:clone(p),status:'active',delivery:'queued',version:1,createdAt:now});
 else if(o.kind==='withdraw-request'){const r=s.expansion.requests.find(r=>r.id===p.requestId);r.status='withdrawn';r.version++;}
 else if(o.kind==='method-save'){const old=s.expansion.methods.find(m=>m.id===p.id);if(p.preferred)for(const m of s.expansion.methods.filter(m=>m.owner===o.actor&&m.currency===p.currency&&m.exponent===p.exponent&&(m.fields.find(f=>f[0]==='Network')?.[1]||'')===(p.fields.find(f=>f[0]==='Network')?.[1]||'')))m.preferred=false;const m={...clone(p),owner:o.actor,version:(old?.version||0)+1,removed:false};if(old)Object.assign(old,m);else s.expansion.methods.push(m);}
 else if(o.kind==='method-remove'){const m=s.expansion.methods.find(m=>m.id===p.id);m.removed=true;m.version++;m.preferred=false;}
 else if(o.kind==='share')s.expansion.shares.push({...clone(p),id:'demo-share-'+(s.expansion.shares.length+1),operationId:o.id,owner:o.actor,status:'active',createdAt:now,expiresAt:Date.parse(now)+24*60*60*1000});
 else if(o.kind==='share-stop')s.expansion.shares.find(r=>r.id===p.shareId).status='stopped';
}
export function transition(input,c,authority='user',now=new Date().toISOString()){
 const s=upgrade(input),x=s.expansion;
 if(c.type==='fixture'){if(authority!=='prototype-fixture')fail('AUTHORITY','Use explicit prototype preconditions.');Object.assign(x.environment,c.patch);return s;}
 account(s,c);if(!online(s)||x.environment.offline)fail('OFFLINE','Reconnect before changing shared records.');
 if(c.type==='wallet'){walletTransition(s,c,authority,now);x.sequence++;return s;}
 if(c.type==='artifact-download'){const a=x.artifacts.find(a=>a.id===c.id&&a.owner===c.actor);if(!a)fail('ARTIFACT','Reopen your exact prepared artifact.');a.delivery='browser-requested';a.requestedAt=now;return s;}
 if(c.type==='delivery'){const r=x.requests.find(r=>r.id===c.id&&r.payload.requester===c.actor);if(authority!=='prototype-fixture'||!r||requestStatus(s,r)!=='active'||!['queued','delivered','failed'].includes(c.result))fail('DELIVERY','Only an explicit current delivery fixture can update this existing request.');r.delivery=c.result;return s;}
 if(c.type==='draft'){x.drafts[c.actor+':'+c.family]=clone(c.values);return s;}
 if(c.type==='prepare'){
  if(!c.id)fail('IDENTITY','Keep a stable operation identity.');const prior=x.operations[c.id];if(prior){if(fingerprint([c.kind,c.payload,c.actor])!==fingerprint([prior.kind,prior.payload,prior.actor]))fail('IDENTITY','This operation reference belongs to another payload.');return s;}
  const overlap=o=>(c.kind.startsWith('data-')&&o.kind.startsWith('data-')&&(o.payload.scope===c.payload.scope||['data-import','data-restore'].includes(c.kind)))||(c.kind.startsWith('lifecycle-')&&o.kind.startsWith('lifecycle-')&&o.payload.groupId===c.payload.groupId)||(c.kind.startsWith('savings-')&&o.kind.startsWith('savings-')&&o.payload.groupId===c.payload.groupId&&o.actor===c.actor)||o.kind===c.kind&&(c.kind==='request'?o.payload.sourceItems.some(id=>c.payload.sourceItems.includes(id)):c.kind==='remove'?o.payload.groupId===c.payload.groupId&&o.payload.person===c.payload.person:c.kind==='share'?o.payload.methodId===c.payload.methodId&&o.payload.audience===c.payload.audience:o.payload.id===c.payload.id&&o.payload.requestId===c.payload.requestId&&o.payload.shareId===c.payload.shareId);
  if(Object.values(x.operations).some(o=>o.actor===c.actor&&['prepared','pending','unknown'].includes(o.status)&&overlap(o)))fail('PENDING','Resolve the existing operation for this exact scope before starting another change.');
  const v=validate(s,c.kind,c.payload,c.actor);x.operations[c.id]={id:c.id,actor:c.actor,kind:c.kind,payload:clone(c.payload),source:fingerprint(v),status:'prepared',createdAt:now};
 }else if(['submit','result','reconcile','retry','cancel'].includes(c.type)){
  const o=x.operations[c.id];if(!o||o.actor!==c.actor)fail('IDENTITY','Reopen the existing operation for the same Participant.');
  if(c.type==='cancel'){if(o.status!=='prepared')fail('PENDING','An operation past first effect must reconcile.');o.status='cancelled';}
  else if(c.type==='submit'||c.type==='retry'){if(o.status!==(c.type==='submit'?'prepared':'no-effect'))fail('PENDING','Retry only after verified non-acceptance.');const v=validate(s,o.kind,o.payload,c.actor);if(fingerprint(v)!==o.source)fail('STALE','Current facts changed. Review the operation again.');o.status=x.environment.knownFailure?'no-effect':x.environment.unknown?'unknown':'pending';}
  else if(c.type==='result'||c.type==='reconcile'){
   if(!['pending','unknown'].includes(o.status))return s;if(c.result===undefined){o.status='unknown';return s;}
   if(authority!=='prototype-fixture')fail('AUTHORITY','Only the explicit external-result fixture can establish the outcome.');
   if(c.result==='no-effect')o.status='no-effect';else if(c.result==='pending')o.status='unknown';else if(c.result==='succeeded'){const v=validate(s,o.kind,o.payload,c.actor);if(fingerprint(v)!==o.source)fail('STALE','Acceptance blocked by changed role, version or dependency.');savingsResultGuard(s,o,c.evidence);effect(s,o,now);o.status='succeeded';o.acceptedAt=now;}else fail('RESULT','Use a defined current-result fixture.');
  }
 }else fail('COMMAND','Unknown integrated-family command.');
 x.sequence++;x.history.push({id:c.operationId||crypto.randomUUID(),operation:c.id,type:c.type,actor:c.actor,at:now});return s;
}
export function repository(storage,assertWriter=()=>{}){return {read:()=>upgrade(JSON.parse(storage.getItem(KEY)||'null')),commit(c,a){assertWriter();const s=transition(JSON.parse(storage.getItem(KEY)||'null'),c,a);storage.setItem(KEY,JSON.stringify(s));return s;}};}
export const money=(minor,currency,exponent=2)=>currency+' '+moneyToDecimal(moneyFromMinorUnits(BigInt(minor)<0n?-BigInt(minor):BigInt(minor),currency,exponent));
