import {sha256,canonical} from './checksum.js';import {membershipActive,groupMembers,fail} from '../create-join/model.js';import {assertAllocationSnapshot,moneyFromMinorUnits} from '../money-v1.js';
export const PORTABLE='chopdot-portable-v1',RECOVERY='chopdot-recovery-v1',MAX_BYTES=2097152;
const pick=(x,keys)=>Object.fromEntries(keys.filter(k=>x[k]!==undefined).map(k=>[k,structuredClone(x[k])]));
const secretKey=/private.?key|seed.?phrase|mnemonic|password|secret|token|credential|signing.?material|participant.?proof/i;
export function noSecrets(x){if(!x||typeof x!=='object')return;for(const[k,v]of Object.entries(x)){if(secretKey.test(k))fail('PRIVATE','Secret-like unexpected fields block this package. Nothing was copied.');noSecrets(v);}}
const expenseKeys=['id','groupId','ownerId','payerId','revision','description','date','money','allocation','participantIds','method','reviews','issues','deleted','receipt'];
function expense(e){noSecrets(e);return pick(e,expenseKeys);}
export function snapshot(s,actor,scope='account'){
 const groups=(s.groups?.length?s.groups:[s.group]).filter(g=>g&&!g.deleted&&membershipActive(s,actor,g.id)&&(scope==='account'||g.id===scope));if(scope!=='account'&&!groups.length)fail('ACCESS','This export group is unavailable.');const ids=new Set(groups.map(g=>g.id));groups.forEach(noSecrets);
 const participants=groups.flatMap(g=>groupMembers(s,g).map(p=>({id:p.id,groupId:g.id,label:p.id==='self'?s.gateD?.account?.displayName||'You':p.name,identityStatus:'unverified-export-reference',capabilityVersion:p.capabilityVersion||0,policyVersion:p.policyVersion||0,...(p.link?{linkReference:pick(p.link,['id','status','participantId'])}:{})})));
 const expenses=(s.expenses||[]).filter(e=>ids.has(e.groupId)).map(expense),history=(s.gateB?.history||[]).filter(h=>ids.has(h.after?.groupId||h.before?.groupId||h.groupId)).map(h=>({type:h.type,actor:h.actor,expenseId:h.expenseId,operationId:h.operationId,at:h.at,...(h.before?{before:expense(h.before)}:{}),...(h.after?{after:expense(h.after)}:{})}));
 const settlementHistory=(s.gateC?.payments||[]).filter(p=>p.groupIds.every(g=>ids.has(g))&&[p.payer,p.recipient].includes(actor)).map(p=>pick(p,['id','payer','recipient','currency','exponent','amount','original','confirmed','state','method','groupIds','sources','applications','createdAt','confirmedAt','closedAt','returnedAt']));settlementHistory.forEach(noSecrets);
 const records={groups:groups.map(g=>pick(g,['id','name','currency','exponent','ownerId','revision','archived','membershipManaged','kind','goal','target','control','removedMemberIds'])),participants,expenses,history,settlementHistory};return {scope,records,sourceVersion:sha256(canonical(records)),omissions:['Credentials, session/capability authority and connected wallet state','Raw receiving details and private account preferences','Savings positions/operations and external provider completeness are outside portable V1; imported savings workspaces must be held out.']};
}
export function packageBytes(data,{schema=PORTABLE,operationId,capturedAt=new Date().toISOString()}={}){const unsigned={manifest:{schema,version:1,capturedAt,scope:data.scope,sourceVersion:data.sourceVersion,operationId,included:['groups','expenses','splits','visible notes/issues','activity/history','settlement-history facts'],excluded:data.omissions,unresolvedIdentities:data.records.participants.filter(p=>p.identityStatus!=='verified').map(p=>[p.groupId,p.id]),checksumAlgorithm:'SHA-256 of canonical package excluding checksum'},records:data.records};const checksum=sha256(canonical(unsigned)),artifact={...unsigned,manifest:{...unsigned.manifest,checksum}};return canonical(artifact);}
export function inspectPackage(bytes,expectedSchema=PORTABLE){if(typeof bytes!=='string'||new TextEncoder().encode(bytes).length>MAX_BYTES)fail('SIZE','Choose a package no larger than 2 MiB.');let artifact;try{artifact=JSON.parse(bytes);}catch{fail('FORMAT','The package is malformed. No records changed.');}noSecrets(artifact);if(artifact.manifest?.schema!==expectedSchema||artifact.manifest.version!==1)fail('SCHEMA','This schema/version needs its owning migration path.');const checksum=artifact.manifest.checksum,unsigned=structuredClone(artifact);delete unsigned.manifest.checksum;if(checksum!==sha256(canonical(unsigned)))fail('CHECKSUM','Package integrity does not match. No records changed.');const r=artifact.records;if(!r||!['groups','participants','expenses','history','settlementHistory'].every(k=>Array.isArray(r[k])))fail('FORMAT','Required portable record classes are missing.');if(r.groups.length>100||r.expenses.length>10000||r.participants.length>10000)fail('SIZE','The record set exceeds this bounded prototype.');if(new Set(r.groups.map(g=>g.id)).size!==r.groups.length||new Set(r.expenses.map(e=>e.id)).size!==r.expenses.length)fail('DUPLICATE','Repeated record identities need explicit resolution.');for(const g of r.groups){if(typeof g.id!=='string'||!g.id||typeof g.name!=='string'||!g.name.trim()||typeof g.currency!=='string')fail('GROUP','Invalid group context.');}
 for(const p of r.participants){if(typeof p.id!=='string'||!r.groups.some(g=>g.id===p.groupId)||typeof p.label!=='string')fail('IDENTITY','Participant linkage is unresolved or malformed.');}
 for(const e of r.expenses){if(typeof e.id!=='string'||!r.groups.some(g=>g.id===e.groupId)||!Array.isArray(e.participantIds)||!e.participantIds.every(id=>r.participants.some(p=>p.groupId===e.groupId&&p.id===id))||!r.participants.some(p=>p.id===e.payerId&&p.groupId===e.groupId))fail('IDENTITY','Expense references need exact group-scoped identities.');try{assertAllocationSnapshot(e.allocation,e.participantIds);if(canonical(e.money)!==canonical(e.allocation.total))throw Error('Total mismatch');}catch{fail('MONEY','Exact MoneyV1 allocation or source total is invalid.');}if(!Number.isInteger(e.revision)||e.revision<1)fail('VERSION','Invalid source version.');}
 return artifact;
}
export function mergePreview(s,actor,artifact,{ownIdentity=false}={}){if(!ownIdentity)fail('IDENTITY','Explicitly confirm which exported self references belong to your current account. Names alone never resolve identity.');const r=artifact.records,groups=[],expenses=[],participants=[],held=[],preserved=[],duplicates=[];
 for(const g of r.groups){const current=[s.group,...s.groups].find(x=>x?.id===g.id);if(g.kind==='savings'){held.push({id:g.id,reason:'Savings positions are not present in this V1 package'});continue;}if(current){if(!membershipActive(s,actor,g.id))fail('ACCESS','An existing inaccessible group cannot be revived by import.');preserved.push(g.id);}else{if((g.ownerId||'self')!=='self'){held.push({id:g.id,reason:'Group ownership identity is unresolved'});continue;}groups.push({...structuredClone(g),membershipManaged:true,provenance:{source:'imported',checksum:artifact.manifest.checksum},revision:g.revision||1});}}
 const groupIds=new Set([...groups.map(g=>g.id),...preserved]);for(const p of r.participants.filter(p=>p.id!=='self'&&groupIds.has(p.groupId))){const current=s.people.find(q=>q.id===p.id);if(current){if(current.groupId!==p.groupId)fail('IDENTITY','A stable Participant reference collides across groups.');continue;}participants.push({id:p.id,groupId:p.groupId,name:p.label,identity:'guest',capabilityVersion:Number.isInteger(p.capabilityVersion)?p.capabilityVersion:1,policyVersion:Number.isInteger(p.policyVersion)?p.policyVersion:1,provenance:{source:'imported-unverified',checksum:artifact.manifest.checksum},...(p.linkReference?{link:{...p.linkReference,status:['pending','unknown'].includes(p.linkReference.status)?p.linkReference.status:'unresolved'}}:{})});}
 for(const e of r.expenses){if(!groupIds.has(e.groupId)){held.push({id:e.id,reason:'Owning group is held out'});continue;}const current=s.expenses.find(q=>q.id===e.id);if(current){if(current.groupId!==e.groupId)fail('IDENTITY','Expense identity collides across groups.');if(canonical(expense(current))===canonical(e))duplicates.push(e.id);else held.push({id:e.id,reason:(current.revision||1)>=e.revision?'Preserve newer/current accepted record':'Different incoming version requires its owner; no automatic overwrite'});continue;}expenses.push({...structuredClone(e),provenance:{source:'imported-unverified',checksum:artifact.manifest.checksum}});}
 return {groups,participants,expenses,held,preserved,duplicates,sourceChecksum:artifact.manifest.checksum};
}
export function validatePortability(s,kind,p,actor){if(!['data-export','data-backup','data-import','data-restore'].includes(kind))fail('COMMAND','Unsupported data operation.');if(kind==='data-export'||kind==='data-backup'){const exact=snapshot(s,actor,p.scope);if(exact.sourceVersion!==p.sourceVersion)fail('STALE','The source snapshot changed. Prepare a fresh export review.');const schema=kind==='data-backup'?RECOVERY:PORTABLE,bytes=packageBytes(exact,{schema,operationId:p.artifactId,capturedAt:p.capturedAt});if(bytes!==p.bytes)fail('SNAPSHOT','The reviewed bytes do not match this exact scope and source version.');inspectPackage(bytes,schema);return exact;}
 const artifact=inspectPackage(p.bytes,kind==='data-restore'?RECOVERY:PORTABLE),plan=mergePreview(s,actor,artifact,{ownIdentity:p.ownIdentity});if(canonical(plan)!==canonical(p.plan))fail('STALE','Current merge facts changed. Review the exact apply/hold/preserve set again.');return plan;
}
export function effectPortability(s,o,now){const x=s.expansion,p=o.payload;if(['data-export','data-backup'].includes(o.kind)){x.artifacts.push({id:p.artifactId,operationId:o.id,owner:o.actor,kind:o.kind,bytes:p.bytes,checksum:JSON.parse(p.bytes).manifest.checksum,createdAt:now,delivery:'not-requested'});return;}
 const artifact=inspectPackage(p.bytes,o.kind==='data-restore'?RECOVERY:PORTABLE),plan=p.plan;s.groups.push(...structuredClone(plan.groups));s.people.push(...structuredClone(plan.participants));s.expenses.push(...structuredClone(plan.expenses));x.imports.push({id:o.id,actor:o.actor,checksum:plan.sourceChecksum,appliedGroups:plan.groups.map(g=>g.id),appliedExpenses:plan.expenses.map(e=>e.id),held:plan.held,preserved:plan.preserved,duplicates:plan.duplicates,at:now});x.importedHistory.push({operationId:o.id,checksum:plan.sourceChecksum,history:structuredClone(artifact.records.history),settlementHistory:structuredClone(artifact.records.settlementHistory),authority:'imported-descriptive-only'});
 // Current session, grants, account binding, revocation and newer records are never restored.
}
