import {moneyToDecimal} from '../money-v1.js';
import {membershipActive} from '../create-join/model.js';
import {definitionView} from './definition-view.js';
import {snapshot,packageBytes,inspectPackage,mergePreview,PORTABLE,RECOVERY,MAX_BYTES} from './portability.js';
export function createPortabilityUI(context){
 const a=(label,action,kind='ghost',extra='')=>({label,action,kind,extra});
 const recordFacts=r=>[...r.groups.map(g=>['Group · '+g.id,g.name+' · default '+g.currency+' · '+(g.archived?'archived':'active')]),...r.participants.map(p=>['Participant · '+p.groupId+' / '+p.id,p.label+' · '+p.identityStatus]),...r.expenses.flatMap(e=>[['Expense · '+e.id,e.description+' · '+e.money.currency+' '+moneyToDecimal(e.money)+' · revision '+e.revision+' · '+(e.deleted?'deleted history':'accepted source record')],['Split · '+e.id,e.allocation.allocations.map(row=>row.participantId+': '+row.amount.currency+' '+moneyToDecimal(row.amount)).join('; ')]]),['Imported financial history','Descriptive only · no payment, retry, wallet or identity authority']];
 const planFacts=(plan,s)=>[...plan.held.map(h=>['Held · '+h.id,h.reason]),...plan.preserved.map(id=>['Preserve current · '+id,s.groups.find(g=>g.id===id)?.name||id]),...plan.duplicates.map(id=>['Exact duplicate · '+id,'Reuse current record · no second copy'])];
 const draftKey=(actor,family)=>actor+':data:'+family;
 function view(){const{s,actor,route,docs,defs,device,esc,staticScreen}=context(),family=route.family,o=s.expansion.operations[route.operation]?.actor===actor?s.expansion.operations[route.operation]:null,d=s.expansion.drafts[draftKey(actor,family)]||{},artifact=s.expansion.artifacts.find(x=>x.owner===actor&&x.id===(o?.payload.artifactId||route.id));let title,lead,notice,facts=[],actions=[],special='';
 if(o){facts=[['Scope',o.payload.scope||'Exact reviewed apply set'],['Status',o.status],['Operation',o.id]];if(o.payload.bytes){const reviewed=inspectPackage(o.payload.bytes,o.kind==='data-backup'||o.kind==='data-restore'?RECOVERY:PORTABLE);facts.push(['Schema',reviewed.manifest.schema],['Captured',reviewed.manifest.capturedAt],['Included',reviewed.manifest.included.join('; ')],['Excluded',reviewed.manifest.excluded.join('; ')],...recordFacts(reviewed.records));}if(o.payload.plan)facts.push(...planFacts(o.payload.plan,s),['New groups',o.payload.plan.groups.length],['New expenses',o.payload.plan.expenses.length],['Held out',o.payload.plan.held.length],['Preserved current',o.payload.plan.preserved.length]);
  if(o.status==='prepared'){title=o.kind==='data-export'?'Create this export?':o.kind==='data-backup'?'Create this backup?':o.kind==='data-import'?'Confirm import':'Apply this reviewed restore?';lead='This is the first effect. Only the exact reviewed snapshot and apply set are bound to this operation.';actions=[a(o.kind==='data-export'?'Create export':o.kind==='data-backup'?'Create backup':o.kind==='data-import'?'Confirm import':'Apply restore','data-submit','accent'),a('Cancel','data-cancel')];}
  else if(o.status==='succeeded'){title=artifact?'Package ready':o.kind==='data-import'?(o.payload.plan.groups.length?'Reviewed new group import completed':'No new group imported'):'Reviewed recovery data applied';lead=artifact?(artifact.delivery==='browser-requested'?'The browser download was requested. Its destination and durable storage are unverified.':'The selected snapshot was packaged locally. No external destination handoff has been requested.'):'Only the reviewed new records were applied. Current identity, credentials, authority and newer records were preserved.';if(artifact){facts.push(['SHA-256',artifact.checksum],['Delivery',artifact.delivery==='browser-requested'?'Browser download requested · location unverified':'Not requested']);actions.push(a('Request browser download','data-download','accent',`data-id="${esc(artifact.id)}"`));}else{const rec=s.expansion.imports.find(i=>i.id===o.id);notice=rec?.held.length?rec.held.map(h=>h.id+': '+h.reason).join('; '):'No records were held out.';}actions.push(a('Back to data tools','data-home'));}
  else{title=o.status==='no-effect'?'Verified no effect':'Result not established';lead='Navigation and reload cannot establish success. Reconcile this exact operation before any retry.';actions=[a(o.status==='no-effect'?'Retry same operation':'Check original result',o.status==='no-effect'?'data-retry':'data-check','accent'),a('Back to data tools','data-home')];}
 }else if(route.page==='preview'){
  if(d.bytes){const artifact=inspectPackage(d.bytes,family==='25'?RECOVERY:PORTABLE),plan=d.ownIdentity?mergePreview(s,actor,artifact,{ownIdentity:true,mode:family==='25'?'restore':'import'}):null;title=family==='25'?'Review recovery without restoring authority':'Review before importing a new group';lead='Checksum means byte integrity, not authentic or complete source truth. Names do not prove identity.';facts=[['Schema',artifact.manifest.schema],['Captured',artifact.manifest.capturedAt],['Source groups',artifact.records.groups.length],['Expenses',artifact.records.expenses.length],['Identity',d.ownIdentity?'You explicitly confirmed exported self references':'Unresolved · confirmation required']];facts.push(...recordFacts(artifact.records));if(plan){facts.push(...planFacts(plan,s),['Apply new groups',plan.groups.length],['Apply new expenses',plan.expenses.length],['Preserve current',plan.preserved.length],['Duplicate records',plan.duplicates.length],['Held out',plan.held.length]);notice=plan.held.map(h=>h.id+': '+h.reason).join('; ')||'No automatic member merge. Imported people remain unverified.';actions.push(a('Continue to final review','data-review-import','accent'));}else actions.push(a('These exported self references are me','data-identity','accent'));actions.push(a('Choose another package','data-picker'),a('Cancel import / restore','data-home'));}
  else if(d.exportData){title='Review this exact snapshot';lead='Values, statuses and identities remain as recorded. No artifact exists yet.';facts=[['Scope',d.exportData.scope],['Groups',d.exportData.records.groups.length],['Expenses',d.exportData.records.expenses.length],['Unresolved identity references',d.exportData.records.participants.length],['Source version',d.exportData.sourceVersion]];facts.push(...recordFacts(d.exportData.records));notice=d.exportData.omissions.join('; ');actions=[a('Final review','data-review-export','accent'),a('Change scope','data-home'),a('Cancel','data-home')];}
 }else if(route.page==='picker'){title=family==='25'?'Choose a readable recovery copy':'Choose import package';lead='Choose one local JSON package, up to 2 MiB. Reading and validation do not change your records.';special='<section class="card pad stack"><label for="data-file">Package file</label><input id="data-file" type="file" accept=".json,application/json"><label for="data-bytes">Or paste package JSON</label><textarea id="data-bytes" rows="6" aria-label="Package JSON"></textarea></section>';actions=[a('Inspect package','data-inspect','accent'),a('Cancel','data-home')];}
 else if(route.page==='boundary'){title='External storage remains outside this prototype';lead='No provider, sync, production encryption or retention is selected. A browser download request does not prove durable storage.';actions=[a('Return to storage','data-home','accent')];}
 else{title=family==='23'?'Review first. Import after.':family==='24'?'Take records out with their meaning intact':'Keep recovery understandable';lead=family==='23'?'Import creates a separate new group. It never merges into existing groups in V1.':family==='24'?'Choose account-wide or one authorized group. Export is read/copy only.':'This browser is the working copy. A package and a requested download do not prove durable backup.';if(family==='23')actions=[a('Choose import package','data-picker','accent')];else if(family==='24')actions=[a('Prepare account export','data-snapshot','accent','data-scope="account"'),...s.groups.filter(g=>!g.deleted&&membershipActive(s,actor,g.id)).map(g=>a('Export '+g.name,'data-snapshot','ghost',`data-scope="${esc(g.id)}"`))];else actions=[a('Prepare backup copy','data-snapshot','accent','data-scope="account"'),a('Choose recovery copy','data-picker'),a('Explore external sync','data-boundary')];actions.push(a('Import data','data-import-home'),a('Export my data','data-export-home'),a('Storage & recovery','data-storage-home'));const unresolved=Object.values(s.expansion.operations).filter(o=>o.actor===actor&&o.kind.startsWith('data-')&&['pending','unknown','no-effect'].includes(o.status));actions.push(...unresolved.map(o=>a('Reopen '+o.kind+' · '+o.status,'data-reopen','ghost',`data-id="${esc(o.id)}"`)));}
 const config={title:title||'Data tools',lead:lead||'',notice,facts,actions,special};
 if(family==='23'){const screen=staticScreen('23',route.page==='picker'?'source-picker':route.page==='preview'?'preview-detail':'entry-you'),main=screen.querySelector('main,.content');main.innerHTML=`<div><div class="eyebrow">Import data / group</div><h1 class="hero">${esc(config.title)}</h1><p class="lead">${esc(config.lead)}</p></div>${facts.length?`<section class="card pad stack">${facts.map(([k,v])=>`<div class="meta-row"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</section>`:''}${notice?`<div class="notice warn"><span>i</span><div>${esc(notice)}</div></div>`:''}${special}<div class="actions">${actions.map(x=>`<button class="btn ${x.kind}" data-action="${x.action}" ${x.extra}>${esc(x.label)}</button>`).join('')}</div>`;}
 else definitionView(docs[family],device,document.querySelector('#golden-style'),config,esc);
 }
 async function action(a,el){if(!a.startsWith('data-'))return false;const{s,actor,route,commit,prepare,submit,push,go}=context(),family=route.family,d=s.expansion.drafts[draftKey(actor,family)]||{},save=values=>commit({type:'draft',family:'data:'+family,values});
 if(a==='data-home')push({page:'entry',operation:'',id:''});else if(a==='data-import-home')go('23','entry');else if(a==='data-export-home')go('24','entry');else if(a==='data-storage-home')go('25','entry');else if(a==='data-picker'){save({});push({page:'picker',operation:''});}else if(a==='data-boundary')push({page:'boundary'});
 else if(a==='data-snapshot'){const exportData=snapshot(s,actor,el.dataset.scope||'account');save({exportData,capturedAt:new Date().toISOString(),artifactId:crypto.randomUUID()});push({page:'preview',operation:''});}
 else if(a==='data-review-export'){const kind=family==='25'?'data-backup':'data-export',p={scope:d.exportData.scope,sourceVersion:d.exportData.sourceVersion,capturedAt:d.capturedAt,artifactId:d.artifactId,bytes:packageBytes(d.exportData,{schema:family==='25'?RECOVERY:PORTABLE,operationId:d.artifactId,capturedAt:d.capturedAt})};push({page:'confirmation',operation:prepare(kind,p)});}
 else if(a==='data-inspect'){const file=document.querySelector('#data-file').files[0];if(file?.size>MAX_BYTES)throw Error('Choose a package no larger than 2 MiB.');const bytes=file?await file.text():document.querySelector('#data-bytes').value;inspectPackage(bytes,family==='25'?RECOVERY:PORTABLE);save({bytes,ownIdentity:false});push({page:'preview',operation:''});}
 else if(a==='data-identity'){save({...d,ownIdentity:true});push({},true);}
 else if(a==='data-review-import'){const artifact=inspectPackage(d.bytes,family==='25'?RECOVERY:PORTABLE),p={bytes:d.bytes,ownIdentity:d.ownIdentity,plan:mergePreview(s,actor,artifact,{ownIdentity:d.ownIdentity,mode:family==='25'?'restore':'import'})};push({page:'confirmation',operation:prepare(family==='25'?'data-restore':'data-import',p)});}
 else if(a==='data-submit')submit(route.operation);else if(a==='data-retry')submit(route.operation,true);else if(a==='data-check'){commit({type:'reconcile',id:route.operation});push({},true);}else if(a==='data-reopen')push({operation:el.dataset.id,page:'operation'});else if(a==='data-cancel'){commit({type:'cancel',id:route.operation});push({operation:'',page:'entry'});}
 else if(a==='data-download'){const artifact=s.expansion.artifacts.find(x=>x.id===el.dataset.id&&x.owner===actor);if(!artifact)throw Error('Your exact artifact is unavailable.');const url=URL.createObjectURL(new Blob([artifact.bytes],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=artifact.kind==='data-backup'?'chopdot-recovery.json':'chopdot-portable.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);commit({type:'artifact-download',id:artifact.id});push({},true);}else return false;return true;
 }
 return {view,action};
}
