import test from '../test-runner.mjs';import assert from 'node:assert/strict';
import {upgrade,transition} from './model.js';import {available,position,savingsSnapshot} from './savings.js';
const seed=()=>upgrade({group:{id:'g',name:'Existing',currency:'CHF'},groups:[{id:'g',name:'Existing',currency:'CHF'}],people:[],expenses:[],gateD:{session:{status:'active'},account:{displayName:'You'}}});
const c=(type,p={})=>({type,actor:'self',operationId:crypto.randomUUID(),...p});
function create(control='tracking'){let s=seed();s=transition(s,c('prepare',{id:'create',kind:'savings-create',payload:{id:'save',name:'Shared goal',currency:'CHF',exponent:2,goal:'300000',target:'2027-06-01',control,inviteNames:['Alex']}}));s=transition(s,c('submit',{id:'create'}));s=transition(s,c('result',{id:'create',result:'succeeded'}),'prototype-fixture');return s;}
const prepare=(s,kind='savings-add',amount='18001',id='money')=>transition(s,c('prepare',{id,kind,payload:savingsSnapshot(s,'self','save',kind,amount)}));
const result=(s,id='money',evidence={confirmation:true})=>transition(s,c('result',{id,result:'succeeded',evidence}),'prototype-fixture');
test('creation preserves expense identity and creates pending invites, not economic members',()=>{const s=create();assert.equal(s.groups.length,2);assert.equal(s.people.length,0);assert.equal(s.membership.invitations[0].status,'pending');assert.equal(available(s,s.group),0n);assert.deepEqual(s.expenses,[]);});
test('review and self report never become Available',()=>{let s=create();s=prepare(s);assert.equal(available(s,s.group),0n);s=transition(s,c('submit',{id:'money'}));assert.equal(available(s,s.group),0n);assert.throws(()=>result(s,'money',{}),/confirmation/);s=result(s);assert.equal(available(s,s.group),18001n);assert.equal(position(s,s.group,'self'),18001n);});
test('unknown reload cannot retry or bypass original savings operation',()=>{let s=prepare(create());s=transition(s,c('submit',{id:'money'}));s=transition(s,c('reconcile',{id:'money'}));s=upgrade(JSON.parse(JSON.stringify(s)));assert.throws(()=>transition(s,c('retry',{id:'money'})),/non-acceptance/);assert.throws(()=>prepare(s,'savings-withdraw','1','other'),/existing operation/);assert.equal(available(s,s.group),0n);});
test('verified no effect retries same identity then confirms once',()=>{let s=prepare(create());s=transition(s,c('submit',{id:'money'}));s=transition(s,c('result',{id:'money',result:'no-effect'}),'prototype-fixture');s=transition(s,c('retry',{id:'money'}));s=result(s);s=result(s);assert.equal(s.expansion.savingsEvents.length,1);assert.equal(s.expansion.savingsEvents[0].id,'money');});
test('own-position exact withdrawal never touches another group',()=>{let s=prepare(create());s=transition(s,c('submit',{id:'money'}));s=result(s);const others=JSON.stringify(s.groups[0]);assert.throws(()=>prepare(s,'savings-withdraw','18002','too-much'),/own confirmed position/);s=prepare(s,'savings-withdraw','10001','withdraw');s=transition(s,c('submit',{id:'withdraw'}));assert.equal(available(s,s.group),18001n);s=result(s,'withdraw');assert.equal(available(s,s.group),8000n);assert.equal(JSON.stringify(s.groups[0]),others);});
test('shared-account fixture needs finality plus configured group rule, no UI self approval',()=>{let s=prepare(create('shared'));s=transition(s,c('submit',{id:'money'}));assert.throws(()=>result(s),/finality/);s=result(s,'money',{confirmation:true,externalFinality:true});s=prepare(s,'savings-withdraw','100','withdraw');s=transition(s,c('submit',{id:'withdraw'}));assert.throws(()=>result(s,'withdraw',{confirmation:true,externalFinality:true}),/group approval/);s=result(s,'withdraw',{confirmation:true,externalFinality:true,groupRule:true});assert.equal(position(s,s.group,'self'),17901n);});
test('stale position blocks result and returned contribution appends exact history',()=>{let s=prepare(create());s=transition(s,c('submit',{id:'money'}));s.group.revision++;s.groups.find(g=>g.id==='save').revision++;assert.throws(()=>result(s),/current group/);s=prepare(create());s=transition(s,c('submit',{id:'money'}));s=result(s);s=transition(s,c('prepare',{id:'returned',kind:'savings-return',payload:{groupId:'save',eventId:'money'}}));s=transition(s,c('submit',{id:'returned'}));s=result(s,'returned');assert.equal(available(s,s.group),0n);assert.equal(s.expansion.savingsEvents.length,2);assert.equal(s.expansion.savingsEvents[0].delta,'18001');assert.equal(s.expansion.savingsEvents[1].returnOf,'money');});

test('unknown savings kinds cannot bypass own-position or configured-rule validators',()=>{const s=create('shared');for(const kind of ['savings-evil','savings-contribute','savings-withdraw-other'])assert.throws(()=>transition(s,c('prepare',{id:kind,kind,payload:savingsSnapshot(s,'self','save',kind,'100000')})),/Unsupported savings operation/);assert.equal(available(s,s.group),0n);});
