import {savingsGroups,savingsGroup,position,available,savingsSnapshot} from './savings.js';
import {groupMembers} from '../create-join/model.js';
import {moneyFromPreviewDecimal,moneyToDecimal} from '../money-v1.js';
export function createSavingsUI(context){
 const button=(label,action,cls='primary',extra='')=>`<button class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
 const info=(copy)=>`<div class="info gray"><span aria-hidden="true">ⓘ</span><div>${copy}</div></div>`;
 const facts=(rows,esc)=>`<div class="card summary-card">${rows.map(([k,v])=>`<div class="fact"><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}</div>`;
 function view(){const {s,actor,route,staticScreen,device,esc,money,name}=context(),draft=s.expansion.drafts[actor+':savings']||{},o=s.expansion.operations[route.operation]?.actor===actor?s.expansion.operations[route.operation]:null;
 if(route.family==='16'){
  const g=route.page==='home'&&s.groups.some(g=>g.id===route.group)?savingsGroup(s,route.group,actor):null,page=o?o.status==='prepared'?'review':o.status==='succeeded'?'home':o.status==='no-effect'?'failed':'pending':route.page==='list'?'start':route.page||'start';
  const screen=staticScreen('16',page),main=screen.querySelector('main'),footer=screen.querySelector('footer');
  if(o&&o.status!=='prepared'&&o.status!=='succeeded'){main.innerHTML=`<h1 class="big-title">${o.status==='no-effect'?'No group created.':'Still checking.'}</h1>${info('Keep this same creation operation. Checking cannot fabricate a result.')}${facts([['Group',o.payload.name],['Result',o.status==='no-effect'?'Not created':'Still checking']],esc)}`;footer.innerHTML=button(o.status==='no-effect'?'Retry same operation':'Check original result',o.status==='no-effect'?'savings-retry':'savings-check')+button('Back','back','secondary-btn');return;}
  if(page==='start'){const list=document.createElement('div');list.className='card list-card';for(const goal of savingsGroups(s,actor))list.innerHTML+=`<button class="list-row" data-action="savings-open" data-id="${esc(goal.id)}"><div class="row-main"><b>${esc(goal.name)}</b><span>${money(available(s,goal),goal.currency,goal.exponent)} confirmed</span></div></button>`;main.append(list);footer.innerHTML=button('New savings group','savings-goal');return;}
  if(page==='goal'){main.querySelectorAll('.card').forEach(n=>n.remove());const rows=[['Name','name','text',draft.name||''],['Goal','goal','text',draft.goalText||''],['Target date','target','date',draft.target||'']];main.querySelectorAll('.form-label').forEach(n=>n.remove());const form=document.createElement('div');form.className='savings-form';form.innerHTML=rows.map(([title,key,type,value])=>`<label class="form-label">${title}<input class="card" aria-label="Savings ${title}" name="${key}" type="${type}" value="${esc(value)}"></label>`).join('')+`<label class="form-label">Currency<select aria-label="Savings currency" name="currency">${['CHF','EUR','USD','DOT'].map(c=>`<option ${draft.currency===c?'selected':''}>${c}</option>`).join('')}</select></label>`;main.prepend(form);footer.innerHTML=button('Choose people','savings-people')+button('Back','back','secondary-btn');return;}
  if(page==='people'){const list=main.querySelector('.list-card');list.innerHTML=`<div class="list-row"><div class="row-main"><b>${esc(name(s,actor))} · You</b><span>Current account</span></div><span class="pill2">Added</span></div>`;for(const p of s.people.filter(p=>p.groupId===draft.sourceGroupId&&!s.groups.find(g=>g.id===p.groupId)?.removedMemberIds?.includes(p.id))){list.innerHTML+=`<label class="list-row"><div class="row-main"><b>${esc(p.name)}</b><span>Invite to this new group · a distinct Participant is created only after joining</span></div><input name="invite:${esc(p.id)}" type="checkbox" ${draft.inviteIds?.includes(p.id)?'checked':''}></label>`;}footer.innerHTML=button('Continue','savings-holding')+button('Back','back','secondary-btn');return;}
  if(page==='holding'){screen.querySelectorAll('.control-option').forEach((n,i)=>{n.dataset.action='savings-control';n.dataset.control=i?'shared':'tracking';n.setAttribute('role','button');n.setAttribute('tabindex','0');n.querySelector('.radio').classList.toggle('on',(draft.control||'tracking')===(i?'shared':'tracking'));});footer.innerHTML=button('Review group','savings-create-review')+button('Back','back','secondary-btn');return;}
  if(page==='review'){main.innerHTML=`<div class="card summary-card"><div class="summary-hero"><h2>${esc(o.payload.name)}</h2><p>Save toward a shared goal.</p></div></div>${facts([['Goal',money(o.payload.goal,o.payload.currency,o.payload.exponent)],['Target date',o.payload.target],['People',name(s,actor)+(o.payload.inviteNames.length?' · Invitations: '+o.payload.inviteNames.join(', '):'')],['Money stays',o.payload.control==='tracking'?'With each person':'Group-controlled external account'],['On create','No money moves']],esc)}${info('Joining and account binding remain separate. Selected names do not grant access or financial authority.')}`;footer.innerHTML=button('Create savings group','savings-submit')+button('Back','back','secondary-btn');return;}
  if(page==='home'){const current=g||savingsGroup(s,o.payload.id,actor),members=groupMembers(s,current),a=available(s,current),goal=BigInt(current.goal),percent=goal>0n?a*10000n/goal:0n;screen.querySelector('.header-title b').textContent=current.name;screen.querySelector('.header-title span').textContent=`${members.length} people · ${current.currency}`;screen.querySelector('.meta-copy b').textContent='Your position · '+money(position(s,current,actor),current.currency,current.exponent);screen.querySelector('.meta-copy span').textContent=members.length+' savers';const stack=screen.querySelector('.people-stack');stack.innerHTML=members.map(p=>`<span class="person-dot">${esc(name(s,p.id).slice(0,1))}</span>`).join('');const values=screen.querySelectorAll('.savings-goal-top b');values[0].textContent=money(a,current.currency,current.exponent);values[1].textContent=money(goal,current.currency,current.exponent);screen.querySelector('.progress i').style.width=String(Number(percent>10000n?10000n:percent)/100)+'%';const meta=screen.querySelectorAll('.progress-meta span');meta[0].textContent=String(percent/100n)+'% complete';meta[1].textContent=current.target;
 const list=screen.querySelector('.savings-people');list.innerHTML=members.map(p=>`<div class="list-row"><div class="avatar2">${esc(name(s,p.id).slice(0,1))}</div><div class="row-main"><b>${esc(p.id===actor?'You':name(s,p.id))}</b><span>Confirmed position</span></div><span class="amount">${money(position(s,current,p.id),current.currency,current.exponent)}</span></div>`).join('');const recent=screen.querySelector('.savings-people').nextElementSibling.nextElementSibling;recent.innerHTML=(s.expansion.savingsEvents||[]).filter(e=>e.groupId===current.id).slice(-4).reverse().map(e=>`<div class="list-row"><div class="row-main"><b>${esc(name(s,e.actor))} · ${esc(e.kind)}</b><span>${esc(e.at)} · confirmed</span></div><span class="amount">${money(e.delta,current.currency,current.exponent)}</span></div>`).join('')||'<div class="list-row">No confirmed changes yet.</div>';
 screen.querySelector('.savings-rule div').textContent=current.control==='tracking'?'Money stays with each member. Available changes only after confirmation.':'Funds remain in the group-controlled external account. Withdrawal requires the configured group rule and confirmed execution.';screen.querySelectorAll('a').forEach(n=>{const label=n.textContent.trim();n.dataset.action=n.getAttribute('aria-label')==='Group settings'?'savings-settings':label==='Withdraw'?'savings-withdraw':label==='Add money'||n.getAttribute('aria-label')==='Add money'?'savings-add':label==='Pots'?'savings-list':'back';});return;}
 }else{
  const g=savingsGroup(s,route.group,actor),kind=o?.kind||(['savings-add','savings-withdraw'].includes(route.kind)?route.kind:'savings-add'),isWithdraw=kind==='savings-withdraw',a=available(s,g),p=position(s,g,actor),amount=o?.payload.amount||(o?.kind==='savings-return'?s.expansion.savingsEvents.find(e=>e.id===o.payload.eventId)?.delta:'0')||'0',draft=s.expansion.drafts[actor+':savings-money:'+g.id]||{},page=o?o.status==='prepared'?(isWithdraw?'withdraw-review':'add-review'):o.status==='succeeded'?(kind==='savings-return'?'returned':isWithdraw?'withdraw-complete':'add-complete'):o.status==='no-effect'?'unknown-not-executed':o.status==='unknown'?'unknown':isWithdraw?'withdraw-pending':'add-sent':isWithdraw?'withdraw':'add';
  const screen=staticScreen('17',page),main=screen.querySelector('main'),footer=screen.querySelector('footer');const walker=document.createTreeWalker(screen,NodeFilter.SHOW_TEXT);while(walker.nextNode())walker.currentNode.textContent=walker.currentNode.textContent.replaceAll('Alps House Fund',g.name).replaceAll('Dev · You',name(s,actor)+' · You').replaceAll('CHF 1240.00',money(a,g.currency,g.exponent)).replaceAll('CHF 520.00',money(p,g.currency,g.exponent)).replaceAll('CHF 180.00',money(amount,g.currency,g.exponent)).replaceAll('CHF 100.00',money(amount,g.currency,g.exponent)).replaceAll('CHF 1420.00',money(a+BigInt(amount),g.currency,g.exponent)).replaceAll('41%',String(a*100n/BigInt(g.goal))+'%');
  const settled=o?.status==='succeeded',delta=BigInt(amount)*(isWithdraw||kind==='savings-return'?-1n:1n),projected=settled?a:a+delta,projectedPosition=settled?p:p+delta,fmt=n=>money(n,g.currency,g.exponent),pct=n=>String(n*100n/BigInt(g.goal))+'%';
  const bindings={'current-available':fmt(a),'current-position':fmt(p),'current-progress-copy':pct(a),'add-amount':fmt(amount),'withdraw-amount':fmt(amount),'op-amount':fmt(amount),'add-projected':fmt(projected),'withdraw-projected':fmt(projected),'withdraw-position-projected':fmt(projectedPosition),'add-confirmed-available':fmt(a),'withdraw-confirmed-available':fmt(a),'add-confirmed-position':fmt(p),'withdraw-confirmed-position':fmt(p),'add-progress':pct(a),'withdraw-progress':pct(a),'add-complete-title':fmt(amount)+' added','withdraw-complete-title':fmt(amount)+' removed','add-wait-copy':fmt(amount)+' is not Available yet','withdraw-wait-copy':fmt(amount)+' is not removed yet','not-executed-title':'Not executed','recovered-confirmed':fmt(amount)+' confirmed'};
  for(const[key,value]of Object.entries(bindings))screen.querySelectorAll('[data-bind-'+key+']').forEach(n=>n.textContent=value);
  for(const row of screen.querySelectorAll('.fact')){const label=row.querySelector('span')?.textContent.trim(),b=row.querySelector('b');if(!b)continue;if(label==='Currency')b.textContent=g.currency;if(['Available','Available shown','Available now'].includes(label))b.textContent=fmt(a);if(label==='Goal progress')b.textContent=pct(a);}
  if(!o){const input=main.querySelector('input');input.value=draft.amountText||'';input.name='savings-amount';input.setAttribute('aria-label',isWithdraw?'Withdrawal amount':'Contribution amount');main.querySelector('.amount-input strong').textContent=g.currency;main.querySelector('.quick')?.remove();main.querySelectorAll('[data-bind-add-projected]').forEach(n=>n.textContent='After current confirmation');footer.innerHTML=button(isWithdraw?'Review withdrawal':'Review contribution','savings-money-review')+button('Cancel','savings-home','secondary-btn');}
  else if(o.status==='prepared')footer.innerHTML=button(isWithdraw?'Request withdrawal':g.control==='tracking'?'I added '+money(amount,g.currency,g.exponent):'Submit contribution','savings-submit')+button('Back','back','secondary-btn');
  else if(o.status==='succeeded'){footer.innerHTML=button('Back to group','savings-home');if(kind==='savings-add')footer.innerHTML+=button('Review returned contribution','savings-return-review','secondary-btn');}
  else footer.innerHTML=button(o.status==='no-effect'?'Retry same operation':'Check original result',o.status==='no-effect'?'savings-retry':'savings-check')+button('Back to group','savings-home','secondary-btn');
  if(o&&g.control==='shared'&&['pending','unknown'].includes(o.status)){const first=main.querySelector('.timeline-row b');if(first)first.textContent=isWithdraw?'Withdrawal submitted for group approval':'External contribution submitted';main.querySelectorAll('.info div').forEach(n=>n.textContent='Available changes only after the configured confirmation authority establishes external finality'+(isWithdraw?' and the group withdrawal rule.':'.'));}
  if(kind==='savings-return'){const hero=main.querySelector('.summary-hero')||main.querySelector('.status-card');if(hero)hero.innerHTML='<h2>'+esc(settled?fmt(amount)+' returned':o.status==='prepared'?'Review returned contribution':'Return awaiting confirmation')+'</h2><p>The earlier confirmed contribution remains in history.</p>';main.querySelectorAll('.summary-card').forEach(n=>n.remove());if(!main.contains(hero))main.insertAdjacentHTML('afterbegin','<div class="card summary-hero"><h2>'+esc(settled?fmt(amount)+' returned':o.status==='prepared'?'Review returned contribution':'Return awaiting confirmation')+'</h2><p>The earlier confirmed contribution remains in history.</p></div>');screen.querySelector('.header-title b').textContent=settled?'Returned contribution':o.status==='prepared'?'Review returned contribution':'Returned contribution';screen.querySelector('.header-title span').textContent='Earlier confirmation retained';main.insertAdjacentHTML('beforeend',facts([['Confirmed Available',fmt(a)],['Returned contribution',fmt(amount)],['After confirmation',fmt(projected)]],esc));footer.innerHTML=o.status==='prepared'?button('Record returned contribution','savings-submit')+button('Back','back','secondary-btn'):settled?button('Back to group','savings-home'):button(o.status==='no-effect'?'Retry same operation':'Check original result',o.status==='no-effect'?'savings-retry':'savings-check')+button('Back to group','savings-home','secondary-btn');}
  if(o&&!['prepared','succeeded'].includes(o.status))screen.querySelector('.header-title b').textContent=kind==='savings-return'?'Returned contribution':isWithdraw?'Withdrawal':'Contribution';
 }
 }
 function action(a,el){if(!a.startsWith('savings-'))return false;const {s,actor,route,commit,prepare,submit,push,go}=context(),d=s.expansion.drafts[actor+':savings']||{};
 const save=(values,family='savings')=>commit({type:'draft',family,values});
 if(a==='savings-list')go('16','list',{group:'',operation:''});
 else if(a==='savings-open')go('16','home',{group:el.dataset.id});
 else if(a==='savings-goal'){save({...d,sourceGroupId:s.group?.id});go('16','goal',{group:''});}
 else if(a==='savings-people'){const inputs=Object.fromEntries([...document.querySelectorAll('#device input,#device select')].map(i=>[i.name,i.value]));save({...d,name:inputs.name,goalText:inputs.goal,currency:inputs.currency,target:inputs.target,sourceGroupId:d.sourceGroupId||s.group?.id});push({page:'people'});}
 else if(a==='savings-holding'){save({...d,inviteIds:[...document.querySelectorAll('input[type=checkbox]:checked')].map(n=>n.name.slice(7))});push({page:'holding'});}
 else if(a==='savings-control'){save({...d,control:el.dataset.control});push({},true);}
 else if(a==='savings-create-review'){const exponent=d.currency==='DOT'?6:2,goal=moneyFromPreviewDecimal(d.goalText,d.currency,exponent).minorUnits,id=prepare('savings-create',{id:crypto.randomUUID(),name:d.name,goal,currency:d.currency,exponent,target:d.target,control:d.control||'tracking',inviteNames:(d.inviteIds||[]).map(id=>s.people.find(p=>p.id===id)?.name).filter(Boolean)});push({page:'review',operation:id});}
 else if(a==='savings-home')go('16','home',{group:route.group,operation:''});
 else if(a==='savings-settings')go('26','settings',{group:route.group});
 else if(['savings-add','savings-withdraw'].includes(a)){const pending=Object.values(s.expansion.operations).find(o=>o.actor===actor&&o.kind.startsWith('savings-')&&o.payload.groupId===route.group&&['prepared','pending','unknown','no-effect'].includes(o.status));go('17',a==='savings-add'?'add':'withdraw',{group:route.group,kind:a,operation:pending?.id||''});}
 else if(a==='savings-money-review'){const g=savingsGroup(s,route.group,actor),input=document.querySelector('input[name=savings-amount]'),amount=moneyFromPreviewDecimal(input.value,g.currency,g.exponent).minorUnits;save({amountText:input.value},'savings-money:'+g.id);if(!['savings-add','savings-withdraw'].includes(route.kind))throw Error('Choose Add money or Withdraw from this group.');const id=prepare(route.kind,savingsSnapshot(s,actor,g.id,route.kind,amount));push({page:'review',operation:id});}
 else if(a==='savings-submit')submit(route.operation);
 else if(a==='savings-retry')submit(route.operation,true);
 else if(a==='savings-check'){commit({type:'reconcile',id:route.operation});push({},true);}
 else if(a==='savings-return-review'){const original=s.expansion.operations[route.operation],id=prepare('savings-return',{groupId:route.group,eventId:original.id});push({page:'returned',operation:id});}
 else return false;return true;
 }
 function input(el){const {actor,route,s,commit}=context();if(!['16','17'].includes(route.family)||!el.name)return false;if(el.name==='savings-amount')commit({type:'draft',family:'savings-money:'+route.group,values:{amountText:el.value}});else if(['name','goal','target','currency'].includes(el.name)){const d=s.expansion.drafts[actor+':savings']||{};commit({type:'draft',family:'savings',values:{...d,[el.name==='goal'?'goalText':el.name]:el.value}});}return true;}
 return {view,action,input};
}
