// J16/J17 approved contract. Records share the prototype's canonical store.
import {groupMembers,membershipActive,fail} from '../create-join/model.js';
import {moneyFromMinorUnits} from '../money-v1.js';
export const savingsGroups=(s,actor)=>s.groups.filter(g=>g.kind==='savings'&&!g.deleted&&membershipActive(s,actor,g.id));
export function savingsGroup(s,id,actor){const g=s.groups.find(g=>g.id===id&&g.kind==='savings'&&!g.deleted);if(!g||!membershipActive(s,actor,id))fail('ACCESS','This savings group is unavailable.');return g;}
export function position(s,g,actor){return (s.expansion.savingsEvents||[]).filter(e=>e.groupId===g.id&&e.actor===actor).reduce((n,e)=>n+BigInt(e.delta),0n);}
export function available(s,g){return (s.expansion.savingsEvents||[]).filter(e=>e.groupId===g.id).reduce((n,e)=>n+BigInt(e.delta),0n);}
export function savingsSnapshot(s,actor,groupId,kind,amount){const g=savingsGroup(s,groupId,actor);return {groupId,member:actor,amount:String(amount),currency:g.currency,exponent:g.exponent,control:g.control,position:position(s,g,actor).toString(),positionVersion:(s.expansion.savingsEvents||[]).filter(e=>e.groupId===g.id&&e.actor===actor).length,groupVersion:g.revision};}
export function validateSavings(s,kind,p,actor){
 if(!['savings-create','savings-add','savings-withdraw','savings-return'].includes(kind))fail('COMMAND','Unsupported savings operation.');
 if(kind==='savings-create'){
  if(actor!=='self')fail('ACCOUNT','Create savings through your own account.');if(!p.id||s.groups.some(g=>g.id===p.id))fail('IDENTITY','Keep a distinct savings group identity.');if(!p.name?.trim()||p.name.length>80)fail('NAME','Name the savings group.');if(!['CHF','EUR','USD','DOT'].includes(p.currency)||p.exponent!==(p.currency==='DOT'?6:2))fail('CURRENCY','Choose one exact supported currency or asset.');const goal=moneyFromMinorUnits(p.goal,p.currency,p.exponent);if(BigInt(goal.minorUnits)<=0n)fail('GOAL','Enter a positive exact goal.');if(!/^\d{4}-\d{2}-\d{2}$/.test(p.target)||Number.isNaN(Date.parse(p.target)))fail('DATE','Choose a target date.');if(!['tracking','shared'].includes(p.control))fail('CONTROL','Choose where money stays.');if(!Array.isArray(p.inviteNames)||p.inviteNames.some(n=>typeof n!=='string'||!n.trim()||n.length>60))fail('MEMBERS','Choose invitation names explicitly.');return p;
 }
 const g=savingsGroup(s,p.groupId,actor);
 if(kind==='savings-return'){const event=(s.expansion.savingsEvents||[]).find(e=>e.id===p.eventId&&e.actor===actor&&e.groupId===g.id&&e.kind==='contribution');if(!event||s.expansion.savingsEvents.some(e=>e.returnOf===event.id))fail('RETURN','Only an existing confirmed contribution can be returned once.');if(position(s,g,actor)<BigInt(event.delta))fail('POSITION','The confirmed contribution cannot be removed from this current position.');return {g,event};}
 if(!['savings-add','savings-withdraw'].includes(kind))fail('COMMAND','Unsupported savings operation.');
 if(p.member!==actor)fail('OWNER','Only your own savings position can be changed.');const exact=savingsSnapshot(s,actor,p.groupId,kind,p.amount);if(JSON.stringify(exact)!==JSON.stringify(p))fail('STALE','Review the current group and your confirmed position again.');const amount=moneyFromMinorUnits(p.amount,p.currency,p.exponent);if(BigInt(amount.minorUnits)<=0n)fail('AMOUNT','Enter an exact amount greater than zero.');if(g.archived)fail('ARCHIVED','Restore this savings group before a new contribution or withdrawal.');if(kind==='savings-withdraw'&&BigInt(p.amount)>position(s,g,actor))fail('POSITION','Withdraw only from your own confirmed position.');return exact;
}
export function savingsResultGuard(s,o,evidence){if(!o.kind.startsWith('savings-')||o.kind==='savings-create')return;const g=savingsGroup(s,o.payload.groupId,o.actor);if(evidence?.confirmation!==true)fail('CONFIRMATION','Waiting is not confirmation. Use the explicit current confirmation-authority fixture.');if(g.control==='shared'&&(evidence.externalFinality!==true||o.kind==='savings-withdraw'&&evidence.groupRule!==true))fail('GROUP_RULE','External finality and the configured group approval rule must be satisfied. The UI cannot self-approve.');}
export function effectSavings(s,o,now){const p=o.payload;
 if(o.kind==='savings-create'){const g={id:p.id,name:p.name.trim(),currency:p.currency,exponent:p.exponent,goal:p.goal,target:p.target,control:p.control,kind:'savings',ownerId:o.actor,revision:1,membershipManaged:true,localOnly:true};s.groups.push(g);s.group=structuredClone(g);s.membership||={sequence:0,invitations:[],operations:{},history:[],environment:{}};for(const n of p.inviteNames)s.membership.invitations.push({id:crypto.randomUUID(),groupId:g.id,inviterId:o.actor,inviterName:s.gateD.account.displayName||'Group owner',name:n.trim(),kind:'person',redemptions:[],status:'pending',createdAt:now});return;}
 const g=s.groups.find(g=>g.id===p.groupId),events=s.expansion.savingsEvents;
 if(o.kind==='savings-return'){const e=events.find(e=>e.id===p.eventId);events.push({id:o.id,groupId:g.id,actor:o.actor,kind:'returned',delta:(-BigInt(e.delta)).toString(),currency:g.currency,exponent:g.exponent,returnOf:e.id,at:now});}
 else events.push({id:o.id,groupId:g.id,actor:o.actor,kind:o.kind==='savings-add'?'contribution':'withdrawal',delta:(BigInt(p.amount)*(o.kind==='savings-add'?1n:-1n)).toString(),currency:p.currency,exponent:p.exponent,at:now});
}
