import {scopeProof} from '../gate-c/model.js';import {membershipActive,fail} from '../create-join/model.js';import {canonical} from './checksum.js';
export function walletAction(s,actor,paymentId){const p=s.gateC?.payments.find(p=>p.id===paymentId);if(!p||p.method!=='Wallet'||p.payer!==actor||p.groupIds.some(g=>!membershipActive(s,actor,g)))fail('CALLER','Open the exact authorized wallet payment from Settle Up.');if(p.currency!=='CHF'||p.amount!=='5430'||p.transfer?.quote!=='approved-demo-5430-chf')fail('QUOTE','Keep the existing approved demo quote. No other conversion is available.');return {paymentId:p.id,proof:scopeProof(p),transfer:p.transfer,recipient:p.recipient};}
export function walletTransition(s,c,authority,now){const x=s.expansion;x.wallets||={};let w=x.wallets[c.actor]||={version:0,status:'disconnected',connection:null,execution:null};const fixture=()=>{if(authority!=='prototype-fixture')fail('AUTHORITY','Only an explicit inert wallet result fixture can establish this outcome.');};const exact=()=>{if(!w.execution)fail('ACTION','Review an exact caller action.');const action=walletAction(s,c.actor,w.execution.action.paymentId);if(canonical(action)!==canonical(w.execution.action))fail('STALE','The payment attempt or exact scope changed. Return to its owner.');const p=s.gateC.payments.find(p=>p.id===action.paymentId);if(!['approval_waiting','submitted','checking','unknown','recovering'].includes(p.state))fail('CALLER','The originating payment is no longer awaiting this execution. Return to its current owner status.');return action;};
 const active=()=>w.execution&&['signature-pending','signature-unknown','signed','submitting','pending','submission-unknown'].includes(w.execution.status);
 if(c.action==='connect'){if(w.status!=='disconnected')fail('PENDING','Reconcile the original connection before another attempt.');w.connection={id:c.id,status:'pending'};w.status='connecting';}
 else if(c.action==='connection-result'){fixture();if(w.connection?.id!==c.id||!['connecting','connection-unknown'].includes(w.status))fail('IDENTITY','Check the original connection reference.');if(c.result==='connected'){w.status='connected';w.account='demo-account-A';w.network='Polkadot';w.version++;}else if(c.result==='rejected'||c.result==='not-connected'){w.status='disconnected';w.connection.status='rejected';}else if(c.result==='unknown')w.status='connection-unknown';else fail('RESULT','Use a defined connection fixture.');}
 else if(c.action==='switch'){if(w.status!=='connected'||active())fail('PENDING','Resolve any possible signature/submission before changing wallet context.');if(!['account','network'].includes(c.target))fail('CONTEXT','Review account or network.');w.switch={id:c.id,target:c.target,status:'pending'};w.status='switching';w.reviewedVersion=null;}
 else if(c.action==='switch-result'){fixture();if(w.switch?.id!==c.id||!['switching','switch-unknown'].includes(w.status))fail('IDENTITY','Reconcile this original switch.');if(c.result==='accepted'){if(w.switch.target==='account')w.account=w.account==='demo-account-A'?'demo-account-B':'demo-account-A';else w.network='Polkadot';w.version++;w.status='connected';w.switch.status='accepted';}else if(c.result==='rejected'||c.result==='failed'){w.status='connected';w.switch.status=c.result;}else if(c.result==='unknown'){w.status='switch-unknown';w.switch.status='unknown';}else fail('RESULT','Use a defined switch fixture.');}
 else if(c.action==='review'){if(w.status!=='connected'||w.network!=='Polkadot')fail('CONTEXT','Connect and revalidate the exact required network.');if(active())fail('PENDING','Check the original signature or transaction before another review.');const action=walletAction(s,c.actor,c.paymentId);if(!['prepared','approval_waiting'].includes(s.gateC.payments.find(p=>p.id===c.paymentId).state))fail('CALLER','Open this payment’s current owner status.');if(s.expansion.environment.feeMissing||s.expansion.environment.assetMissing)fail('BALANCE','The external fixture cannot cover the exact transfer or fee. No amount is lowered.');w.execution={id:c.id,action,account:w.account,network:w.network,version:w.version,status:'reviewed',at:now};w.reviewedVersion=w.version;}
 else if(c.action==='signature'){const action=exact();if(s.gateC.payments.find(p=>p.id===action.paymentId).state!=='approval_waiting')fail('CALLER','Only the exact caller approval-waiting state permits a signature request.');if(w.execution.status!=='reviewed'||w.reviewedVersion!==w.version||w.status!=='connected'||w.account!==w.execution.account||w.network!==w.execution.network)fail('STALE','Wallet context changed. Review the same action again.');if(Date.parse(now)>Date.parse(w.execution.action.proof.expiresAt))fail('EXPIRED','The caller review expired. Recover its exact outcome.');if(s.expansion.environment.feeMissing||s.expansion.environment.assetMissing)fail('BALANCE','The exact transfer and fee must be covered.');w.execution.status='signature-pending';}
 else if(c.action==='signature-result'){fixture();exact();if(!['signature-pending','signature-unknown'].includes(w.execution.status)||c.id!==w.execution.id)fail('IDENTITY','Check the original signature identity.');if(c.result==='signed')w.execution.status='signed';else if(c.result==='rejected'||c.result==='not-signed')w.execution.status='rejected';else if(c.result==='unknown')w.execution.status='signature-unknown';else fail('RESULT','Use a defined signature fixture.');}
 else if(c.action==='submit'){exact();if(w.execution.status!=='signed')fail('PENDING','Only the existing accepted signature may be submitted.');w.execution.status='submitting';w.execution.transactionId='demo-transaction:'+w.execution.id;}
 else if(c.action==='network-result'){fixture();exact();if(c.id!==w.execution.id||!['submitting','pending','submission-unknown'].includes(w.execution.status))fail('IDENTITY','Check the existing submission; never create another transaction.');if(!['pending','unknown','finalized','reverted'].includes(c.result))fail('RESULT','Use a defined external network fixture.');w.execution.status=c.result==='unknown'?'submission-unknown':c.result;w.execution.finality=c.result==='finalized'?{verifiedFixture:true,at:now,transactionId:w.execution.transactionId}:null;}
 else if(c.action==='disconnect'){if(active())fail('PENDING','Connection changes cannot erase a possible execution. Check the original outcome first.');w.status='disconnected';w.account=null;w.network=null;w.reviewedVersion=null;w.version++;}
 else fail('COMMAND','Unsupported wallet command.');return w;
}
