import {scopeProof} from '../gate-c/model.js';import {walletAction} from './wallet.js';import {canonical} from './checksum.js';
export function createWalletUI(context){
 function view(){const{s,actor,route,device,staticScreen,esc,money,name}=context(),w=s.expansion.wallets?.[actor]||{status:'disconnected'},e=w.execution;let page=route.page||'handoff';
 if(['connecting','connection-unknown','switching','switch-unknown'].includes(w.status))page={'connecting':'connect-pending','connection-unknown':'connect-timeout','switching':'switch-pending','switch-unknown':'switch-unknown'}[w.status];else if(e&&e.action.paymentId===route.payment&&['signature-pending','signature-unknown','signed','submitting','pending','submission-unknown','finalized','reverted'].includes(e.status))page={'submitting':'signed','pending':'submission-pending','submission-unknown':'submission-unknown'}[e.status]||e.status;
 else if(w.status==='disconnected'&&!['chooser','wallet-unavailable','connect-rejected','cancelled','handoff'].includes(page))page='handoff';else if(w.status==='connected'&&['handoff','connect-pending','connect-timeout'].includes(page))page='connected';
 const screen=staticScreen('21',page),main=screen.querySelector('main'),actions=main.querySelector('.actions');main.querySelectorAll('.context,.scope').forEach(n=>n.remove());main.querySelectorAll('.sub').forEach(n=>n.textContent='Local prototype wallet state. Every wallet/provider/network result below is an explicit inert fixture. No wallet, signature or funds are used.');const p=route.payment?walletAction(s,actor,route.payment):null;const walk=document.createTreeWalker(screen,NodeFilter.SHOW_TEXT);let node;while(node=walk.nextNode()){node.textContent=node.textContent.replaceAll('12.50 DOT',p?money(p.transfer.minorUnits,p.transfer.asset,p.transfer.exponent):'the caller’s exact transfer').replaceAll('Maya',p?name(s,p.recipient):'the caller recipient').replaceAll('5F3sa2…Demo9',w.account||'Disconnected');}const boundary=document.createElement('p');boundary.className='notice neutral';boundary.textContent='Inert local wallet fixture · no live connection, signature, network execution or funds.';main.prepend(boundary);
 const facts=[['Wallet',w.status],['Signing account',w.account||'Disconnected'],['Network',w.network||'Not connected'],['Saved receiving addresses','Separate · do not connect or authorize this wallet']];if(p)facts.push(['Exact payment',money(p.proof.amount,p.proof.currency,p.proof.exponent)],['Transfer',money(p.transfer.minorUnits,p.transfer.asset,p.transfer.exponent)],['Fee fixture','0.012000 DOT · not a live quote'],['Recipient',name(s,p.recipient)],['Originating payment',p.paymentId]);if(e&&p?.paymentId===e.action.paymentId)facts.push(['Execution',e.status],['Transaction',e.transactionId||'Not submitted']);const box=document.createElement('section');box.className='card context';box.innerHTML='<div class="context-head"><b>Exact caller and wallet facts</b><span>Local prototype</span></div><div class="context-grid">'+facts.map(([k,v])=>`<span>${esc(k)}</span><strong class="fact">${esc(v)}</strong>`).join('')+'</div>';main.insertBefore(box,actions||null);
 if(!actions){const n=document.createElement('div');n.className='actions';main.append(n);}const list=main.querySelector('.actions');list.innerHTML='';const button=(label,action,value,kind='primary')=>{const n=document.createElement('button');n.className='btn '+kind;n.textContent=label;n.dataset.action='wallet-'+action;if(value)n.dataset.value=value;list.append(n);};
 if(w.status==='connecting'||w.status==='connection-unknown'){button('Demo approved connection','connection-result','connected');button('Demo rejected / verified not connected','connection-result','not-connected','secondary');button('Demo result still unknown','connection-result','unknown','text');}
 else if(w.status==='switching'||w.status==='switch-unknown'){button('Demo switch accepted','switch-result','accepted');button('Demo switch rejected','switch-result','rejected','secondary');button('Demo switch failed','switch-result','failed','secondary');button('Demo result still unknown','switch-result','unknown','text');}
 else if(e&&p?.paymentId===e.action.paymentId&&['signature-pending','signature-unknown'].includes(e.status)){button(e.status==='signature-unknown'?'Demo original signature found':'Demo signature approved','signature-result','signed');button('Demo verified not signed','signature-result','not-signed','secondary');button('Demo signature result unknown','signature-result','unknown','text');}
 else if(e&&p?.paymentId===e.action.paymentId&&e.status==='signed')button('Demo submission started','submit');
 else if(e&&p?.paymentId===e.action.paymentId&&['submitting','pending','submission-unknown'].includes(e.status)){button('Demo network finalized','network-result','finalized');button('Demo found pending','network-result','pending','secondary');button('Demo verified network failed','network-result','reverted','secondary');button('Demo network result unknown','network-result','unknown','text');}
 else if(e&&p?.paymentId===e.action.paymentId&&e.status==='finalized')button('Hand exact result to Complete Settlement','handoff-result');
 else if(w.status==='disconnected'){if(page==='chooser')button('Use inert browser-wallet fixture','connect');else button('Choose a wallet','chooser');}
 else if(page==='switch-account-review'||page==='switch-network-review'){button('Continue in wallet fixture','switch',page==='switch-account-review'?'account':'network');button('Keep current wallet','connected',null,'secondary');}
 else if(page==='action-review'&&p&&e?.status==='reviewed'){button('Approve in wallet fixture','signature');button('Review account switch','switch-review','account','secondary');}
 else{if(p)button('Review this exact payment','review');button('Switch account','switch-review','account','secondary');button('Switch network','switch-review','network','secondary');button('Disconnect wallet','disconnect',null,'text');}
 button(p?'Return to same payment':'Return to account','return',null,'secondary');
 }
 function action(a,el){if(!a.startsWith('wallet-'))return false;const{s,actor,route,commit,push,owner,ledger}=context(),w=s.expansion.wallets?.[actor],e=w?.execution,kind=a.slice(7),value=el.dataset.value;const command=(action,extra={},fixture=false)=>commit({type:'wallet',action,...extra},fixture?'prototype-fixture':undefined);
 if(kind==='return'){if(route.payment)owner('gate-c','#'+new URLSearchParams({page:'payment',id:route.payment}));else owner('gate-d','#page=account');}else if(kind==='chooser'||kind==='connected')push({page:kind});else if(kind==='connect'){command('connect',{id:crypto.randomUUID()});push({page:'connect-pending'});}else if(kind==='connection-result'){command(kind,{id:w.connection.id,result:value},true);push({page:value==='connected'?'connected':value==='unknown'?'connect-timeout':'connect-rejected'});}
 else if(kind==='switch-review')push({page:'switch-'+value+'-review'});else if(kind==='switch'){command(kind,{id:crypto.randomUUID(),target:value});push({page:'switch-pending'});}else if(kind==='switch-result'){command(kind,{id:w.switch.id,result:value},true);push({page:value==='accepted'?'switch-accepted':value==='unknown'?'switch-unknown':value==='failed'?'switch-failed':'switch-rejected'});}
 else if(kind==='review'){command('review',{id:crypto.randomUUID(),paymentId:route.payment});push({page:'action-review'});}else if(kind==='signature'){command(kind);push({page:'signature-pending'});}else if(kind==='signature-result'){command(kind,{id:e.id,result:value},true);push({page:value==='signed'?'signed':value==='unknown'?'signature-unknown':'signature-rejected'});}
 else if(kind==='submit'){command(kind);push({page:'signed'});}else if(kind==='network-result'){command(kind,{id:e.id,result:value},true);push({page:value==='unknown'?'submission-unknown':value==='pending'?'submission-pending':value});}
 else if(kind==='disconnect'){command(kind);push({page:'disconnect'});}else if(kind==='handoff-result'){const p=s.gateC.payments.find(p=>p.id===route.payment);if(e?.status!=='finalized'||!e.finality?.verifiedFixture||canonical(scopeProof(p))!==canonical(e.action.proof))throw Error('Only the exact accepted fixture finality may return to its owner.');const proof=e.action.proof,send=type=>ledger.commit({type,id:p.id,actor,proof,operationId:crypto.randomUUID()},'prototype-fixture');if(p.state==='approval_waiting')send('wallet_submitted');const live=ledger.read().gateC.payments.find(x=>x.id===p.id);if(['submitted','checking','unknown','recovering'].includes(live.state))send('wallet_received');owner('gate-c','#'+new URLSearchParams({page:'payment',id:p.id}));}else return false;return true;
 }
 return {view,action};
}
