const assert=require('node:assert/strict'),M=require('./model.cjs');let assertions=0;const cases=[];
const eq=(a,b)=>{assertions++;assert.deepEqual(a,b);},ok=x=>{assertions++;assert(x);};
const test=(name,fn)=>{fn();cases.push({name,passed:true});};
const ready=(...args)=>{const s=M.create(...args);M.preview(s);return s;};
const sent=(...args)=>{const s=ready(...args);M.submit(s);M.accept(s,s.command.id);return s;};
test('J09 group scope is preserved',()=>{const s=ready();eq(s.review.amountMinor,3000);eq(s.review.sourceItems,['marc-zurich']);eq(s.review.sourceGroups,['zurich']);eq(s.review.payer,'marc');eq(s.review.recipient,'dev');eq(s.review.returnTo,s.context.returnTo);});
test('All-group request has exactly four source groups',()=>{const s=ready('marc','all');eq(s.review.amountMinor,12540);eq(s.review.sourceGroups,['apartment','zurich','ski','geneva']);});
test('Currencies stay separate with explicit scale',()=>{let s=ready('sam','all','CHF');eq(s.review.amountMinor,9110);eq(s.review.displayScale,2);s=ready('sam','all','DOT');eq(s.review.amountMinor,2400000);eq(s.review.displayScale,6);eq(s.review.sourceItems,['sam-hackathon']);});
test('Reverse debt and zero balance cannot be requested',()=>{eq(M.preview(M.create('jeanine','all')).blocked,'nothing-due');eq(M.preview(M.create('jeanine','zurich')).blocked,'nothing-due');});
test('No owner role needed to request your own balance',()=>{const s=M.create('marc','all');s.data.owners.zurich='sam';ok(M.preview(s).amountMinor===12540);});
test('Requester cannot impersonate another payer or viewer',()=>{const s=M.create();s.data.viewer='marc';eq(M.preview(s).blocked,'unavailable');eq(M.submit(s).blocked,'unavailable');});
test('Requests are private to the two participants',()=>{eq(ready().review.audience,['dev','marc']);});
test('Review required before send',()=>{eq(M.submit(M.create()).blocked,'changed');});
test('Changing a note requires another review',()=>{const s=ready();s.note='Different';eq(M.submit(s).blocked,'changed');});
test('Note length validated in model',()=>{const s=M.create();s.note='x'.repeat(161);eq(M.preview(s).blocked,'note');});
test('Offline cannot send',()=>{const s=ready();s.data.online=false;eq(M.submit(s).blocked,'offline');eq(s.requests.length,0);});
test('Reconnection never sends automatically',()=>{const s=ready();s.data.online=false;s.data.online=true;eq(s.requests.length,0);eq(s.command,null);});
test('Repeat submit returns the same pending command',()=>{const s=ready(),a=M.submit(s),b=M.submit(s);eq(a.id,b.id);eq(s.sequence,1);eq(s.requests.length,0);});
test('Acceptance creates one request but never a payment',()=>{const s=ready(),before=M.clone(s.data);const c=M.submit(s);eq(M.accept(s,c.id),'accepted');eq(M.accept(s,c.id),'accepted');eq(s.requests.length,1);eq(s.requests[0].status,'active');eq(s.requests[0].delivery,'queued');eq(s.data,before);});
test('Creation delivery and payment are different states',()=>{const s=sent();ok(M.deliver(s,s.selected,'delivered'));eq(M.current(s).delivery,'delivered');eq(M.current(s).status,'active');eq(M.amount(s),3000);});
test('Late delivery failure does not regress delivered state',()=>{const s=sent();M.deliver(s,s.selected,'delivered');eq(M.deliver(s,s.selected,'failed'),false);eq(M.current(s).delivery,'delivered');});
test('Unknown result cannot create a duplicate',()=>{const s=ready();const c=M.submit(s);ok(M.unknown(s,c.id));eq(M.submit(s).id,c.id);eq(M.retry(s),null);eq(s.requests.length,0);});
test('Check status is not evidence of acceptance',()=>{const s=ready();M.submit(s);M.unknown(s,s.command.id);ok(M.recover(s));ok(M.recover(s));eq(s.command.status,'recovering');eq(s.requests.length,0);});
test('Unknown can resolve accepted without resubmission',()=>{const s=ready();const c=M.submit(s);M.unknown(s,c.id);M.recover(s);eq(M.accept(s,c.id),'accepted');eq(s.requests.length,1);eq(s.sequence,1);});
test('Verified not saved enables same-payload retry',()=>{const s=ready();s.note='';const c=M.submit(s);ok(M.notSaved(s,c.id));const retry=M.retry(s);eq(retry.id,c.id);eq(retry.payload,c.payload);eq(M.accept(s,c.id),'accepted');eq(s.requests.length,1);});
test('Unrelated or late results are ignored',()=>{const s=ready();const c=M.submit(s);eq(M.accept(s,'wrong-id'),'stale');eq(M.notSaved(s,'wrong-id'),false);M.accept(s,c.id);eq(M.notSaved(s,c.id),false);eq(M.unknown(s,c.id),false);});
test('Current balance must match reviewed exact amount',()=>{const s=ready();s.data.items.find(x=>x.id==='marc-zurich').minor=2000;eq(M.submit(s).blocked,'changed');});
test('Version change after send invalidates acceptance',()=>{const s=ready();const c=M.submit(s);s.data.items.find(x=>x.id==='marc-zurich').version=2;eq(M.accept(s,c.id),'changed');eq(s.requests.length,0);});
test('Unrelated item does not block this request',()=>{const s=ready();const c=M.submit(s);s.data.items.find(x=>x.id==='sam-zurich').version=2;eq(M.accept(s,c.id),'accepted');});
test('Only dependent review issues block',()=>{const s=M.create();s.data.issue=true;eq(M.preview(s).blocked,'issue');const sam=M.create('sam','zurich');sam.data.issue=true;eq(M.preview(sam).amountMinor,2290);});
test('Access revoked between send and acceptance denies save',()=>{const s=ready();const c=M.submit(s);s.data.access=false;eq(M.accept(s,c.id),'unavailable');eq(s.requests.length,0);});
test('Group member removed between review and send denies request',()=>{const s=ready();s.data.members.zurich=s.data.members.zurich.filter(x=>x!=='marc');eq(M.submit(s).blocked,'unavailable');});
test('All-group scope cannot silently drop inaccessible sources',()=>{const s=ready('marc','all');s.data.members.ski=['marc'];eq(M.submit(s).blocked,'unavailable');});
test('Identical source request opens existing regardless of note',()=>{const s=sent();s.note='Another note';const p=M.preview(s);eq(p.blocked,'duplicate');eq(p.id,s.selected);eq(s.requests.length,1);});
test('Overlapping group/global request is also blocked',()=>{const s=sent();s.context.scope='all';eq(M.preview(s).blocked,'duplicate');eq(s.requests.length,1);});
test('Separate currency requests do not block each other',()=>{const s=sent('sam','all','CHF');s.context.currency='DOT';eq(M.preview(s).amountMinor,2400000);M.submit(s);eq(M.accept(s,s.command.id),'accepted');eq(s.requests.length,2);});
test('Forged amount or source group is rejected',()=>{const s=ready();s.review.amountMinor=1;eq(M.submit(s).blocked,'changed');M.preview(s);s.review.sourceGroups=['wrong'];eq(M.submit(s).blocked,'changed');});
test('Forged audience is rejected',()=>{const s=ready();s.review.audience.push('luca');eq(M.submit(s).blocked,'changed');});
test('Withdrawal requires requester and preserves data',()=>{const s=sent(),before=M.clone(s.data),p=M.clone(M.current(s).payload);const c=M.withdraw(s);eq(M.accept(s,c.id),'accepted');eq(M.current(s).status,'withdrawn');eq(M.current(s).payload,p);eq(s.data,before);eq(M.amount(s),3000);});
test('Duplicate withdrawal cannot remove twice',()=>{const s=sent();const a=M.withdraw(s),b=M.withdraw(s);eq(a.id,b.id);M.accept(s,a.id);const version=M.current(s).version;eq(M.accept(s,a.id),'accepted');eq(M.current(s).version,version);});
test('Unknown withdrawal stays active and checks do not close it',()=>{const s=sent();const c=M.withdraw(s);M.unknown(s,c.id);M.recover(s);eq(M.current(s).status,'active');eq(M.restore(s),'withdraw-unknown');eq(M.retry(s),null);});
test('Withdrawal retry retains command identity',()=>{const s=sent();const c=M.withdraw(s);M.notSaved(s,c.id);eq(M.retry(s).id,c.id);eq(M.accept(s,c.id),'accepted');eq(M.current(s).status,'withdrawn');});
test('Payment in progress blocks withdrawal',()=>{const s=sent();M.observePayment(s,'payment-progress');eq(M.withdraw(s).blocked,'payment-progress');});
test('Payment race invalidates an in-flight withdrawal',()=>{const s=sent();const c=M.withdraw(s);M.observePayment(s,'payment-progress');eq(M.accept(s,c.id),'changed');eq(M.current(s).status,'payment-progress');});
test('Verified payment observation closes request and prevents re-request',()=>{const s=sent(),before=M.clone(s.data);M.observePayment(s,'paid');eq(M.current(s).status,'paid');eq(M.amount(s),0);eq(M.preview(s).blocked,'nothing-due');eq(s.data,before);});
test('A withdrawn request cannot be delivered afterward',()=>{const s=sent();const c=M.withdraw(s);M.accept(s,c.id);eq(M.deliver(s,s.selected,'delivered'),false);eq(M.current(s).status,'withdrawn');});
test('Back/resume cannot reopen accepted commands',()=>{const s=sent();eq(M.restore(s),'detail');const c=M.withdraw(s);M.accept(s,c.id);eq(M.restore(s),'withdrawn');});
test('Settled items are excluded from later broader scope',()=>{const s=sent();M.observePayment(s,'paid');s.context.scope='all';const p=M.preview(s);eq(p.amountMinor,9540);eq(p.sourceGroups,['apartment','ski','geneva']);ok(!p.sourceItems.includes('marc-zurich'));});
test('Late payment progress cannot regress verified paid',()=>{const s=sent();M.observePayment(s,'paid');eq(M.observePayment(s,'payment-progress'),false);eq(M.current(s).status,'paid');});
console.log(JSON.stringify({ok:true,assertions,scenarios:cases.length,cases},null,2));
